### ISSUE TITLE
Items updated by feed import or manual edition unexpectedly raise different behavior 

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#101]
# What occurs
It seems to have a mis-implementation on update item feature. 
On #97 we've observed that when an item is updated by feed import it raises a push, but if we update an item from admin panel it didn't. Then it means that somewhere code is duplicated, the origin of item (category feed auto or manual) must not change the behavior.

# How to reproduce
check log of push after auto and manual updates

**Comment by juliogreff** [comment]
This is related to #97.
