### ISSUE TITLE
when I create new site an auto generated domain should be auto-filled with title, it doesn't work 

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#106]
# What occurs
https://www.evernote.com/l/APVJFTjRXUZIvK-C30iyJIemNivO5oeJRtwB/image.png

# How to reproduce
Create a new site and fill title, the field domain should be filled, it is not

**Comment by t4deu** [comment]
Already has fixed by #62, but the sitebuilder in RIMOBI don't has updated
