### ISSUE TITLE
add new fields platform and version for devices

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#110]
Need to add new fields platform and version for devices

"devices" : [ {
"uuid" : "c3e60134-fe04-44b8-3568-910536530538", 
"push_id" : "", 
"model" : "GT-I9505",
**"platform": "iOS"**
**"version": "3.2"**
"app_version" : "1.2.0" } ]

**Comment by t4deu** [comment]
Add the fields to entities/VisitorDevice:
```php
class VisitorDevice extends Entity
{
  protected $platform;
  protected $vertion;
  
  public function platform()
  
  public function version()
}
```
Update repositories/VisitorsRepository::dehydrate:
```php
protected function dehydrate($object)
{
  return [
    ...
    devices => [
     ...                                                 
      'platform' => $d->platform(),
      'version' => $d->version,
    ]
  ]
}
```
Update VisitorsController::add_device and VisitorsController::update_device actions:
```php
...
  $device = new VisitorDevice([                                              
    'uuid' => $device_id,
    'platform' => $this->request->get('data:platform'),
    'version'  => $this->request->get('data:version'),                                                   
    'pushId' => $this->request->get('data:push_id'),                         
    'model' => $this->request->get('data:model'),                            
    'app_version' => $this->request->get('data:app_version')                 
  ]);
...
```

These fields will be added to visitors list in sitebuilder dashboard or some new pie chart need be created?

**Comment by juliogreff** [comment]
Please refactor add_device and update_device, removing the duplicated code. Feel free to rename device_id on the update action to uuid, just remember to update any documentation that points to that.

And since you're playing with it, add logging to those two methods. No need to use instances of the logger class, that's what the static methods are for. They also force you to add a component name as first parameter, which is very useful for grepping.

**Comment by t4deu** [comment]
Ok, the add_device action will be removed because isn't used.

And I will follow what is descriped in #9 to add the devices details in the visitors list

**Comment by elbidone** [comment]
The #9 is on backlog as mentioned on my last comment. Current issue doesn't mention any udpates on visitors/list. There's no device details on visitors/list

**Comment by t4deu** [comment]
Ok @elbidone , I asked on the first comment if there will be any changes at visitors list or in the visitors pie charts, and while speaking with @juliogreff he said it may be useful.

**Comment by elbidone** [comment]
I don't think that add_device is not used. What is strange it's create a new device within method update_device. Both actions exists add/update device. The implementation sounds confused.

**Comment by elbidone** [comment]
@julio, maybe we should analyze also the #114 in order to achieve this one. Because if we reuse the same way items and images are managed we can imagine 2 controllers for devices and visitors. And device must be related to a visitor, if not exist on request create it, as done when we create image through api, without item.id. That could solve the #114 and provide an already known structure (copied from items/images) for visitors and devices.

**Comment by julio** [comment]
@juliogreff I think @elbidone's message above was for you

**Comment by juliogreff** [comment]
I don't think creating a spec for #114 is necessary for this one. We can create another controller later on, but it doesn't change the behavior for this one. And in any case, now that I think of it, it doesn't make sense to have device creation as separate methods right now, since it could always be created from the login anyway (passing a "device" parameter), so I'd even be in favor of removing it.

How do the apps work nowadays? Do they send a separate request to add a new device? I think we can avoid that.

**Comment by juliogreff** [comment]
According to discussion in Slack last week: let's keep update_device for the moment, and drop create_device.

@t4deu create a CreateOrUpdateDevice service for this logic. It'll be used by both the login and update_device. Also, your PR contains commits that are unrelated to the feature. Fix that as soon as possible so I can start reviewing it.

**Comment by elbidone** [comment]
Also need to add param "app_build", sorry for the delay.
Below an example of payload:
```json
{
"model":"GT-I8190L",
"platform":"Android",
"version":"4.1.2",
"app_version":"1.2.0",
"app_build":104,
"push_id":"APA91bGjYPOchqRLCO2wSr7QQ1wipr962KjPlutG6O_vsh2QTdIyfjZZUhdLNro1J2hiA0s9jxzDPJkNU7l9F5S_Wtt9Q5KknqHiB08axcqltIw0YQDZBowQm4RyHAjryRxkRE5lNETmOH7I1Ymiakkmrhk4J7iMmA",
"uuid":"b1c69c42-0d9d-71c5-3552-550589379488"}
```

**Comment by t4deu** [comment]
Ok the service will be like:

```php
class CreateOrUpdateDevice
{
  //create or update a device based on the uuid
  public function perform($deviceData, Visitor $visitor)

  protected function update(VisitorDevice $device, Visitor $visitor)

  protected function create(VisitorDevice$device, Visitor $visitor)
}
```
