### ISSUE TITLE
allow to send push even if  site is public

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#114]
that means there no visitors details, only devices

**Comment by elbidone** [comment]
Should be considered with #157 and #7 
My suggestion is to merge visitors collection and users mysql table to a single users collection with roles.
meumobi should consider users.role={admin, editor, visitor}. 
Current sitebuilder use only admin and user (but user role is used as editor). By this way an admin and editor could publish through api using a single account and not an account for sitebuilder and another for the app. 
User will create and manage its own account through api.

User can create a public site where "visitors" can subscribe to receive push.

Below an example of what could be a user object
```
{ "_id" : ObjectId("559578629a645d7e4b25b69c"), "email" : "john.smith@gmail.com", "first_name" : "JOHN", "last_name" : "SMITH", "site_id" : NumberLong(445), "hashed_password" : "8022a454f1682c9ba8e27889e9065272ebde927f", "auth_token" : "377b22b738c3e0b4337af3509145002b962c90c9", "last_access" : "2015-07-08 20:21:08", "should_renew_password" : false, "devices" : [ ], "groups" : [ ] , "role" : "editor", "created" : "2015-07-02 20:21:08", "modified" : "2015-07-02 20:21:08"}
```

last_access instead of last_login
role = {admin, editor, user}
hashed_password, should_renew_password and auth_token are optionals, used it only if site is private

**Comment by juliogreff** [comment]
This issue is going to be split into several others (see below), so we can treat them separately and possibly release them at different times. They'll supersede this issue, so I'm closing it.

#283 - Create docs for new API endpoint for "devices"
#284 - Create new API endpoint for "devices"
#285 - Create Devices repository
#286 - Move devices from Visitors to use DevicesRepository

**Comment by elbidone** [comment]
The issues created by the split don't resolve the initial requirement: send Push to public sites. It seems that push continues to need visitors record and/or private site.
I reopen this issue to allow to send push to devices saved even if site is public.

**Comment by juliogreff** [comment]
(I don't have a meumobi instance right now so I can test, sorry if I'm making obvious questions)

There's nothing in the code preventing a public site from sending push notifs, so I imagine it's only an interface that's missing. What do you expect to happen that is currently not happening?

**Comment by elbidone** [comment]
It continues not working. See test context below.
I've one device registered on site_id 11.
```sh
> db.devices.find({site_id: 11})
{ "_id" : ObjectId("56bbaf5cb5a508b61f478634"), "uuid" : "7F0E776C-D308-48BD-AAE6-C802CB8E774E", "user_id" : null, "site_id" : NumberLong(11), "push_id" : "f154e9d2f800bb02db99133546e50ae4ac49b1fd4eba84359c6c932f84f6024d", "model" : null, "platform" : null, "platform_version" : null, "app_version" : null, "app_build" : null, "created" : ISODate("2016-02-10T21:45:00Z"), "modified" : ISODate("2016-02-10T21:54:40Z") }
```

I've created on site_id 11 a new item, it generated a job to push notif, but the push was not sent as you can see on logs,... or better... as you can't see on logs. The worker finished without sending Push and no log to understand why.

```sh
[2016-02-10 23:12:01] sitebuilder.INFO: start executing worker {"job_id":"56bbb57cb5a508705a478635","job_type":"push_notification","job_params":{"item_id":"56bbb57cb5a508705a478634","category_id":79},"component":"worker_manager"}
[2016-02-10 23:12:01] sitebuilder.INFO: script finished {"script_id":"updateevents-high","component":"cli"}
[2016-02-10 23:12:01] sitebuilder.INFO: worker finished {"job_id":"56bbb57cb5a508705a478635","job_type":"push_notification","job_params":{"item_id":"56bbb57cb5a508705a478634","category_id":79},"component":"worker_manager"}
```
