### ISSUE TITLE
update_events.php raises a Fatal error: 'String could not be parsed as XML'

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#118]
I've ran it on CSE env.
No mor informations on logs to know which feed is responsible for it.

```
Fatal error: Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php:26
Stack trace:
#0 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php(26): SimpleXMLElement->__construct('')
#1 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/script/update_events.php(26): meumobi\sitebuilder\services\UpdateEventsService->call()
#2 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/config/cli.php(19): {closure}()
#3 /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/script/update_events.php(27): meumobi_lock('update_events_', Object(Closure))
#4 {main}
  thrown in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php on line 26
```

**Comment by t4deu** [comment]
Need to refactor the update_events service to have a better log and transform the Service into a Worker, like what was done with the update_feeds
.
The error is caused by an invalid url, here is the correspondent log, with the invalid url:
> log/php.log
[12-Jun-2015 13:06:40 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/meumobi/PROJECTS/int-meumobilesite.com/releases/20150415113636/sitebuilder/lib/meumobi/sitebuilder/services/UpdateEventsService.php:26

log/sitebuilde.log
[2015-06-12 10:06:40] sitebuilder.DEBUG: downloading feed {"url":"http://services.int-meumobi.com/docs/tests/santander-eventos.xml"}

**Comment by t4deu** [comment]
Replace UpdateEventsService.php for workers/UpdateEvents.php with the followings methods.
Composition will be used to avoid code duplication and reuse the UpdateFeedsWorker methods, the class UpdateItems will be created and used in the UpdateFeeds an UpdateEvents workers.
```php
namespace meumobi\sitebuilder\workers;
class UpdateItems
{
  public getCategory()
  public getExtension()
  public getExtensionIds()
  public getItem()
}

namespace meumobi\sitebuilder\workers;
class UpdateEvents extends Worker
{
  $updateItems = new UpdateItems()
  
  public perform()
  
  public updateFromFeed($feed)
  
  public updateEvent($event,$feedItem)
  
  public getCategory()
  {
    return $updateItems->getCategory();
  }
  ...
}
```

The logs will be the same as in the UpdateFeeds worker.

**Comment by juliogreff** [comment]
UpdateFeedsWorker should not update feed items right now, it depends on #68. What would UpdateItems do?

**Comment by t4deu** [comment]
It's the compositive class used by UpdateFeeds and UpdateEvents workers, to allow reuse methods that are commom in both

**Comment by juliogreff** [comment]
Currently, UpdateFeeds *does not update items*, why do you call the service like it does? Why can't you just use the CreateItems service we created in #111?

**Comment by t4deu** [comment]
Don't understand, the UpdateFeed is a worker that periodically update category items using an rss feed.
How can I use the CreateItems service to update the items from the rss?

**Comment by t4deu** [comment]
To fix the Fatal error.
Add the Exception to the class namespace:
```php
use Exception; 
class UpdateEventsService extends
```
Update the logs to add extension information:
```php
} catch ( Exception $e ) {
  Logger::error('events update error',
    'message' => $e->getMessage(),
    'extension' => $extension,
    'site id' => $category->site_id,
    'category id' => $category->d,
  )
}
```

**Comment by juliogreff** [comment]
That only logs all errors, but doesn't do anything to fix it. Shouldn't we do something about it? As in, disable that URL, so the error doesn't keep happening over and over and over? Should we tell the site's owner that there's something wrong?

Those are the questions that need answering, not only logging the errors and moving on.

**Comment by t4deu** [comment]
Well we can disable the extension and send an alert email or somehow tell to the site' owner, but I can't answer if we shoud.

For now I think that disabling the extension may be enough.

**Comment by juliogreff** [comment]
Only disabling the extension sounds fine for now, you can open a pull request for this.
