### ISSUE TITLE
visitors/login returns an empty errors array

### ISSUE THREAD

**Issue by juliogreff** [meumobi/sitebuilder#122]
When I log in with a valid visitor and a valid device, I still get an "errors" array. I know it's empty, but including it might confuse API clients, so it's better to remove it. Therefore, the "errors" array should only be included when we actually have errors.

```
{
    "errors": [],
    "success": true,
    "token": "dbea997b978117fdbf91ff35721f2c37f88fd7f7",
    "visitor": { ... }
}
```

**Comment by t4deu** [comment]
This was because the "errors" was added by default in the VisitorsController::login action response:
```php
$response = [
  errors => [],
  success => true
];
````
I will check before adding the errors:
```php
if ($errors) {
 $response['errors'] = $errors;
}
```
