### ISSUE TITLE
Item Type Evaluation and Cleanup

### ISSUE THREAD

**Issue by juliogreff** [meumobi/sitebuilder#125]
In the spirit of simplifying the platform so we can move forward, I'm investigating which item types are still relevant nowadays.

The item types we have today are the following:

- **Articles**: either created from a news feed or from the web interface. I believe it's pretty clear that we want to keep this one. The only special thing about it is the format, which can be "html" (returned as is) or "bbcode" (parsed and rendered before we return it as HTML)
- **Business**: has an address that gets geocoded, and can be searched for
- **Events**: has a start and end date
- **ExtendedArticles**: has a string "enclosure" field. From a quick glance, this one seems pointless, and is a good candidate to be removed. Do we use it for any clients, or do we want to keep it for any reason?
- **Links**: nothing special about it. I'm ok keeping it, but if we don't use it anywhere, I'd be happy to remove.
- **Products**: nothing special. Keep it or not, I'm good with either.
- **MerchantProducts**: doesn't seem to have anything special about it from looking at the class, but I do know we import them from somewhere. Do any of the fields in there have any special meaning? Also, why do we need to make a distinction between this and Products?
- **Promotions**: has a start and end date as well. Nothing special besides that. I'm good with keeping it.
- **Restaurants**: has geocoding. There's a "ratings" field that seems to be special somehow. How does it work and do we still use it for any client? Also, there's a "related" there that puzzles me a little bit. What is it related to?
- **Stores**: geocoding, related products, nothing special. We can keep it.
- **Users**: I get very worried about this one, mainly because it looks like we save unencrypted passwords. Also because it looks a lot like the visitors functionality we now have. Can we burn it with fire?

Thoughts?

/cc @elbidone @t4deu

**Comment by t4deu** [comment]
Currently the most used types are Articles and Events.
For the others we certainly can remove the ExtendedArticles and maybe remove the Users type.
The remaining are not in use, but can probably be in the future.

**Comment by juliogreff** [comment]
So it seems like we indeed don't use **ExtendedArticles**, so I'll open a PR to remove it.

Regarding the **Users** type, it is enabled in the following segments: *agencia3*, *ipanemax* and *oi*. The first question is: do we use those segments? And if we do, do we need the **Users** type in there?

Regarding **MerchantProducts**, it is used only in the *fbiz* segment. Same questions as above apply.

@elbidone any input on this?

**Comment by elbidone** [comment]
- Articles: Used on all Sites
- Business: keep it, used on SantacasaJF
- Events: Used on IRmobi
- ExtendedArticles: **can remove it**
- Links: I'd like to keep it despite we don't use it
- Products: Should be used for a Commerce App, like restaurant. keep it
- MerchantProducts: This type fit GoogleShopping model, maybe could be merged with Products. I'll check it later
- Promotions: **can remove it** if we generalize the schedule (start, end dates) to all types. 
- Restaurants: this type was used for lafarge project, where Users rate the restaurant. **can remove it**
- Stores: I like to keep a type using the related concept, ie. Products belongs Stores. Suggest to keep it 
- Users: used on Lafarge project, **can remove it**

**Comment by juliogreff** [comment]
I don't like the idea of generalizing start and end dates to all types. And I'm ok with keeping **Promotions**, so I'll leave it alone, and I'll take into consideration the start/end dates in the spec.

I'm strongly in favor of merging **MerchantProducts**, I just need to know what was specific to it so I can take it into account.

I'll remove **Restaurants** and **Users**. PR will follow.

**Comment by juliogreff** [comment]
@elbidone @t4deu any info about **MerchantProducts**?

**Comment by t4deu** [comment]
I think we could merge the MerchantProducts with the Products, providing that the Merchant Feed Import also be available for the Products
