### ISSUE TITLE
How do we use skins and themes?

### ISSUE THREAD

**Issue by juliogreff** [meumobi/sitebuilder#127]
I continue to investigate how our platform works, so we can document it properly and move on to the next level.

One thing that I found and is not entirely clear to me is how we use skins and themes nowadays? I do understand that we only expose the skin through the API, and the theme is something that only the sitebuilder knows about, mostly to group some skins and provide them default values that the user can update. Or at least that's how I view them at the moment, feel free to correct me on that.

My bigger question is how do we use them from the apps and the template-engine? What does it expect, only a list of colors? Do we still intend to provide it with images?

/cc @elbidone @t4deu

**Comment by t4deu** [comment]
Please Victor correct me if I'm wrong.

Currently there no need to provide images, since we are using icon fonts int the themes now.

But besides colors, there are layout custom options and translation tokens now. Each theme can have different layout options or translation tokes. that are specified in the [themes.json](http://meu-template-engine.int-meumobilesite.com/themes.json).

Here an example of the API response:
GET http://mobi.comunique-se.com.br/api/cielopt.int-meumobilesite.com/performance

        "theme": {
            "id": "536aa94a701796d2508b4567",
            "theme_id": "rimobi",
            "parent_id": "5356559970179676028b4567",// parent skin
            "colors": {
                "defaultBg": "#21a1dd"
            },
            "assets": [],// not used anymore
            "tokens": {// translations
                "contact": "Fale com RI"
            },
            "layout_alternatives": {// layout options
                "footer": "ir",
                "home": "headlines",
                "nav": "nav-horizontal",
                "navbar": "navbar-fixed"
            },
            "html5": "true"// flag to prevent WOPE parsing
        }

**Comment by elbidone** [comment]
A skin corresponds to the configuration of the site/app theme. Everything we can configure should be setted there.
- colors: configure any customizable color of theme
- assets: ie. facebook icon. It's wrong to say that is not used anymore
- tokens: configure the wording of theme, ie. "contact": "Entre em contato conosco". It doens't correspond to translation.
- layout_alternatives: allow to configure some behaviors/variations on theme. It often corresponds  to css class, ie: "navbar": "navbar-fixed" or "navbar-float"

Each theme provide default skins and user can customize it to create its own based on a parent skin (default values).
