### ISSUE TITLE
authentication with visitors.email should not be case sensitive

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#130]
The mail is not case sensitive, but on site-builder if we add visitor John.Smith@gmail.com try to signin with john.smith@gmail.com it doesn't work. 

Mail should be saved on lowercase and compared using lowercase.

**Comment by elbidone** [comment]
It generates a lot of "Invalid visitor" on siemens project

**Comment by t4deu** [comment]
Update the VisitorsRepository::findForAuthentication, to lower case and trim the email before search the database:
```php
public function findForAuthentication($siteId, $email, $password)                 
{                                                                                 
  $conditions = [                                                                 
    'email' => strtolower(trim($email)), 
```

Also update the Visitor::setEmail to lower case and trim the email, this will persist the email in the correct format:
```php
public function setEmail($email)
{
	$this->email = strtolower(trim($email));
}
```

Obs. The others finders of the VisitorsRepository that use the email in the conditional also need this update, a way, that I have not found, to make this in one single place would be better, [like comented here](https://github.com/meumobi/sitebuilder/pull/145#discussion_r34628495).
