### ISSUE TITLE
When I run site-builder/script/import_visitors.php segments strings.yaml are not considered

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#137]
# What occurs
I've ran on ELEFANTE import_visitors.php. But the mail that visitors received didn't display the correct content.
For example inviting a visitor, on infobox segment on PROD, instead of displaying on footer "Para mais informações, entre em contato conosco: onlinecommunications.br@siemens.com..." as setted on segments/infobox/strings.yaml it shows the value of token visitors/mail.footer from config/locales/py.yaml "Para mais informações, entre em contato conosco: contact@meumobi.com..."

# How to reproduce
Because the feature of replace token with segments/strings.yaml didn't work, cf #132, I've fixed the code directly on PROD. So to reproduce you should:
- Update sitebuilder/app/views/visitors/password_mail.htm.php to include <?= s('visitors/mail/add.body')?>
- add on segments/infobox/strings.yaml:
```
'visitors/mail':
  footer: '<br /><br /> Para mais informações, entre em contato conosco: onlinecommunications.br@siemens.com<br/>Ou acesse a <a href="http://www.siemens.com.br/infobox">página do InfoBox na intranet</a><br /><br />Atenciosamente, <br /> <br />Equipe de Comunicação da Siemens'
```
- add on config/locales/pt.yaml
```
'visitors/mail':
  footer: '<br /> <br /> Para mais informações, entre em contato conosco: contact@meumobi.com<br /><br />Atenciosamente, <br /> <br />Equipe meumobi'
```
- add on config/locales/en.yaml
```
'visitors/mail':
  footer: '<br /> <br /> For further informations please contact us: contact@meumobi.com<br /><br />Regards, <br /> <br />Team meumobi'
```

- Import visitor, using php import_visitors.php -s [SITE_ID] -f [FILE_PATH]

You should observe that instead of displaying on mail the footer of infobox segment it display values from en or pt.yaml

**Comment by tadeuvalentt** [comment]
It's the same translation problem of #138, the fix is the also the same.

**Comment by elbidone** [comment]
ok, but the description doesn't mention any translation issue but bad use of segment tokens
