### ISSUE TITLE
Title of visitor invite mail is different if you use web dashboard or import script

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#138]
# What occurs
I've updated the title of password of invite visitor mail on visitors_controller.php. It works fine when I add visitor from dashboard but not on when I add visitor using script import_visitors.php.
I've checked the code and see that code is duplicated, then I should edit both files.
sendVisitorEmail function is duplicated on ImportVisitorsCsvService.php and visitors_controller.php
sitebuilder/lib/meumobi/sitebuilder/services/ImportVisitorsCsvService.php

# How to reproduce
Because the feature of replace token with segments/strings.yaml didn't work, cf #132, I've fixed the code directly on PROD. So to reproduce you should:
- Update sitebuilder/app/controllers/visitors_controller.php
```
$data['title'] = s('visitors/mail/add.subject', $site->title);
```
- add on segments/infobox/strings.yaml:
```
'visitors/mail':
  footer: '<br /><br /> Para mais informações, entre em contato conosco: onlinecommunications.br@siemens.com<br/>Ou acesse a <a href="http://www.siemens.com.br/infobox">página do InfoBox na intranet</a><br /><br />Atenciosamente, <br /> <br />Equipe de Comunicação da Siemens'
```
- add on config/locales/pt.yaml
```
'visitors/mail':
  footer: '<br /> <br /> Para mais informações, entre em contato conosco: contact@meumobi.com<br /><br />Atenciosamente, <br /> <br />Equipe meumobi'
```
- add on config/locales/en.yaml
```
'visitors/mail':
  footer: '<br /> <br /> For further informations please contact us: contact@meumobi.com<br /><br />Regards, <br /> <br />Team meumobi'
```

- Import visitor, using php import_visitors.php -s [SITE_ID] -f [FILE_PATH]

You should observe that instead of displaying on mail the footer of infobox segment it display values from en or pt.yaml

**Comment by tadeuvalentt** [comment]
The title is not translated because the method that make the translations `s` is defined in the `app_controller.php`, 

Because of this, the translation is only available for controllers.

To make the translation available for the Services we can move the `s` and `__` methods to the I18n class, and create an initializer to setup the global methods:

```
//config/initializers/translation.php
function __($key) {                                                                 
  I18n.__($key);                             
}                                                                                
                                                                                    
function s($key) {                                                                  
  I18n.s($key);                                    
}  
```

About the duplicated code that send the visitor email, we can create the SendVisitorPasswordEmail service, like what already was done for the user password email, and use the service in visitors_controller and ImportVisitorsCsvService

**Comment by elbidone** [comment]
ok, but the description doesn't mention any translation issue but bad use of segment tokens

**Comment by tadeuvalentt** [comment]
Yes, I reproduced the error, it's happens because the bootstrap dispatcher, that setup the yaml path for the tokens, based on the segment, is not called by the script, to fix that need to get set the $dispatcher in the cli.php, and call it in the import_script:
```php
// config/cli.php
$dispatcher = require '/config/bootstrap.php';
setSegment($segment) {
  $dispatcher($segment);
}

// script/import_visitors.php
...
 setSegment($site->segment);
...
```

**Comment by tadeuvalentt** [comment]
The problem not happens with the web dashboard because the dispatcher is called by the segment `index.php`:
```php
// segments/meumobi/public/index.php
$dispatcher = '/sitebuilder/config/bootstrap.php'
$dispatcher($segment);
```

**Comment by elbidone** [comment]
ok, so what about your previous comment "The title is not translated because..." ?

**Comment by tadeuvalentt** [comment]
There is nothing wrong with the translations, only the segment tokens that are not loaded, but the refactoring to remove the translations methods from the app_controller still valid.

**Comment by elbidone** [comment]
ok @tadeuvalentt, for next issues **remember the rules**, 4 headings (not 3), it's the second time in 2 days I need to re-post following lines for you:

# What occurs

# How to reproduce

# Why it occurs

# How to fix

**Comment by t4deu** [comment]
# Why it occurs
It's happens because the bootstrap dispatcher, that setups the yaml path for the tokens, based on the segment, is not called by the import script.

**Comment by t4deu** [comment]
After look inside the config/bootstrap.php, I noticed that besides load the segment files, the bootstrap dispatcher also start the lithiun Dispatcher to handle the sitebuilder requests.

This is unecessary and resource consuming for the command line scripts. To prevent this, we can extract to a separeted method (loadSegment) the segement loading of the bootstrap dispatcher, and call only this method in the scripts.

**Comment by tadeuvalentt** [comment]
Why it occurs

It's happens because the bootstrap dispatcher, that setups the yaml path for the tokens, based on the segment, is not called by the import script.

**Comment by tadeuvalentt** [comment]
After look inside the config/bootstrap.php, I noticed that besides load the segment files, the bootstrap dispatcher also start the lithiun Dispatcher to handle the sitebuilder requests.

This is unecessary and resource consuming for the command line scripts. To prevent this, we can extract to a separeted method (loadSegment) the segement loading of the bootstrap dispatcher, and call only this method in the scripts.

**Comment by tadeuvalentt** [comment]
## How to test
1. Deploy the branch `fix/load-segment-strings-in-command-line` on INT.
1. Follow the steps described in **How to reproduce** section of this issue.
1. Check the segment strings tokens in the received email.
