### ISSUE TITLE
log/sitebuilder.log raised > 2Go, should use rotation. Too big to be used

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#139]

**Comment by t4deu** [comment]
The log rotation already existed, it was removed, so if there is nothing different from the previous version I can revert the it.

**Comment by t4deu** [comment]
Update the ```lib/meumobi/sitebuilder/Logger.php``` and ```config/bootstrap.php ``` with the previous log path:
```php
class Logger
{
	public function __construct($level = null)
	{
		...
		$handler = new \Monolog\Handler\StreamHandler(APP_ROOT . '/log/sitebuilder-' . date('Y-m-d') . '.log', $level);
		...
	}
}
////
define('ERROR_LOG', dirname(dirname(__DIR__)) . '/log/php-' . date('Y-m-d') . '.log');
...
```

**Comment by tadeuvalentt** [comment]
The logrotate was configured in the servers INT, PROD and RIMOBI
