### ISSUE TITLE
import_visitors didn't process Mapper::url()

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#141]
# What occurs
It's necessary on segments to provide personalized documentation links on mail
Need to use it on 
sitebuilder/app/views/visitors/password_mail.htm.php

# How to reproduce
you can run import_visitors on INT updating manualy password_mail.php to use MApper::url()

**Comment by elbidone** [comment]
I've migrated urls to tokens to work. Pleaseif you fix it add a comment here how it works, I'll update php files to use it

**Comment by elbidone** [comment]
What we need: If I want to use a different "guideline" doc on segments. I will declare Mapper::url('/docs/guidelines.pdf') thta should be converted to [SEGMENT].[DOMAIN]/docs/guidelines.pdf

I don't if Mapper::url is the correct method, but the behavior above is the correct one

**Comment by tadeuvalentt** [comment]
The Mapper generates url based on the $_SERVER global variable. And It's not the recommended way to generate links. Instead we can use the Html::link helper, that calls the Mapper::url internally.

To support the segment based url, the segment domain must be set in the segment config file:
```php
// segments/meumobi/config.php
Config::write('Segment', [
  'id' => 'meumobi',
  'domain' => 'meumobi.com'
  ...
])
```

After that we can update the `lib/core/dispatcher/Mapper.php` to get the segment value, which I do not recommend, since it's a core class of the framework, that don't know nothing about the business model.

Or add an `url` method, that generates an url based on the segment domain, to the Segment model(not confortable with this since it's a Model).

And update the Html::link method to accept the Mapper as a parameter:
```php
class HtmlHelper
{
  public function link ($text, $url = null, $mapper = Mapper); //the Mapper is the default, so there is no need to update older links
}
``` 

And them generate the links like this:
```
$this->link('/docs/guidelines.pdf', ..., $segment)
```

**Comment by tadeuvalentt** [comment]
While looking at the code, I foud that the `MeuMobi` class already implement an `url` method based on the segment settings. It can be used like this:

```
MeuMobi::url('/docs/guidelines.pdf') => http://inverstors.meumobi.com/docs/guidelines.pdf
```
But the domain MUST be set in the segment config file, like described in previous comments, otherwise will not work.

And the correct way to generate an link is stil using the Html::link helper, so I updated to allow use the `MeuMobi`  instead of the `Mapper` class:
```
$this->html->link('Link text', $url, $attributes, true, 'MeuMobi');
```

**Comment by elbidone** [comment]
sitebuilder/app/views/users/forgot_password_mail.htm.php
$this->html->link(
- $url = Mapper::url('/users/reset_password/' . $user->id . '/' . $user->token, true), 
- $url)

`<a href="http://meumobi.com/users/reset_password/281/ab7dda6471319e5085be6e40fc6a127b441e1d97">http://meumobi.com/users/reset_password/281/ab7dda6471319e5085be6e40fc6a127b441e1d97</a>`

sitebuilder/app/views/users/invite_mail.htm.php
$this->html->link(
- s('Click to confirm invite'), 
- $link)

`<a href="http://enterprise.meumobilesite.com/accept_invite/login/1bad4f17af7310aa95e915f6dfab1854b5e6b0b0">Clique para confirmar o convite</a>`

where 
`sitebuilder/app/models/users.php:				
$data['link'] = Mapper::url("/accept_invite/login/{$data['token']}", true);`

sitebuilder/app/views/users/confirm_mail.htm.php
$this->html->link(
- $url = Mapper::url('/users/confirm/' . $user->id . '/' . $user->token, true), 
- $url, 
- array('style' => 'color: #FF0000'))

I didn't test view above, seems not being used anymore

## Conclusions
1. **html->link is not used with relative links on email views** but final url previously build by Mapper::url or on controller (on forgot_password_mail). Then you must update these views to **not create  inconsistencies** mixing relative and absolute paths with Mapper, MeuMobi and controller based methods to fill url.
It seems that the three files above are exhaustive but check it. I've checked using `$ grep "html->link" -R sitebuilder/app/ |grep Mapper` and `$ grep "html->link" -R sitebuilder/app/ |grep "\$link"` commands. 
2. Looking into your commit I've seen that the **$mapper is used on HtmlHelper.php with 2 arguments, but MeuMobi::url signature use only one argument, how could it work ?** (`$attr['href'] = $mapper::url($url, $full);`)

I imagine, the solution is to refactor all html->link calls contained on email views to use relative path with MeuMobi class AND build url inside views and not controllers. 
Also update MeuMobi class to add the 2nd argument: 
```
public static function url($path, $full)
        {
            return $full ? "http://" . self::domain() . $path : $path;
        }
```

**Comment by tadeuvalentt** [comment]
1. The refactoring of the views is necessary, likewise the refactoring and cleaning of the entire `html` helper, I will update the views, tell me if is necessary update the helper.
1. It's [perfectly fine](http://stackoverflow.com/questions/6051309/can-you-pass-more-parameters-than-a-function-expects) pass more parameters, they CAN be ignored. And it seems just extra code to generate relative urls based on segments.

**Comment by tadeuvalentt** [comment]
Some email messages need to me updated to handle multiple segments, like the forgot password, that have the segment name hardcoded:
> <?= s('Hi, %sYou have requested the reset of your **MeuMobi** password. In order to do that you should click on link below.', $user->firstname)

Need to pass the segment name to the string:
> <?= s('Hi, %sYou have requested the reset of your **%s** password. In order to do that you should click on link below.', $user->firstname, **$segment->name**)

**Comment by elbidone** [comment]
There's no need of refactoring of htmlHelper. Only fix inconsistencies moving links built on controller to views and segment's name as shown on previous comment.
Why default mapper is Mapper and not MeuMobi ? Seems that linkHelper should use MeuMobi::url($url, $full) and not the generic one, then all calls will use same component. Check if there's a valid reason to use Mapper or risk of regression

**Comment by tadeuvalentt** [comment]
The Mapper::url can:

* Handle external urls, 'http://google.com'
* Hangle hash urls, '#some-place'
* Build array based urls, ['controller' => 'items', 'action' => 'show'...]
* Normalize, prepend, append and remove extra slash '/' when necessary

But, besides the external url, these features are not used currently, so I think we can make the MeuMobi the default mapper of the `link` helper.

**Comment by tadeuvalentt** [comment]
## How to test

1. Add a segment link to an email template: `$this->html->link(s('Pdf Guide'), "/docs/guidelines.pdf", [], true, 'MeuMobi')`
1. Send the email
1. Open the recieved email and check if the link domain is the same of the segment

**Comment by tadeuvalentt** [comment]
Views that use Mapper:
```
$ ack Mapper::url sitebuilder/app/views/
sitebuilder/app/views/layouts/home.htm.php
9:		<link rel="shortcut icon" href="<?php echo Mapper::url("/images/layout/favicon.png") ?>" type="image/png" />

sitebuilder/app/views/layouts/default.htm.php
8:		<link rel="shortcut icon" href="<?php echo Mapper::url('/images/layout/favicon.png') ?>" type="image/png" />
37:										<a href="<?php echo Mapper::url('/users/change_site/'.$site->id) ?>">
44:									<li class="new"><a href="<?php echo Mapper::url('/create_site/theme') ?>"><?php echo s('new mobile site...') ?></a></li>

sitebuilder/app/views/layouts/login.htm.php
7:		<link rel="shortcut icon" href="<?php echo Mapper::url('/images/layout/favicon.png') ?>" type="image/png" />

sitebuilder/app/views/layouts/error.htm.php
7:		<link rel="shortcut icon" href="<?php echo Mapper::url("/images/layout/favicon.png") ?>" type="image/png" />

sitebuilder/app/views/layouts/register.htm.php
7:		<link rel="shortcut icon" href="<?php echo Mapper::url("/images/layout/favicon.png") ?>" type="image/png" />

sitebuilder/app/views/dashboard/_photos.htm.php
2:	<a class="link" href="<?php echo Mapper::url('/sites/business_info#business-photos') ?>">

sitebuilder/app/views/dashboard/_analytics.htm.php
11:            <div id="analytics_report" data-url="<?php echo Mapper::url('/dashboard/analytics_report') ?>">

sitebuilder/app/views/dashboard/_description.htm.php
2:	<a class="link" href="<?php echo Mapper::url('/sites/business_info#businessDescription') ?>">

sitebuilder/app/views/dashboard/_weblinks.htm.php
2:	<a class="link" href="<?php echo Mapper::url('/sites/business_info#business-social') ?>">

sitebuilder/app/views/dashboard/_timetable.htm.php
2:	<a class="link" href="<?php echo Mapper::url('/sites/business_info#timeable') ?>">

sitebuilder/app/views/dashboard/_news.htm.php
2:	<a class="link" href="<?php echo Mapper::url('/sites/news') ?>">

sitebuilder/app/views/dashboard/_location.htm.php
2:	<a class="link" href="<?php echo Mapper::url('/sites/business_info#business-address') ?>">

sitebuilder/app/views/dashboard/_stocks.htm.php
2:	<a class="link" href="<?php echo Mapper::url('/sites/business_info#stocks') ?>">

sitebuilder/app/views/dashboard/_visitors.htm.php
3:	<a class="link" href="<?php echo Mapper::url('/visitors') ?>">

sitebuilder/app/views/dashboard/index.htm.php
30:				<a class="link" href="<?php echo Mapper::url('/categories') ?>">
46:					<a href="<?php echo Mapper::url('/placeholder_creator/menu') ?>">
53:					<a href="<?php echo Mapper::url('/placeholder_creator/stores') ?>">
60:					<a id="products" href="<?php echo Mapper::url('/placeholder_creator/products') ?>">
67:					<a href="<?php echo Mapper::url('/placeholder_creator/news') ?>">

sitebuilder/app/views/dashboard/_contact.htm.php
2:	<a class="link" href="<?php echo Mapper::url('/sites/business_info#business-contact') ?>">
```

**Comment by elbidone** [comment]
Use helper with default MeuMobi mapper on all email, see #173 for exhaustive list. 
Avoid use of Mapper on helper call, it should lead to an useless  "double Mapping"
<?php echo $this->html->link($url = Mapper::url('/users/confirm/' . $user->id . '/' . $user->token, true), $url, array('style' => 'color: #FF0000')) ?>

**Comment by tadeuvalentt** [comment]
The Mapper has replaced by the MeuMobi mapper in views, controllers and models.

I tested the views and emails by accessing pages and sending the emails.
