### ISSUE TITLE
provide a script to check_import_visitors.php

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#142]
Sending email could raise status={Sent, User unknown, Service unavailable}.
In order to provide a report of campaign we'll develop a command-line to read the csv that has been imported and check on /var/log/mail.log the status of mail sent.
If exist doublons on log consider the latest record
See below an extract of /var/log/mail.log
```
Jul  1 19:26:06 ks387594 sm-mta[31054]: t61HQ6Zf031052: to=<tiago.marques@siemens.com>, delay=00:00:00, xdelay=00:00:00, mailer=esmtp, pri=123537, relay=hylas.siemen
s.com. [217.194.35.76], dsn=5.1.1, stat=User unknown
Jul  1 19:26:25 ks387594 sm-mta[31217]: t61HQOHK031215: to=<paulo.silvajr@siemens.com>, delay=00:00:01, xdelay=00:00:00, mailer=esmtp, pri=123537, relay=hylas.siemen
s.com. [217.194.35.76], dsn=5.1.1, stat=User unknown
Jul  1 19:28:17 ks387594 sm-mta[32244]: t61HSHsk032242: to=<tais.sousa@siemens.com>, delay=00:00:00, xdelay=00:00:00, mailer=esmtp, pri=123531, relay=meleagros.sieme
ns.com. [217.194.35.77], dsn=5.0.0, stat=Service unavailable
Jul  1 19:28:18 ks387594 sm-mta[32248]: t61HSHJN032246: to=<adriana.arruda@siemens.com>, delay=00:00:01, xdelay=00:00:00, mailer=esmtp, pri=123539, relay=meleagros.s
iemens.com. [217.194.35.77], dsn=5.0.0, stat=Service unavailable
Jul  6 17:32:51 ks387594 sm-mta[2939]: t66FWnfZ002939: to=<contact@meumobi.com>, delay=00:00:02, xdelay=00:00:02, mailer=esmtp, pri=30000, relay=aspmx.l.google.com. [IPv6:2a00:1450:400c:c04::1a], dsn=2.0.0, stat=Sent (OK 1436196646 n3si31456261wib.44 - gsmtp)
```

**Comment by elbidone** [comment]
This script should overwrite the csv adding status column and values for each records
We should consider a script for last import we've realised for Siemens.
And if necessary another solution for future imports, using for example http://swiftmailer.org/docs/sending.html#finding-out-rejected-addresses

**Comment by t4deu** [comment]
Extract the email, status and date from var/log/mail into a tmp/mail_report.csv  file.
Load the import csv passed by parameter and loop each line, on each loop:

* Search for the latest occurrence of the current visitor email in the tmp/mail_report.csv.
* Update the import csv file by inserting the status and date of the current visitor.
* Log the visitor email and status

Remove the tmp/mail_report.csv after finish the loop
