### ISSUE TITLE
options of script import_visitors are not consistent

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#146]
password-strategy is binary, default OR auto
import-mode is also binary, exclusive OR inclusive

But the treatment and call are different
```
$options = getopt('f:s:', ['exclusive','password-strategy::']);

$site = Model::load('Sites')->firstById($options['s']);

require 'segments/' . $site->segment . '/config.php';
$import = new ImportVisitorsCsvService();
if (isset($options['exclusive'])) $import->setMethod(ImportVisitorsCsvService::EXCLUSIVE);
if (@$options['password-strategy']) $import->setPasswordStrategy($options['password-strategy']);
$import->setSite($site);
$import->setFile($options['f']);
echo $import->import();
```

On cli it means
```
$ php sitebuilder/script/import_visitors.php --password-strategy default --exclusive -s 2 -f ../import.csv
```

**So why --password-strategy should accept an argument and --exclusive not ?**

Why don't we use something like this:
--auto-password
  new password should be auto-generated
--exclusive
  importation should erase all old records not present on current import
--resend-invite
  send a new invite to all visitors updated whose last_login is not null. It means that a new password is generated
-s [SITE_ID]
-f [FILE_PATH]

By default import_visitors use default password, inclusive mode and doesn't resend-invite to updated users (don't udpate password field)

**Comment by t4deu** [comment]
Update the script/import_visitors.php
```php
$options = getopt('f:s:', ['auto-password', 'exclusive', 'resend-invite']);
...
if (isset($options['auto-password'])) $import->setPasswordStrategy(VisitorPasswordGenerationService::RANDOM_PASSWORD);
```
Update the ImportVisitorsCsvService::import to check the last_login before resend the visitor email:
```php
   ...
    if ($visitor->id()) {
      $this->logger()->info("updating visitor with email: {$visitor->email()}");

      if ($resend && $visitor->lastLogin()) {
        $password = $passwordGenerationService->generate($visitor, $this->passwordStrategy, $this->getSite());
        $this->sendVisitorEmail(['email' => $visitor->email(), 'password' => $password]);
      } else {
        // create visitor
      }
   ...
```
