### ISSUE TITLE
the datetime that appears on dashboard/visitors for last_login it based on server not site config

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#147]
# What occurs
on visitors dashboard time of last_login is wrong. Should use the site settings managed on /sites/general to define the local time

**Comment by t4deu** [comment]
Following the logic that is in ItemsController::prepareDates

Add Visitor::updateLastLogin() to update the last_login based on the site time zone
```php
public function updateLastLogin() {
  $timezone = date_default_timezone_get();
  date_default_timezone_set($this->site()->timezoneId());
  
  $this->setLastLogin(date('Y-m-d H:i:s'));
  
  date_default_timezone_set($timezone);
}
```
Obs.
* We can do conversion within the "setLastLogin" and not create the "updateLastLogin" method.
* If necessary we can create a service to login the visitor and extract the logic from the VisitorsController::loginUser
* In the database the field type of "last_login" is "string". I think the best is to use the correct type to represent dates. In the future if necessary 
create reports based on the last login date. It will be difficult to work with strings instead of dates.

**Comment by juliogreff** [comment]
We *should* do the conversion in setLastLogin. Fixing the type is fine too.
The service is not necessary right now.

**Comment by t4deu** [comment]
Update VisitorsRepository dehydrate and hydrate methods to set the correct field types:
```php
  protected function hydrate($data)
  {
   $data[last_login] = $data[last_login] ? date('Y-m-d H:i:s', $data['last_login']->sec); : null;
   return new visitor($data);
	}
	
  protected function dehydrate($object)                                                                                                                
  {                                                                                                                                                    
    return [                                                                                                                                           
      'last_login' => $object->lastLogin() ? new MongoDate(strtotime($object->lastLogin()) : null,
      ...
    ]
  }
```

**Comment by elbidone** [comment]
Do we need a conversion of existing records from (string) last_login to (date) last_login ?
What impact on dashboard visitor ?

**Comment by t4deu** [comment]
*Do we need a conversion of existing records?*
Yes

*What impact on dashboard visitor?*
None, since the date object is converted to string by the repository when it retrieves the data from the database

**Comment by t4deu** [comment]
Migration for convert strings to date in the file db/migrations/convert_last_login_to_date.php
```php
class ConvertLastLoginToDate
{
  public static function migrate($connection)
  {
    $connection = Connections::get('default')->connection;

    $command = " 
      db.visitors.find().forEach(function(visitor) {
				if (visitor.last_login) {
					visitor.last_login = new Date(visitor.last_login);
					db.visitors.save(visitor);
				}
			});
    ";

    $connection->execute($command);
  }
}
```

**Comment by t4deu** [comment]
Make the conversion in the ```setLastLogin``` isn't working because the method is automatically called by the VisitorsRepository::hidrate to setup the entity data retrieved by the database, converting the dates  multiple times.

We cold use the [updateLastLogin()](https://github.com/meumobi/sitebuilder/issues/147#issuecomment-122057118) to make the conversion or update the date format to include the  timezone to prevent incorrect timezones convertions.

I prefer to use the updateLastLogin() because is more simple.

**Comment by juliogreff** [comment]
You could use a date time object that has timezone information. [PHP has a built in for that](http://php.net/manual/en/class.datetime.php). It is much better than dealing with raw strings.

If you do that, though, you'll need to check the places where this is serialized/deserialized.

**Comment by t4deu** [comment]
Convert the DateTime object to MongoDate in the VisitorRepository: 
```php
  protected function hydrate($data)
  {
   $data[last_login] = $data[last_login] ? $data['last_login']->toDateTime() : null;
   return new visitor($data);
    }

  protected function dehydrate($object)                                                                                                                
  {                                                                                                                                                    
    return [                                                                                                                                           
      'last_login' => $object->lastLogin() ? new MongoDate($object->lastLogin()->getTimestamp()) : null,
      ...
    ]
  }
```

Update Visitor::setLastLogin() to set the correct timezone
```php
  public function setLastLogin(DateTime $lastLogin)                                          
  {       
  	$lastLogin->setTimezone(new DateTimeZone($this->site()->timezoneId()));                                                                          
    $this->lastLogin = $lastLogin;                                                  
  }  
```

Update the VisitorsController::loginUser to set the correct value:
```php
protected function loginUser()                                                                                                                       
{ 
	$visitor->setLastLogin(new DateTime('NOW'));
}
```

Update the app/views/visitors/index.htm.php
```php
<td><?= $visitor->lastLogin() ? $visitor->lastLogin()->format('Y-m-d H:i:s') : ?></td> 
```
