### ISSUE TITLE
push without any group setted should send to "all visitors of the site" not all visitors

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#151]
# What occurs
We use same App for several sites. When a news is restricted for a group of user it send push only for token registered for group selected. But when none group is selected it send push without any token specified, it means for pushwoosh all registered for app. But all registered on app are not subscribers of the site. Then, **when meumobi send push it should ALWAYS specified tokens on Pushwoosh API request**.

**Comment by t4deu** [comment]
It's a bug, not and enhancement.

Because the devices already are filtered by the site if no group is found:
```php
protected function getDevicesTokens($item)
{
  $groups = $item->to('array')['groups'];

  if ($groups) {
    $visitors = $repository->findBySiteIdAndGroups($this->getSite()->id, $groups);
  } else {
    $visitors = $repository->findBySiteId($this->getSite()->id);
  }
  ...
 }
```
But if the site not have any visitor that already logged in, this will result in an empty array.

To fix check before send the notification:
```
public function perform()
{
    if (!$devices) {
      Logger::info('push_notification', 'no devices available', $logData);
      return;
    }
   ...
}
```
