### ISSUE TITLE
scheduled article appears before setted date

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#152]
# What occurs
On infobox project the item 549d7b049a645d2166f5c9d7, was scheduled to be released at 3pm today, 10/07. But at 10:am it's already published. It seems that push notification was not sent yet.
The time zone setted on site.settings is correct "Sao Paulo".

![posts___infobox](https://cloud.githubusercontent.com/assets/9011612/8619634/f3e8f66c-26ee-11e5-8f24-16fba736aa8a.png)

**Comment by juliogreff** [comment]
This is not an issue with the publication itself. ```GET /items/latest``` has a bug, it is not filtering by ```is_published``` correctly.

**Comment by t4deu** [comment]
Update the ItemsController::action to filter by is_published:
```php
public function latest()
{
      $params = [ 
      'conditions' => [
        ....
        'is_published' => true
      ], 
      ....
}
```
