### ISSUE TITLE
payload sent to pushwoosh api is missing on logs

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#155]
# What occurs
In order to debug paypload should appears on logs

**Comment by t4deu** [comment]
The lib gomoob/php-pushwoosh responsible for sending and parsing the request to pushwoosh have this method to get the data sent to the API:
> CreateMessageRequest::toJSON();

But I don't see a way to get the HTTP request payload, since the request is made inside the lib

**Comment by elbidone** [comment]
What's the difference between "data sent to the API" and "request payload" ?

**Comment by t4deu** [comment]
For me none, but the difference between what is being already logged and what is returned by the ```CreateMessageRequest::toJSON();``` is that the latter also provide the static auth token and the site.pushwoosh_app_id. So I needed to make sure of what is to be logged

**Comment by t4deu** [comment]
Update the lib/pushwoosh/Push.php, log the ```CreateMessageRequest::toJSON();```, the method only works after create the message, if called before a ```Gomoob\Pushwoosh\Exception\PushwooshException``` is thrown:
```php
  public static function notify($appId, $content, $devices)
  {
   ....
    $response = static::getClient($appId)->createMessage($request);
    // only after create the message
    Logger::debug('push_notification', 'request payload', $request->toJSON());
   ...
```

This generates the following log:
```
[2015-07-13 17:44:10] sitebuilder.DEBUG: request payload {
    "application": "0000-0000",
    "applicationsGroup": null,
    "auth": "z8we...",
    "notifications": [
        {
            "ignore_user_timezone": true,
            "send_date": "now",
            "content": "...",
            "devices": [
                ...
            ],
            "ios_badges": "+1"
        }
    ],
    "component": "push_notification"
}
```
