### ISSUE TITLE
Seems confusing when api use response status 200 with error on body

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#168]
If I send a /mail without message (mandatory field) it should raise an error on api response but the response status sent is 200.
I think it should be 422. Because client framework will call success callback if response.status is 200

**Comment by t4deu** [comment]
Need just to thrown the proper exception instead or return the error message to fix this issue:
```php
class MailController extends ApiController                                          
{                                                                                
  public function index()                                                           
  {                                                                               
    if (!$this->request->get('data:name') ||                                        
      !$this->request->get('data:mail') ||                                          
      !$this->request->get('data:message')) {                                       
      throw new InvalidArgumentException('missing parameters');                       
    }
```

But the status 422 isn't suported by the lithium framework, changing the status to the default(500). 
To send the 422 status I need to set the status with raw php or update the framework.

The list of supported statuses is available in the file ```lib/lithium/net/http/Response.php```:
```php
    /**
	 * Status codes.
	 *
	 * @var array
	 */
	protected $_statuses = array(
		100 => 'Continue',
		101 => 'Switching Protocols',
		200 => 'OK',
		201 => 'Created',
		202 => 'Accepted',
		203 => 'Non-Authoritative Information',
		204 => 'No Content',
		205 => 'Reset Content',
		206 => 'Partial Content',
		300 => 'Multiple Choices',
		301 => 'Moved Permanently',
		302 => 'Found',
		303 => 'See Other',
		304 => 'Not Modified',
		305 => 'Use Proxy',
		307 => 'Temporary Redirect',
		400 => 'Bad Request',
		401 => 'Unauthorized',
		402 => 'Payment Required',
		403 => 'Forbidden',
		404 => 'Not Found',
		405 => 'Method Not Allowed',
		406 => 'Not Acceptable',
		407 => 'Proxy Authentication Required',
		408 => 'Request Time-out',
		409 => 'Conflict',
		410 => 'Gone',
		411 => 'Length Required',
		412 => 'Precondition Failed',
		413 => 'Request Entity Too Large',
		414 => 'Request-URI Too Large',
		415 => 'Unsupported Media Type',
		416 => 'Requested range not satisfiable',
		417 => 'Expectation Failed',
		500 => 'Internal Server Error',
		501 => 'Not Implemented',
		502 => 'Bad Gateway',
		503 => 'Service Unavailable',
		504 => 'Gateway Time-out'
	);
```

**Comment by elbidone** [comment]
I think 422 is closer to 417 => 'Expectation Failed' than 500 Internal Error Server

**Comment by t4deu** [comment]
The 400 seems more correct, since the spec says:
>**400 Bad Request**
The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing)

The 417 says:
>**417 Expectation Failed**
The server cannot meet the requirements of the Expect request-header field.

The Google's OAuth 1.0 implementation returns a 400 response when POST parameters are missing or unsupported.

Source:
* https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error
* http://stackoverflow.com/questions/3050518/what-http-status-response-code-should-i-use-if-the-request-is-missing-a-required#comment9696649_3050561
