### ISSUE TITLE
Service of extractCoverThumbOfMedia: Save thumbnails of items.media

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#172]
The purpose of this issue is to provide when possible a thumbnail for media managed on meumobi.
We'll firstly focus on pdf, but the solution should managed others format of document like video for example.

When a media is saved on item (RSS meaning) the service extractCoverThumbOfMedia should extract and save on item a [media:thumbnail](http://www.rssboard.org/media-rss#media-thumbnails)

Service should be called by meumobi Workers each time a new item w/ media is saved

**Comment by mguilarducci** [comment]
In this case I would create an Interface with a factory method that creates the objects by parameters.
For example: PDF URL -> PDF converter, YouTube URL -> YouTube converter, etc.

Each converter would be an implementation for this interface.

This interface would have a method `convert` that creates the thumbnail with custom options or default options.

We could use ImageMagick and Ghostscript to convert the PDF files.
There is a lib for that in PHP, but we can use the `exec` command to invoke the ImageMagick's command line.
What is better? I don't know. I suppose the PHP lib.

What do you think?

**Comment by elbidone** [comment]
I think it should easier to use php. Did you test the quality of result ?

You should Test the quality of the export with an example of pdf. You can use this one:
http://cielo.riweb.com.br/FeedMeuMobi.aspx?IdCanal=zVuoCf0kO9yMP8t7HCm8kw==

The convertion you recommend is similar to code below ? if yes how did you do without downloading the pdf ? 
http://www.binarytides.com/convert-pdf-image-imagemagick-php/
```
$pdf_file   = 'demo.pdf';
$save_to    = 'demo.jpg';
 
$img = new imagick();
 
//this must be called before reading the image, otherwise has no effect - "-density {$x_resolution}x{$y_resolution}"
//this is important to give good quality output, otherwise text might be unclear
$img->setResolution(200,200);
 
//read the pdf
$img->readImage("{$pdf_file}[0]");
 
//reduce the dimensions - scaling will lead to black color in transparent regions
$img->scaleImage(800,0);
 
//set new format
$img->setImageFormat('jpg');
 
// -flatten option, this is necessary for images with transparency, it will produce white background for transparent regions
$img = $img->flattenImages();
 
//save image file
$img->writeImages($save_to, false);
```

To test on command line
http://codetheory.in/convert-split-pdf-files-into-images-with-imagemagick-and-ghostscript/
```
$ convert file.pdf[0] image.png
```

**Comment by mguilarducci** [comment]
Yes, it is similar to what I am thinking about, but I didn't try the PHP code yet. I was waiting for the vagrant box.
When I said "without download" it meant that is not necessary save the file to convert it when we are executing the IM's command line.
On the background of course it is downloading the files.

We can do: 
```
$ convert http://path-to-pdf.com/blabla[0] -thumbnail x300 thumbnail-blabla.png
```

But it doesn't matter. It must run on PHP anyway.
May the PHP lib works like the command line.

Thanks for the files example. I noticed the quality with them was bad. I was trying with other files.
I will improve it.

**Comment by juliogreff** [comment]
I'd go with the PHP library. ```exec``` shells out (creating unnecessary processes), and then there's always the risk of unescaped/badly escaped input, so it is to be avoided as much as possible.

I wouldn't start with factories or interfaces just yet. Start with the PDF converter, and let's build from there. Smallest possible thing first, so we can see results. You can create the class ```\meumobi\sitebuilder\thumbnailers\PdfThumbnailer``` (our newer classes live in ```sitebuilder/lib```).

I supplied the vagrant box (check #175 for instructions). Let me know if you need any further help.

**Comment by elbidone** [comment]
meumobi uses phpthumb/ThumbLib.inc.php for images management. This library uses imageMagick so I recommend to use it to convert pdf ([see example of phpthumb call to convert pdf](http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x57)).  

I suppose you'll work with remote files, so no need to download.

On this first moment we'll not cover:
- resizeImage feature.
- deleteFile, if parent item and/or media is deleted 

Inspired by lib/meumobi/sitebuilder/workers/MediaFilesizeWorker.php you'll implement a generic Media Thumbnailer called lib/meumobi/sitebuilder/workers/MediaThumbnailerWorker.php, with these 3 functions below:
- perform
- addThumbnail
- getRemoteFileThumbnail (with best resolution)

Where to save ? => Model::load('Images')->getPath("pdfThumbnail")
Get Infos (height, width, length, path, type) ? =>  Model::load('Images')->getImageInfo($path, $filename) // add width, height params if not exist

### Content below is not needed for this issue, it's only to explain why we can't reuse Images code
On meumobi, Images are manipulated on app/models/images.php class, applying following workflow:
- download image based on url, downloadFile()
- save on disk, saveImage() 
- save on db, saveImage()
- create thumbnails, based on meumobi's settings, resizeImage()

Images are saved on a mysql table, using foreign_key to item.
For each image saved meumobi create thumbs according to its configuration. Thumbs paths are not saved anywhere, they are deducted of configuration. We should check later if we'll use same convention or save all thumbnails path on db.

**Comment by elbidone** [comment]
> Deixei em evidencia certos tratamentos que nao iremos resolver nesse primeiro momento: deleteFile, resizeImage, thumbnail.path vs thumbnail.url (caso do youtube por exemplo)
Tambem vamos deixar de lado a migraçao do thumbnail Video para esse Worker que esta criando, mas deixei os nomes genericos para contempla-lo. 
Por enquanto tambem so ira adicionar o Worker no Service ItemCreation. Depois iremos alterar isso para que seja chamado cada vez que item criado ou alterado.

@juliogreff put on your radar these pending tasks to add them later

**Comment by mguilarducci** [comment]
The `phpthumb` in your example (https://github.com/JamesHeinrich/phpThumb) is not the same in meumobi (https://github.com/masterexploder/PHPThumb).

This `phpthumb` (meumobi) should use GD and Imagick, but there is no imagick implementation yet.

There is a GD implementation in `phpthumb` dir that I believe that is working well with images. 

The `PhpThumbFactory::create($src) in phpthumb/ThumbLib.inc.php`  doesn't recognize PDF files and throws an exception `File is not a valid image`.

Look at this issue: https://github.com/masterexploder/PHPThumb/issues/29. Is this the official phpthumb repo? I suppose so. :disappointed: 

So what do we do? Should we implement it? Should we go in other way?

**Comment by elbidone** [comment]
@juliogreff I've tried to add a pdf on INT but the thumbnailer failed

Check below the logs and mongo record

```
[2015-11-06 21:29:01] sitebuilder.INFO: start add medias file size {"item id":"[object] (MongoId: {\"$id\":\"563d0d78b5a50813336473f6\"})"} 
[2015-11-06 21:29:01] sitebuilder.INFO: Media file size successfully added {"item id":"[object] (MongoId: {\"$id\":\"563d0d78b5a50813336473f6\"})"} 
[2015-11-06 21:29:01] sitebuilder.INFO: start executing worker {"worker":"meumobi\\sitebuilder\\workers\\MediaThumbnailerWorker","job id":"563d0d78b5a50813336473f8","job type":"media_thumbnailer","component":"workers"} 
[2015-11-06 21:29:01] sitebuilder.INFO: start create pdf thumbnails {"item_id":"[object] (MongoId: {\"$id\":\"563d0d78b5a50813336473f6\"})"} 
[2015-11-06 21:29:06] sitebuilder.INFO: Can't create thumbnail on item {"exception":"[object] (ImagickException(code: 1): WriteBlob Failed `uploads/pdf_thumbnail/9316c9af2ffd59c4c44627f49206c5a1.png' @ error/png.c/MagickPNGErrorHandler/1728 at /home/meumobi/PROJECTS/int-meumobi.com/releases/20151019215300/sitebuilder/lib/meumobi/sitebuilder/services/PdfThumbnailer.php:23)","file":"http://infobox.meumobilesite.com/docs/Como_Instalar_InfoBox-iOS.pdf","item_id":"[object] (MongoId: {\"$id\":\"563d0d78b5a50813336473f6\"})"} 
[2015-11-06 21:29:06] sitebuilder.INFO: Media thumbnails created {"item_id":"[object] (MongoId: {\"$id\":\"563d0d78b5a50813336473f6\"})"} 
```

```
> db.items.find({ "_id" : ObjectId("563d0d78b5a50813336473f6")})
{ "_id" : ObjectId("563d0d78b5a50813336473f6"), "author" : "", "created" : ISODate("2015-11-06T20:28:40.180Z"), "description" : "", "groups" : [ ], "guid" : "", "is_published" : true, "link" : "", "medias" : [ 	{ 	"type" : "application/pdf", 	"length" : NumberLong(670103), 	"title" : "passo a passo", 	"url" : "http://infobox.meumobilesite.com/docs/Como_Instalar_InfoBox-iOS.pdf" } ], "modified" : ISODate("2015-11-06T20:29:06.742Z"), "order" : NumberLong(13), "parent_id" : NumberLong(31), "published" : ISODate("2015-11-06T20:27:00Z"), "site_id" : NumberLong(6), "thumbnails" : [ ], "title" : "Um teste pra ver thumbnail de pdf", "type" : "articles" }
>
```

**Comment by elbidone** [comment]
- Why following msg on log if thumbnailer failed "[2015-11-06 21:29:06] sitebuilder.INFO: ***Media thumbnails created***..." ?

I've created manually the missing directory uploads/pdf_thumbnail with it didn't solve the issue
