### ISSUE TITLE
FIX reset password mail: remove Error logs and apply same UI styles used on others mails

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#173]
![_meumobi__reset_password_request_-_victor_dias_meumobi_com_-_meumobi_mail](https://cloud.githubusercontent.com/assets/9011612/8879238/9d95e5fe-3206-11e5-90a1-d3f8bef29442.png)

**Comment by elbidone** [comment]
It's not the 1st time I open this issue, the 1st time it was hidden updating php configuration to not show Notice, this workaround is not acceptable. You should FIX the notice and not hide it. Also, the style is not compliant with others mails

**Comment by t4deu** [comment]
Extract the email sending from the Users model to the SendForgottenUserPasswordMail service, also add the site to the email params to fix the issue:
```php
class SendForgottenUserPasswordMail
{
  public function send($params)                                    
  {   
  	list($user, $site) = ParamsValidator::validate($params, ['user', 'site'])                                                                              
    if (!Config::read('Mail.preventSending')) {                                     
      $segment = MeuMobi::currentSegment();                                         
                                                                                    
      $mailer = new Mailer(array(                                                   
        'from' => $segment->email,                                                  
        'to' => array($user->email => $user->fullname()),                           
        'subject' => s('[MeuMobi] Reset Password Request'),                         
        'views' => array('text/html' => 'users/forgot_password_mail.htm'),          
        'layout' => 'mail',                                                         
        'data' => array(                                                            
          'user' => $user,
          'site' => $site,                                                          
          'title' => s('[MeuMobi] Reset Password Request')                          
        )                                                                           
      ));                                                                           
      $mailer->send();                                                             
    }                                                                               
  }
} 
```

Remove the unecessary styles from the mail template, to make it compliant with the other emails:
```php
<p>                                       
    <?php echo s('Hi, <b>%s</b>. <br/><br/>You have requested the reset of your MeuMobi password. In order to do that you should click on link below.', $user->firstname()) ?>
</p>
<br/>                                                                                
<p>                                                         
    <?php echo $this->html->link($url = Mapper::url('/users/reset_password/' . $user->id . '/' . $user->token, true), $url) ?>
</p>                                                                                
~       
```

**Comment by t4deu** [comment]
The subject of the email must have the site or segment title?

Currently i'ts hard coded to "meumobi":
```php
...
 'subject' => s('[MeuMobi] Reset Password Request'), 
```

**Comment by elbidone** [comment]
@tadeu you should respect the consistency of the platform and not consider each case isolated. So check how are threated the subjects of the others mails and do your recommendation considering as high priority to maintain consistency

**Comment by t4deu** [comment]
The subjects of the others emails, except of visitors emails, are also hard coded to "MeuMobi", for example :
```php
protected function sendConfirmationMail($created)                                 
{                                                                                 
  $this->sendMail($segment->email,
    '[MeuMobi] Account Confirmation',                                           
    'users/confirm_mail.htm',                                                   
  );                                                                                                                                                
}
```
I think they must be the dynamic current segment title, since the users are registered in the segment, not on an specific site.

**Comment by t4deu** [comment]
List os email titles:
```
User invite, app/models/users.php, s('Invited by %s', $user->fullname())
User confirmed invite, app/models/users.php, "Invite confirmed"
Site Admin User confirmed invite, app/models/users.php, s('%s confirmed the invitation', $user->fullname())
User Welcome, app/models/users.php, s("Welcome to %s", $segment->title)
User Account Confirmation, app/models/users.php, s('[MeuMobi] Account Confirmation')
User Reset Password, app/models/users.php, s('[MeuMobi] Reset Password Request')

Scheduled import finished, app/models/categories.php, s('[MeuMobi] Category import scheduled')

Api Contact, app/controllers/api/MailController.php, s('api_mail_contact', $site->title)

Visitor Welcome, lib/meumobi/sitebuilder/services/ImportVisitorsCsvService.php, s('[%s]: Get started', $this->getSite()->title)
Visitor Reset password, lib/meumobi/sitebuilder/services/ResetVisitorPassword.php, s('[%s]: New password', $site->title)
```

**Comment by elbidone** [comment]
I move to #204 the fixes of inconsistencies

**Comment by elbidone** [comment]
This easy-to-test issue remains:
https://www.evernote.com/l/APUvIsKuVfdH9YhnDHp3RkgOCM3dOQzMsQkB/image.png

How could we close it if it's remains ? which tests have been done ?

**Comment by tadeuvalentt** [comment]
To fix the issue on all emails, and make the email sending consistent, we need to create a service for each email type and extract the responsibility of sending the emails from models and controllers.

Also update the `layouts/mail.htm.php` to not get the title from the `$site` object directly, instead the title will be provided by the service.

List of emails that need to be extracted to a service:
* User Account Confirmation - users/confirm_mail.htm.php
* User Invite confirmation - users/invite_confirmed_mail.htm.php
* Site admin Invite confirmation- users/invite_confirmed_host_mail.htm.php
* User invite - users/invite_mail.htm.php
* User welcome - users/welcome_mail.htm.php
* Categories import finished - categories/confirm_import_mail.htm.php
* Contact from site - sites/contact_mail.htm.php

We can also extract the actions that sends the emails from models and controllers to the services, like the ResetVisitorPassword service that resets the visitor password and sends the email, but this is a much bigger refactoring.

**Comment by elbidone** [comment]
@juliogreff  Despite Service creation errors on body remains and mail subject is now not translated, it displays token. Then to resume it's worse and worse...
See screenshot below copied form INT today:
https://www.evernote.com/l/APWhtU5COudAFL0_j-AOM_-1__7fnVcjPCsB/image.png

Mail raised by the following service: 
sitebuilder//lib/meumobi/sitebuilder/services/SendForgottenUserPasswordMail.php:	'subject' => s('users/mail/reset_password:subject', $segment->title)

**Comment by elbidone** [comment]
And concerning the send forgot password, the link on mail to reset password always use a default segment, on INT it's meumobi, but it should use the segment of user requesting the password!!!
