### ISSUE TITLE
Images from enclosure tag of Rss are not saved anymore

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#180]
# What occurs
Since new release rel-2.6.3, images referenced on enclosure tag of RSS are saved as media and not images as expected.

# How to reproduce
Check Category 7115 from site 445 (infobox)

# Why it occurs
@t4deu indicates on slack that should happens because the conditional has been modified on this release

> Antes
> https://github.com/meumobi/sitebuilder/blob/cc62b7928d96be4ba2a093a1fbc9b3fd8d6eda76/sitebuilder/lib/meumobi/sitebuilder/workers/UpdateFeedsWorker.php#L408
> Depois
> https://github.com/meumobi/sitebuilder/blob/master/sitebuilder/lib/meumobi/sitebuilder/services/UpdateNewsFeed.php#L307
> mas a condicional antiga também está com problema, porque alem de salvar a imagem do item, um item media também é criado para a imagem

**Comment by elbidone** [comment]
I've updated manually UpdtaeNewsFeed.php on PROD, see below, it continues not working 

```
...
  protected function extractMediaFromEnclosure($article, $xpath)
  {
    $filter = function($enclosure) {      return $enclosure->get_link() && (!$enclosure->get_medium() || $enclosure->get_medium() == 'image');
    };
...
```

**Comment by t4deu** [comment]
I tested in local and INT, and the fix is working, with the extra media bug that I informed, but working.

here an example of the siemens feed imported:
> http://int-meumobi.com/api/santander.int-meumobi.com/categories/70/items/
