### ISSUE TITLE
media.length is not computed anymore when I add a pdf since rel-2.6.3

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#183]
# What occurs
I've added a new media (type pdf) on item, the length was not computed and appears as "length" : "-1"

# How to reproduce
Add any pdf as media and check on db its length

> db.items.find({site_id: 458}).sort({created: -1}).limit(1)
{ "_id" : ObjectId("55bbce769a645d884b8b4567"), "author" : "", "created" : ISODate("2015-07-31T19:46:01.693Z"), "description" : "Post de test", "groups" : [ ], "guid" : "", "is_published" : true, "link" : "", "medias" : [     {       "type" : "application/pdf",     "length" : "-1",        "title" : "siemens",    "url" : "http://infobox.meumobilesite.com/docs/resultados.pdf" } ], "modified" : ISODate("2015-08-03T12:55:02.508Z"), "order" : NumberLong(5), "parent_id" : NumberLong(7109), "published" : ISODate("2015-07-31T19:37:00Z"), "site_id" : NumberLong(458), "thumbnails" : [ ], "title" : "Test pdf", "type" : "articles" }
>

**Comment by t4deu** [comment]
I cold not reproduce the error, tested in local, INT and PROD, with the same media file:
> http://infobox.meumobilesite.com/docs/resultados.pdf

And all tests had a correct media file size:
```
http://meumobi.com/api/basetestcategories.meumobi.com/categories/7090/items
{
    "items": [
        {
            "medias": [
                {
                    "type": "application/pdf",
                    "length": 148242,
                    "title": "Media Title",
                    "url": "http://infobox.meumobilesite.com/docs/resultados.pdf"
                },
                {
                    "type": "application/pdf",
                    "length": 148242,
                    "title": "Media Again",
                    "url": "http://infobox.meumobilesite.com/docs/resultados.pdf"
                }
            ],
....
```

But I noted that the logs need to be refactored, to allow a better debug:
```
$ meumobi.com/current$ grep '55bbce769a645d884b8b4567' log/sitebuilder.log 
[2015-07-31 21:46:02] sitebuilder.INFO: start add medias file size {"item id":"[object] (MongoId: {\"$id\":\"55bbce769a645d884b8b4567\"})"} 
[2015-07-31 21:46:03] sitebuilder.INFO: Media file size successfully added {"item id":"[object] (MongoId: {\"$id\":\"55bbce769a645d884b8b4567\"})"} 
```

**Comment by elbidone** [comment]
What means a "better debug" ? if you don't mention the problem and proposition we can't respond anything

**Comment by t4deu** [comment]
Closing because can't be reproduced.

The issue #199 has created to improve the logs

**Comment by elbidone** [comment]
I've reproduced it today.

# How to reproduce
I've added following media on
```

{       "type" : "application/pdf",     "length" : NumberLong(0),       "title" : "Webinar: investidor móvel",         "url" : "https://drive.google.com/uc?export=download&id=0Bzfx1cNAAzhsTTM4UVdZaFRrS0E" }
```

no errors on log 

```
[2015-08-28 20:58:25] sitebuilder.INFO: job created {"job id":"55e0af519a645d496947e132","type":"media_filesize","priority":0,"params":{"item_id":"556f030f9a645d840bd7fd02"},"component":"workers"} 
[2015-08-28 20:59:03] sitebuilder.INFO: start add medias file size {"item id":"[object] (MongoId: {\"$id\":\"556f030f9a645d840bd7fd02\"})"} 
[2015-08-28 20:59:04] sitebuilder.INFO: Media file size successfully added {"item id":"[object] (MongoId: {\"$id\":\"556f030f9a645d840bd7fd02\"})"}
```

**Comment by t4deu** [comment]
The errors are not the same, the first says that the media.length is not computed and the length is set to -1, now the media.length is computed, but the response of the file request is invalid.

Apparently google drive does not work well with the curl:
```
$ curl -v https://drive.google.com/uc?export=download&id=0Bzfx1cNAAzhsTTM4UVdZaFRrS0E
< HTTP/1.1 400 Bad Request
< Content-Type: text/html; charset=UTF-8
< P3P: CP="This is not a P3P policy! See http://www.google.com/support/accounts/bin/answer.py?hl=en&answer=151657 for more info."
< x-chromium-appcache-fallback-override: disallow-fallback
< Date: Fri, 28 Aug 2015 20:24:20 GMT
< Expires: Fri, 28 Aug 2015 20:24:20 GMT
< Cache-Control: private, max-age=0
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
* Server GSE is not blacklisted
< Server: GSE
< Set-Cookie: NID=70=UiakGi5A9MbowVQN8yFyvwFIvhLTB5osZ73ssqReuON4QEWHADFlfhsThToe5kz-ImSX_1yT-XNi2vzI_o1WUNHBIgEHdrVKYmgDMog0-i3IQ5XYMFMhuUtC-WFwdE1b;Domain=.google.com;Path=/;Expires=Sat, 27-Feb-2016 20:24:20 GMT;HttpOnly
< Accept-Ranges: none
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
```

In the response they point [this url](http://www.google.com/support/accounts/bin/answer.py?hl=en&answer=151657).

I'm checking if there is any curl setting to fix it

**Comment by elbidone** [comment]
It could be the same issue, because before the worker process length is "", so if it was -1 it means it was processed.

Please re-check the implementation of this feature it seems not "robust"

**Comment by tadeuvalentt** [comment]
The process media.length is set to 0, it's because the worker can't  google drive files, the issue #230 has created to solve this.
