### ISSUE TITLE
Improve log of the MediaFileSIze worker

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#199]
The current log don't have the size persisted, or if an error prevented to recover the file size:
```
[2015-07-31 21:46:02] sitebuilder.INFO: start add medias file size {"item id":"[object] (MongoId: {\"$id\":\"55bbce769a645d884b8b4567\"})"} 
[2015-07-31 21:46:03] sitebuilder.INFO: Media file size successfully added {"item id":"[object] (MongoId: {\"$id\":\"55bbce769a645d884b8b4567\"})"} 
```

Also note that the logic is inside the worker, when the most appropriate is to be in a service.

**Comment by elbidone** [comment]
I don't understand the issue, could explain "What Occurs" and "How to Reproduce" ?
"don't have the size persisted," means that log should indicate the size file ? I don't think so
"if an error prevented to recover the file size", ok so it concerns which worker or service ?
If I want to investigate I need the id of media where it is ?  only with item.id I can't retrieve the media processed

OBS: be aware that the log message should be consistent, starts with upper case or not but not both: "start add medias..." and "Media file size..."
