### ISSUE TITLE
Unrelevant logs message, missing item and/or category, site

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#203]
# What Occurs
Following logs are unrelevant, there's no indication about what item and/or category, site is being processed
```
[2015-08-28 14:20:31] sitebuilder.DEBUG: not creating media_filesize job {"reason":"item has no media","component":"items"} 
[2015-08-28 14:20:50] sitebuilder.DEBUG: not creating push_notification job {"reason":{"published":true,"push_enabled_in_category":null},"component":"items"}
```

# How to Reproduce
Check log file on PROD

**Comment by elbidone** [comment]
I think we should each time it's possible include on log message the site_id. It should allow us to filter by site_id when we investigate

**Comment by t4deu** [comment]
For test create items and check the log

**Comment by elbidone** [comment]
then, ok @t4deu *where is the analyze of issue and results of your tests ?* 
The issue concerns a global behavior, the examples provided on description of issue are not exhaustives. You have several examples of previous jobs highlighting the necessity to analyze an issue globally and not only fixing the example provided on ticket, see #173, #191.
So, the right thing to do is:
- check one day log on PROD to map log messages
- identify which log messages are irrelevant, how and where they are raised
- fix them and test

The results of tests is the trace of the correct message, on analyze you should previously identify how and where they are raised, not "For test create items and check the log".
I've began this job, copying on a Google Sheet logs I've found on PROD, feel free to complete the list
https://docs.google.com/a/meumobi.com/spreadsheets/d/1r4xtgbr2OYcF0Lg3OC_bbkxNk4x4hruU7skKjXNfNPo/edit?usp=sharing
![meumobi_logs_-_google_sheets_and_ios_certificates__development__-_apple_developer](https://cloud.githubusercontent.com/assets/9011612/9935849/7ea56328-5d2f-11e5-9006-ed7099f87dc6.png)

You can Observe a lot of inconsistencies, if you don't map these inconsistencies (to solve later) you can't extract rules to fix the current issue and *you'll increase inconsistency of the platform*.
Som bugs observed on list of log messages:
- should we log "not [DOING STG]" ? I could understand "no media available" and "push notification disabled" it concerns checks on code, but not [DOING STG] sounds strange.
- inconsistencies on job logs: "job_id" vs "job id", "job type" vs "type", etc.
- "item_id" vs "item id"
- "item id":"[object] (MongoId: {\"$id\":\"55fac1979a645da1638b45e4\"})" vs "item_id":"55fac1419a645da1638b45a5"
- "csv import finished" but none log when it starts, which component, reporting ? 
- "finished updating events from feeds" which reporting ?
