### ISSUE TITLE
Upgrade php mongoclient to prevent Fatal error

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#207]
Upgrade the mongoclient to prevent this error:
Fatal error: Call to undefined method MongoDate::toDateTime() in /home/meumobi/PROJECTS/int-meumobi.com/releases/20150831194503/sitebuilder/lib/meumobi/sitebuilder/repositories/VisitorsRepository.php on line 135

**Comment by t4deu** [comment]
The minimun version for the mongo client must be 1.6, the servers versions are:
INT: 1.5.6
PROD: 1.5.8
RIMOBI: 1.4.5

**Comment by t4deu** [comment]
Need three steps to upgrade the client, as described in the [client doc](https://github.com/mongodb/mongo-php-driver/releases):
```
 $ service apache2 stop
 $ pecl upgrade mongo 
 $ service apache2 start
```

**Comment by t4deu** [comment]
The client version now are:
```
INT: 1.6.11 
PROD: 1.6.11 
```

**Comment by juliogreff** [comment]
@t4deu has this been updated in RIMOBI yet?

**Comment by t4deu** [comment]
Yes, it was updated yesterday
