### ISSUE TITLE
When a site is removed, related photos, apple_touch_icon and splash_screen are not removed

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#219]
# What occurs
Site is removed. The site contain photos, apple_touch_icon and splash_screen. The image files were not removed.

# How to reproduce it
create new site, add visitors photos, apple_touch_icon and splash_screen, get files paths, remove site
check on uploads folder

**Comment by t4deu** [comment]
A delete observer method will be created for each image type, and a helper method "deleteImages" to avoid code duplication:
```php
  protected function deletePhotos($id)                                             
  {                                                                              
    $this->deleteImages('SitePhotos', $id);                                                
    return $id;                                                                  
  }  
  ...
  protected function deleteImages($type, $id)                                             
  {                                                                              
    $model = Model::load('Images');                                              
    $images = $model->allByRecord('SiteLogos', $id);                                
    $this->deleteSet($model, $images);                                           
                                                                                 
    return $id;                                                                  
  }
```

But we cold create a remove site service, to be responsible for all actions related to site removal, avoiding the use of observers and cleaning the sites model, like done with items and the CreateItem service.

**Comment by t4deu** [comment]
The remove service will be like:
```php

class RemoveSite
{
	public remove($site, $user)
	{
		//remove site only if user is admin and has more than one                                      
    if ($user->role == Users::ROLE_ADMIN 
    	&& count($user->sites()) < 1) return;
    
		$this->removeVisitors($site);
		$this->removeUsers($site);
		$this->removeCategories($site);
		$this->removeCustomSkin($site);
		$this->removeLogo($site);
		$this->removePhotos($site);
		$this->removeSplashScreens($site);
		$this->removeAppleTouchIcon($site);
		
		return $site->remove();
	}
	
	protected removeVisitors($site);
	
	protected removeUsers($site);
	
	protected removeCategories($site);
	
	protected removeCustomSkin($site);
	
	protected removeLogo($site);
	
	protected removePhotos($site);
	
	protected removeSplashScreens($site);
	
	protected removeAppleTouchIcon($site);
}
```

**Comment by elbidone** [comment]
Should alter names to use following naming rules:

Launch Image instead of Splash Screen
App Icon instead of Apple Touch Icon

Then call methods removeLaunchImage (instead of removeSplashScreens) and removeAppIcon (instead of removeAppleTouchIcon)

Why removeSplashScreens is plural ?

**Comment by t4deu** [comment]
The removeSplashScreens is plural  because the image type is in plural. To change that need to create a migration to rename the already saved images.

And I grouped the images removal in a single method "removeImages" to avoid code duplication.

**Comment by elbidone** [comment]
***... then why removeLogo is singular if type (SiteLogos) is plural ?***

@t4deu save our time checking if your response is consistent with your code.
