### ISSUE TITLE
PT Accents badly encoded on meumobi sitebuilder, tested on /visitors

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#223]
# What Occurs
I've open meumobi on INT and see accents badly encoded
https://www.evernote.com/l/APXVPN3Sov9FE5ZqEBGRqsaF1vFcnkX6LGcB/image.png
# How to Reproduce
Check on INT, int-meumobi.com (setup your /etc/hosts) and open /visitors page

**Comment by t4deu** [comment]
Can't reproduce on chrome  45.0.2454.85 (64-bit) and firefox 40.0.3. 
Please check if the browser encoding is set to Auto or to UTF-8.

**Comment by elbidone** [comment]
It's UTF-8, same encoding as used on when I open meumobi.com.
On same page the bug only appears on special chars of table of visitors, others special chars on page are well displayed. Then for sure the pb concerns the encoding of this file.

**Comment by t4deu** [comment]
I could not reproduce on Safari

But to fix the issue the accents in the translation quotes will be encoded to html entities.

And while looking at the files, I noticed that the code need some refactoring and also another bug, the 
quotes in the list of visitors don't change to english if the site language is set to english.

The refactoring, is that the translations quotes are in js, inside the ```assets/scripts/main.js```, they need to be moved to a translations file(config/locale/vendors.pt.yaml), this will keep the translation in one place and also fix the bugs.

**Comment by t4deu** [comment]
To fix the not english translated quotes and make the refactor:
1. move the translations from main.js to config/locale/vendors.pt.yaml, is not in the main file(pt.yaml) because they are translations of a plugin(dataTable), that can be replaced, and not related to the app.

2. Convert the translations, based on site language,  tokens to json and pass to the dataTable script, like done with visitors chart data.

**Comment by juliogreff** [comment]
@tadeuvalentt doesn't datatables have its own translation files that we could use, instead of creating all of it by ourselves?

**Comment by tadeuvalentt** [comment]
Yes, datatables have translation files, [as described here](https://www.datatables.net/plug-ins/i18n/), I'm gonna use then. 

But we need to translate the table according to the site settings or just set the table to a single language, no matter what the current site language?

To present the datatable based on site settings I can create a view helper to configure the databable language based on the settings.

**Comment by elbidone** [comment]
@tadeuvalentt what is your suggestion ?. The correct solution is to translate the table according to the site settings. @juliogreff ask you if translation is not a turn-key feature of databaseTable, if yes (seems to be the correct answer), then the response of your question seems YES, and it will clean our code removing useless code for own translation.

**Comment by tadeuvalentt** [comment]
# How to Test
1. Access /visitors page and check the list if visitors string tokens
1. Go to /users/edit, change user language
1. Access /visitors and check if the string tokens changed to the current language
