### ISSUE TITLE
On PROD item created site_id=69 follow "Sites with id=69 not found"

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#227]
# What Occurs
logs are inconsistent, look at this sequence
```
[2015-09-18 19:04:14] sitebuilder.ERROR: Category update timestamp error: Sites with id=69 not found  
[2015-09-18 19:04:14] sitebuilder.INFO: item created {"item_id":"55fc440e9a645d7f298b458a","site_id":6
9,"category_id":378,"downloaded_images":0,"failed_images":0,"component":"items"}
```

Sites (sic, plural ???) with id 69 is not found but item is created with site_id=69.
If site_id not exists it should not create the item, and why items are imported on a non existing site?

**Comment by t4deu** [comment]
To prevent an item from being persisted on a non existing site we need to update the ```ItemsPersistenceValidator::validSite``` to validate the site and check if it exists.

And to prevent to try import the item, we can update the UpdateFeedsWorker to check if the category site exists, if not, log, stop the import and disable the extension to prevent new imports.

The "Sites" in plural log, is the message of the RecordNotFoundException, The message is generated based on the model name:
```
app/models/app_model.php
28:   throw new \app\models\RecordNotFoundException("{$class} with id={$id} not found");
```
We can update the exception message to:
> "Record not found", {model: Sites, id: 69}

**Comment by elbidone** [comment]
@t4deu I don't find response to 
# How to reproduce

# Why it occurs

To define "How to fix it" we should answers both previous questions

**Comment by tadeuvalentt** [comment]
## Why it occurs

The error occurs when a category without site, tries to update the time stamps of the invalid site.
The concerned category belonged to a site that has been removed incorrectly, see #24.

And the item is created, even when the site not exists, because there is no check to see if the site really exists in the database.

## How to reproduce

* Create a site and category through the sitebuilder web interface.
* Enable an Rss Feed in the category.
* Thought command line, remove the site directly in the database.
* See the logs

**Comment by tadeuvalentt** [comment]
To test the : 
* Deploy the branch in the INT server
 * Created an Rss Feed category.
 * Set an invalid site for the category, directly in the database.
 * After the import, checked the log and if the extension was disabled in the database.

**Comment by elbidone** [comment]
"check the log", @tadeuvalentt check what ?
Please can you provide on ticket what is logged ?

**Comment by tadeuvalentt** [comment]
Checked the log message, for when an extension is disabled:
```
[2015-09-24 22:29:02] sitebuilder.INFO: category extension disabled {"extension_id":"5502da6bb5a508cc5c8b4567","category_id":46,"site_id":2,"reason":"Sites with id=33332 not found","component":"extensions"} 
```

**Comment by elbidone** [comment]
log message is not coherent with previous comment
> if the category site exists, if not, log, stop the import and disable the extension to prevent new imports

Then:
1. check if site exist => log if "Site not found", if site is found it's not relevant to log it
2. stop the import => log
3. disable extension => log

**Comment by t4deu** [comment]
The previous comment intention was just to describe the desired behavior, it has not based on the current import workflow.

In the actual import workflow, the category and the site is checked before the extension import start. If there is a problem getting the category, the current extension import not even start and the import of the others extensions continue.

So based in the current import implementation:

1. check if extension site exist => log if error
1. disable extension => log if error
1. not start current extension import => log to failed_extension *(Already done)*
1. continue to the next extensions import *(Already done)*

**Comment by tadeuvalentt** [comment]
The previous comment intention was just to describe the desired behavior, it has not based on the current import workflow.

In the actual import workflow, the category and the site is checked before the extension import start. If there is a problem getting the category, the current extension import not even start and the import of the others extensions continue.

So based in the current import implementation:

check if extension site exist => log if error
disable extension => log if error
not start current extension import => log to failed_extension (Already done)
continue to the next extensions import (Already done)

**Comment by elbidone** [comment]
@tadeuvalentt I understand that's the desired behavior it's why these logs should appears now, and they are not. So do it, all actions should be logged and not "if error"

**Comment by tadeuvalentt** [comment]
Done, the log is like this now:
```
[2015-09-29 15:58:01] sitebuilder.INFO: updating feeds {"priority":2,"component":"workers"} 
[2015-09-29 15:58:01] sitebuilder.INFO: site of extension not found {"extension_id":"56044eab95d45d5f528b4567","category_id":1,"site_id":1,"component":"extensions"} 
[2015-09-29 15:58:01] sitebuilder.INFO: extension disabled {"extension_id":"56044eab95d45d5f528b4567","category_id":1,"site_id":1,"reason":"site of extension not found","component":"extensions"} 
[2015-09-29 15:58:01] sitebuilder.INFO: finished updating feeds {"total_updated_feeds":0,"total_failed_feeds":1,"failed_feeds":[{"extension_id":"56044eab95d45d5f528b4567","category_id":1,"site_id":1,"error":"site of extension not found"}],"categories":[],"priority":2,"elapsed_time":0.033483028411865,"component":"workers"} 
```

**Comment by tadeuvalentt** [comment]
## How to test
1. Deploy the `fix/prevent-import-from-invalid-site` branck on INT.
1. Change the site id of a category with feed import directly in the database.
1. Wait for the import and check the logs for the "site of extension not found" and "extension disabled" messages.
1. Check on mongod if the extension has disabled.
