### ISSUE TITLE
Last login of visitors are wrong since rel-2.6.4 deploy

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#232]
### What Occurs
It seems that all records of last_login saved before deploy have been converted to a wrong date 1969-12-31 21:00:00
Take a look of screenshot below:
![visitantes___infobox](https://cloud.githubusercontent.com/assets/9011612/10022223/08420d66-6122-11e5-8621-25f093136ba3.png)

### How to reproduce
I've tested using infobox and comunique-se segments, sites resp. infobox.meumobi.com and dnadigital.meumobi.com

**Comment by t4deu** [comment]
The bug happened when the date string was converted to "Date" object type.
 if the string is converted "ISODate" instead, the bug not happens.

**Comment by elbidone** [comment]
I close it, we'll not use it anymore
