### ISSUE TITLE
Enable to remove domain on db

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#240]
## What Occurs
The site casaevideo on PROD (site_id=7) had 2 domains, casaevideo.meumobi.com and m.casaevideo.com.br.
I've removed the 1st one from config / domain on enterprise.meumobilesite.com. It disappeared from Site admin but db record remains

**Comment by elbidone** [comment]
I've added a custom domain of santanderen project on comunique-se.ipanemax.com env (old rimobi)
It unexpectedly removes santanderen.int-meumobilesite.com, see below:
https://www.evernote.com/l/APW6WUh1CGZFioWASfPu5g_ZlZFT6kTsbq8B/image.png
But if I call santanderen.int-meumobilesite.com it works, and if I try to recreate this domain it raises a warning message that the domain already exists

**Comment by juliogreff** [comment]
Cannot reproduce. Is this still happening?

**Comment by elbidone** [comment]
can't reproduce. I've tested same operations described above on PROD and seems to work fine
