### ISSUE TITLE
The number of items created is "suspicious"

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#244]
# What Occurs

The number of items created is huge, it seems "suspicious"
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/releases/20150922195136# cat log/sitebuilder.log| grep "item created"|**grep "2015-10-06"**|wc -l
**3200**
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/releases/20150922195136# cat log/sitebuilder.log| grep "item created"|grep "2015-10-05"|wc -l
4967
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/releases/20150922195136# cat log/sitebuilder.log| grep "item created"|grep "2015-10-04"|wc -l
3681

**Comment by juliogreff** [comment]
The code was behaving fine, but there was some faulty data that made all the newly created items to be dropped in certain circumstances (though not all, and I have no idea why). I emptied some categories that were having problems, and the problem went away.

It is still happening to the feed in http://www.rj.gov.br/web/guest/exibeconteudo/-/journal/rss/103138/NOTICIAS_IMPRENSA?doAsGroupId=103138&refererPlid=11702 -- but that's because it generates different GUIDs on every request. I'm thinking about disabling it. Since it's a completely separate issue, I'm considering this ticket closed.

**Comment by elbidone** [comment]
The description of this issue use logs of C-SE where rj.gov.br feeds not exists, and we continue observing these numbers. If you check details

```bash
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log| grep "item created"|grep "2016-03-20"|wc -l
5087
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log| grep "item created"|grep "2016-03-21"|wc -l
5002
```

A lot of these items created were due to deloitte site (site_id: 33) . I removed it, I didn't previously check if it generates different GUIDs.
But the issue remains, I've investigated which category are responsible for items created. It seems that it concerns category with high number of items.

Check following example:
http://ri.aeseletropaulo.com.br/FeedMeuMobi.aspx?idCanal=ubE2RNi5hI/jAIsSTbzwmw==
Each 15 min 3 items are created, at the end of day it was created more than 200 items, and if you check the feed content there's 1 or 2 new item per week.

```bash
# cat log/sitebuilder.log | grep "item created"| grep "2016-03-01" | grep "category_id\":328" | wc -l
288
```

**Comment by elbidone** [comment]
I'll test to delete all items of suspicious feeds to check if it solves the issue

**Comment by elbidone** [comment]
I've done same check previously reported on this ticket.

The number of created items decreased after deleted the site_id: 33, but remains at an high level
```bash
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log| grep "item created"|grep "2016-04-12"|wc -l
1254
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log| grep "item created"|grep "2016-04-11"|wc -l
1235
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log| grep "item created"|grep "2016-04-13"|wc -l
1038
```

I've deleted the RSS extension of category 328 to check if it continues to add items each 15 min as observed before, and it not. I've checked the logs during an hour, and no more items have been imported.
Then I search categories responsible for this amount of items created and repeat the process: delete extension and recreate it.

I've done it with the categories 86, 88 and 64:

```bash
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-12" | grep "category_id\":86" | wc -l
96
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-12" | grep "category_id\":88" | wc -l
95
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-12" | grep "category_id\":64" | wc -l
94
```
I'll check tomorrow if it's fine and reproduce to all others extensions to close this issue.

**Comment by elbidone** [comment]
It works, items are not created anymore after deleting extension an re-created it.
I've deleted site_id: 11, 39
and re-create items of categories 63 (site_id: 7), 465 and 467 (site_id: 60)

These extensions seems to be the highest issues. We can consider this issue closed

**Comment by elbidone** [comment]
Issue was solved on comunique-se ENV:

```bash
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-18" |wc -l
4
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" |wc -l
2
root@CSE-MOBI-CL:/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-20" |wc -l
1
```

But remains on elefante:

```bash
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-18" |wc -l
7545
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" |wc -l
7442
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-20" |wc -l
7419
```

**Comment by elbidone** [comment]
I've deleted sites 403, 190, 417, 415, 268 (see #364), 75, 86

I've removed news feed of sites 455
I've removed category 144 (import RSS of Gov RJ) from site 144

```bash
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" | grep "site_id\":144" | wc -l
822
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" | grep "category_id\":733" |wc -l
820
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" | grep "site_id\":190" | wc -l
1387
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" | grep "site_id\":403" | wc -l
202
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" | grep "site_id\":455" | wc -l
577
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" | grep "site_id\":417" | wc -l
2092
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" | grep "site_id\":415" | wc -l
469
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" | grep "site_id\":268" | wc -l
964
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" | grep "site_id\":75" | wc -l
213
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/current# cat log/sitebuilder.log | grep "item created"| grep "2016-04-19" | grep "site_id\":86" | wc -l
215
```
