### ISSUE TITLE
media url are badly encoded

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#264]
# What Occurs
media.url are not encoded, then when it contains empty space it raises crash of App if user try to share it.

# how to reproduce
When imported from RSS media:content@url are encoded on source RSS file, see feed below 
http://ri.embraer.com.br/FeedMeuMobi.aspx?idCanal=fa18f0R9kBesScFLU/kxqg==
You'll find the url "http://ri.embraer.com.br/Download.aspx?Arquivo=gKYG6/E+DHUw8u4L2w+fng=="
where empty space are encoded with "+" character
But if we call same [feed from meumobi api](http://int.meumobi.com/api/infobox.int-meumobi.com/categories/31/items?order=published,DESC&page=1) it returns the following property
"http:\/\/ri.embraer.com.br\/Download.aspx?Arquivo=gKYG6\/E DHUw8u4L2w fng==" where empty space are not encoded.

**Comment by elbidone** [comment]
Could be related to #264

**Comment by juliogreff** [comment]
Closed in 116ac8c
