### ISSUE TITLE
When I remove all items of a category media.thumbnails files are not removed

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#268]
# What Occurs

When I remove all items of a category media.thumbnails files are not removed
# How to Reproduce

Create a category, create item with application/pdf media.
Wait for Media Thumbnailer Service create its thumbnail and now click on "delete all items" of category

**Check if this issue also occurs when items are deleted indiviually**

**Comment by juliogreff** [comment]
Also happens when items are deleted individually.

I'm removing it from this milestone, there's no way we can get this done until tomorrow.
