### ISSUE TITLE
Huge Space disk used for mongodb

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#27]
Below the mongodb files allocated on rimobi ENV. It's higher than 6.5Go. It seems huge for less than 40 sites. 

/var/lib/mongodb/rimobi.6: 512M
/var/lib/mongodb/rimobi.0: 16M
/var/lib/mongodb/rimobi.7: 512M
/var/lib/mongodb/rimobi.13: 512M
/var/lib/mongodb/rimobi.4: 256M
/var/lib/mongodb/rimobi.15: 512M
/var/lib/mongodb/rimobi.10: 512M
/var/lib/mongodb/rimobi.16: 512M
/var/lib/mongodb/rimobi.8: 512M
/var/lib/mongodb/rimobi.3: 128M
/var/lib/mongodb/rimobi.11: 512M
/var/lib/mongodb/rimobi.9: 512M
/var/lib/mongodb/rimobi.1: 32M
/var/lib/mongodb/rimobi.14: 512M
/var/lib/mongodb/rimobi.5: 512M
/var/lib/mongodb/rimobi.12: 512M
/var/lib/mongodb/rimobi.ns: 16M
/var/lib/mongodb/rimobi.2: 64M

Julio's insights:
Here's what I found about this issue so far: http://docs.mongodb.org/manual/faq/storage/#why-are-the-files-in-my-data-directory-larger-than-the-data-in-my-database

I'll investigate further, but it seems our issue is fragmented data

**Comment by elbidone** [comment]
The PROD is full today, no space left on device. This issue is critical

**Comment by juliogreff** [comment]
The issue will be much alleviated in the next deploy, since the fix for #80 should behave better, not causing as much fragmentation. Meanwhile, I'll try to free up some space and run a repairDatabase as soon as I get home.

**Comment by juliogreff** [comment]
I logged in the production machine, and I noticed that the mongodb data is on the root partition (which is only 20GB), while we have more than 700GB available in /dev/sda2 (our home directory). Is there any way we can also mount /var in that partition? I cannot repair the database without at least 10GB free, so we cannot get rid of the fragmentation.

```
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS# df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs           20G   19G  239M  99% /
/dev/root        20G   19G  239M  99% /
tmpfs           199M  224K  198M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            10M     0   10M   0% /dev
tmpfs           499M     0  499M   0% /dev/shm
/dev/sda2       912G   97G  769G  12% /home
```

**Comment by juliogreff** [comment]
I have run a repairDatabase (after trying very hard to free up disk space). Now we have:

```
root@ks387594[ELEFANTE]:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs           20G  2.1G   17G  11% /
/dev/root        20G  2.1G   17G  11% /
tmpfs           199M  224K  198M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            10M     0   10M   0% /dev
tmpfs           499M     0  499M   0% /dev/shm
/dev/sda2       912G   97G  769G  12% /home
```

So it was indeed fragmentation. This issue can be closed, but we'll have to be more observant about how we use our database.
