### ISSUE TITLE
I've invited an user, but when he tried to register it raises an error

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#289]
I've invited m.nogueira@comunique-se.com.br on comunique-se segment.
He signup, but when he login it raises an error 500

![skype](https://cloud.githubusercontent.com/assets/9011612/12419302/5500e42e-be9c-11e5-825e-578b4045d900.png)

**Comment by juliogreff** [comment]
The error happens because the user has logged in, but he couldn't get invited to the site, and therefore has no site. This happens because the link sent to the invited user points to the wrong segment.

Check [app/views/users/invite_mail.htm.php](https://github.com/meumobi/sitebuilder/blob/master/sitebuilder/app/views/users/invite_mail.htm.php) for where the problem is.

**Comment by elbidone** [comment]
Should be fixed by #204

**Comment by elbidone** [comment]
# User Invite Request
![convidado_por_test_test_-_tadeu_valentt_meumobi_com_-_e-mail_de_meumobi_png_-_google_drive](https://cloud.githubusercontent.com/assets/9011612/13494759/04aa2bec-e125-11e5-96b0-461b4666d81f.png)

- Token: users/mail/invite_request:subject
- File Path: app/models/users.php
- Subject: s('[SEGMENT_NAME] %s Invited you to Join %s Content Managers', $user->fullname(), $site->title)
- Example: [infomobi] John Smith Invited you to Join Light Content Managers

**Comment by elbidone** [comment]
I've found the issue, someone [has introduced a domain property on Segment config on rel-2.6.5](https://github.com/meumobi/sitebuilder/commit/4af70a8c66e4c63ad709c2934cee3e144d244779). He has only changed the config of segment meumobi and not the others. It's why when we use this function on another segment it doesn't work.
But the implementation doesn't seem smart, look below what looks like a dumb code, that's the function responsible to retrieve the current domain.
This function is on `sitebuilder/app/models/meu_mobi.php`, code comments are mine.

```php
	public static function domain()
	{
		$segment = self::currentSegment();
// return Segments::current(); -> return new self((array) Config::read('Segment'));
		$domain = null;

		if ($segment->domain) {
			$domain = $segment->domain;
		}

		if (!$domain) {
			$domain = Config::read('Sites.domain');
		}
// /config/environments/integration.php, Config::write('Sites.domain', 'int.meumobi.com');

		if (!$domain) {
			$domain = self::instance();
		}

		return $domain;
	}
```

self:instance() seems to always work, I didn't investigate how. But if used on cli I think it will return null, so it's why this function MUST have a fallback, could be Config.read(Segment). Config.read(Segment) is not related to environment, so on INT links will lead to PROD, but I don't know how to manage it.
The use of Config::read("Sites.domain") seems a bug because on my understanding this value concerns the domain of created sites and not the domain of backend, so completely different purpose.

So I think the code should be refactored to follow:
If self::instance() $domain = self::instance()
else if Config.segment.domain
else log error "missing sitebuilder domain"

# Layout
The other issue concerns the layout. It raises following errors

```bash
[2016-03-03 17:57:43] sitebuilder.NOTICE: E_NOTICE: Undefined variable: site {"code":8,"message":"Undefined variable: site","file":"/home/meumobi/PROJECTS/int-meumobi.com/releases/20160228125550/sitebuilder/app/views/layouts/mail.htm.php","line":16}

[2016-03-03 17:56:35] sitebuilder.NOTICE: E_NOTICE: Undefined variable: title {"code":8,"message":"Undefined variable: title","file":"/home/meumobi/PROJECTS/int-meumobi.com/releases/20160228125550/sitebuilder/app/models/users.php","line":380}
```

The reason is the dumb implementation of  `/sitebuilder/app/models/users.php` that doesn't use or send correct variables. for instance $data not include $site object mandatory for mail layout.
sendEmail function use an undefined $title var  for mailer subject instead of $subject param

# content for layout

on users/invite_mail.htm we use following code
`<?= $this->html->link(s('Click to confirm invite'), "/accept_invite/login/$token", [], true) ?>`

That is redundant with ready-to-use link property sent by app/models/users.php to view
`$data['link'] = MeuMobi::url("/accept_invite/login/{$data['token']}", true);`
