### ISSUE TITLE
add android_custom_icon and android_header on Pushwoosh payload

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#290]
Android allow to set an icon an header on Push payload. By default the icon and header displayed on push are the App ones. We can change it to use the icon (android_custom_icon) and title (android_header) of site which user belongs to.
This feature, not available on iOS, is interesting for our demos and our DIY solution of Employee App.

![pushwoosh___applications___rimobi_embraer___send_push](https://cloud.githubusercontent.com/assets/9011612/12536863/a579c010-c298-11e5-9c2a-f755a8353af8.png)

Then the payload should like:
```json
{
	"request": {
		"application": "36D9B-4948F",
		"applicationsGroup": null,
		"auth": "z8slYDk24hm2SJDIhzi6SBcdFPjCMU870gEH4wJ9WbzcdJsC6RBVl72r7k12b99yoHxZ39VDoOPYNsoLLtRk",
		"notifications": [
			{
				"ignore_user_timezone": true,
				"send_date": "now",
				"content": "Teste yahoo",
				"devices": [
					"APA91bGQQLM1yuEomiduxQxWL-vjhP1znQqlu-Ux6H0z9MZwQKjLrtlpysZS4lEYnuOJ2oXNmF4Jth60gBNLxcCVt_GwDiP-ehxF_uiZLZJlJlvRgKTDwzYBeIV1OlbKJy2BGZAUPHRZ",
					"e6287b0d33308d2b7e7bc9f2afe45b8c9ddc848dc6fd2e783ffcfdd63760c99d"
				],
				"ios_badges": "+1",
				"data": {
					"custom": {
						"category_id": 40, // Please check the correct key format following meumobi rules
						"item_id": 390080 // Please check the correct key format
					}
				},
				"android_custom_icon": "", // Full path URL to the image file
				"android_banner": "", // Full path URL to the item.thumbnail file, =< 450px wide and 2-1 aspect
				"android_header": "" // HERE THE NAME OF SITE
			}
		],
		"component": "push_notification"
	}
}
```

**Comment by juliogreff** [comment]
@elbidone what "image file" do you mean on android_custom_icon? We have tons of them. Is it the site logo? Any specific size?

**Comment by elbidone** [comment]
we'll use the icon uploaded on /sites/application, remove field on payload if not exists
android_header should be the site.title
I've created a ticket #292 to update the /sites/application page to follow current resources and config needed to build App.
