### ISSUE TITLE
"Poll" item type

### ISSUE THREAD

**Issue by juliogreff** [meumobi/sitebuilder#304]

**Comment by elbidone** [comment]
# One-Question Survey
The model for our poll is twitter and its four-option poll:
- one question
- max of four options
- duration (or close date)

We'll add our meumobi native properties: 
- schedule publish
- photos
- target groups if site is private

It should be great if can merge a multiple-choice poll and star rating (5 stars). That means options are automatically created, no need to user inputs.

Below an example of poll model. Its important to save UUID of vote to prevent double vote.

```
// Subdocument schema for votes
var voteSchema = new mongoose.Schema({ userId: 'String' });

// Subdocument schema for poll choices
var choiceSchema = new mongoose.Schema({ 
	text: String,
	votes: [voteSchema]
});

// Document schema for polls
exports.PollSchema = new mongoose.Schema({
	question: { type: String, required: true },
	choices: [choiceSchema]
});
```
# Example of API response
```
{
site_id
category_id
"question": "", 
"type": "star-rating" // OR "multiple-choice",
"options": [],
"votes": {
  "total": 18 // value of total number of votes,
  "results": [10, 0, 3, 5] // details of votes for each options
},
"timeLeft": // which format ?? 0 if closed
"userVote": null // indicate the vote of user if saved, could be the index of [options]
}
```

**Comment by juliogreff** [comment]
# Fields

- **title**: string
- **end_date**: datetime
- **options**: array(string)
- **votes**: array(vote)
- **multiple_choice**: bool

**votes** is a hidden field and will always be hidden when editing the item through the CMS. Its **vote** data type is defined as follows:

- **user_id**: string
- **values**: array(any)
- **timestamp**: datetime

All other fields are available to all other item types (scheduled publishing, media, segmenting into groups).

# API Representation

```javascript
{
    // ...
    choices: ['a', 'b', 'c'],
    results: [
      { value: 'a', votes: 5 },
      { value: 'b', votes: 2 },
      { value: 'c', votes: 7 },
    ]
}
```

# Voting

Voting will be done through a new API endpoint: **POST /items/{item id}/poll**. It accepts the following values as parameters:

* **value[]**: the values to be voted on

It also requires the user to be authenticated (so X-Visitor-Token), returns the new item representation as a response, and is idempotent (multiple votes will have no effect).

**Note**: this ticket will not implement star rating nor likes. The spec is made forward-compatible though, so both of those can just be new field types ("rating" and "likes", for example). Voting will probably be implemented differently for all of them through different API endpoints.

**Comment by elbidone** [comment]
1. Seems redundant choices and results. Why not use only results ?
2. Need to provide the information if current visitor has voted or not. 
3. If has voted he could update its vote.

**Comment by juliogreff** [comment]
I updated my comment above with the current vote, and also how the "options" array looks like.

Regarding having both "options" and "results", that's necessary so that we can be forwards compatible with likes and star rating. I can't remove the "options" from the API response in a generic way, and I can't move the "results" into the "options" because that's something star rating and likes won't have.

**Comment by elbidone** [comment]
don't forget to update api doc

**Comment by elbidone** [comment]
## multiple-choice property missing
I don't see the property multiple-choice neither on dashboard nor api response.
What's the default behaviour ? multiple-choice or not. 

## I can't vote - "vote has not been provided"
I can't vote, the server always respond "vote has not been provided", even if it's the first time I vote.

```bash
$ curl -X POST http://int.meumobi.com/api/infomobi.int-meumobi.com/items/56d1f5d3b5a508890f8b4567/poll -H "X-Visitor-Token: 175ebfbf68f23abe7ebf32c6713171954be5cbf3" -d "values[0]=1"
{"errors":["vote has not been provided"]}
```

## Do API authorize to update vote ?

**Comment by juliogreff** [comment]
- Multiple choice has been added. It was an oversight on my part
- There had been an issue with lithium, in non-reproducible ways. I completely changed the voting persistence code. Also, you should be using "value" instead of "values".
- Updating the vote is not yet implemented. I'm working on that today. It's related to the bug that allows the user to vote more than once.
