### ISSUE TITLE
Media thumbs are not being created

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#312]
On C-SE env, I've deleted, 24h ago, all items of category 475 to refresh datas. Till now none media thumb has been created.

**Comment by juliogreff** [comment]
There was a problem with imagick/postscript/ghostscript:

```
[2016-02-24 12:45:07] sitebuilder.ERROR: caught exception {"message":"Postscript delegate failed `/tmp/magick-xOa3SO6F': No such file or directory @ error/pdf.c/ReadPDFImage/677","exception":"[
object] (ImagickException(code: 1): Postscript delegate failed `/tmp/magick-xOa3SO6F': No such file or directory @ error/pdf.c/ReadPDFImage/677 at /home/meumobi/PROJECTS/mobi.comunique-se.com.b
r/releases/20160203200413/sitebuilder/lib/meumobi/sitebuilder/services/PdfThumbnailer.php:29)","component":"remote_media"}
```

I believe this is because the pdf could not be served. So there is no bug, but we could deal with this more gracefully. I'll open a new ticket for a QoS milestone.

**Comment by elbidone** [comment]
Media thumbs disappear because I've deleted all items to update item's feed due to #311. If I re-delete items to force re-import it should resolve the issue, media thumbs missing ?
Before closing this ticket include the QoS issue reference to track the resolution.

**Comment by juliogreff** [comment]
It *can* solve the issue. It's possible that we drove too much traffic to the server and it stopped responding. I'd try it, anyway.

If that doesn't happen, you can run the thumbnails worker by hand. I can provide you with the command if necessary.

**Comment by elbidone** [comment]
I've re-deleted all items and I'm tracking on logs success of error of Media Thumb Worker as described on [Operating hand-book](https://github.com/meumobi/sitebuilder/wiki/Operating-hand-book)
At the moment (after 10 min), all items have been imported but none success (`# tail -f log/sitebuilder.log |grep "Media thumbnails"`) or error `# tail -f log/sitebuilder.log |grep "sitebuilder.ERROR"` related to thumbs have been raised

**Comment by juliogreff** [comment]
You should be grepping by the component "media_thumbnailer", not by the string, since that can change at any point.

Have the thumbnails shown up now?

**Comment by elbidone** [comment]
This issue seems to always occur after a thumb creation with processing time > 300sec

```
[2018-04-05 07:58:00] sitebuilder.INFO: "thumbnail created" {"item_id":"5ac5fd297017965f4d8b456b","medium_url":"https://www.rd.com.br/Download.aspx?Arquivo=YgFGUcDl3w8R18SsCwGdLA==","thumbnail_url":"http://mobi.comunique-se.com.br/uploads/pdf_thumbnail/bcb07829fe440f65628c69b5d9a83e27.png", "processing_time":366.8548541069,"component":"media_thumbnailer"}
[2018-04-05 07:58:01] sitebuilder.INFO: "remote media processed" {"item_id":"5ac5fd297017965f4d8b456b","successes":1,"failures":0,"skipped":0,"component":"remote_media"}
[2018-04-05 07:58:01] sitebuilder.INFO: "worker finished" {"job_id":"5ac5fd297017965f4d8b456c","job_type":"process_remote_media","job_params":{"item_id":"5ac5fd297017965f4d8b456b"},"component":"worker_manager"}
[2018-04-05 07:58:01] sitebuilder.INFO: "start executing worker" {"job_id":"5ac5fd297017965f4d8b456e","job_type":"process_remote_media","job_params":{"item_id":"5ac5fd297017965f4d8b456d"},"component":"worker_manager"}
[2018-04-05 07:58:01] sitebuilder.INFO: "processing remote media" {"item_id":"5ac5fd297017965f4d8b456d","component":"remote_media"}
[2018-04-05 07:58:01] sitebuilder.INFO: "requesting info for remote media" {"item_id":"5ac5fd297017965f4d8b456d","url":"https://www.rd.com.br/Download.aspx?Arquivo=esjl6fu/irHrASLsKP2E1g==","type":"application/pdf","component":"remote_media"}
[2018-04-05 07:58:02] sitebuilder.INFO: "remote media info downloaded" {"item_id":"5ac5fd297017965f4d8b456d","url":"https://www.rd.com.br/Download.aspx?Arquivo=esjl6fu/irHrASLsKP2E1g==","info":{"type":"application/pdf","extension":"pdf","length":200130},"processing_time":0.35630893707275,"component":"remote_media"}
[2018-04-05 07:58:02] sitebuilder.INFO: "creating medium thumbnail" {"item_id":"5ac5fd297017965f4d8b456d","component":"media_thumbnailer"}
[2018-04-05 07:58:02] sitebuilder.NOTICE: "thumbnail generation failed" {"item_id":"5ac5fd297017965f4d8b456d","medium_url":"https://www.rd.com.br/Download.aspx?Arquivo=esjl6fu/irHrASLsKP2E1g==","type":"application/pdf","message":"Postscript delegate failed `/tmp/magick-JV0tQv8S': No such file or directory @ error/pdf.c/ReadPDFImage/677","exception":"[object] (ImagickException(code: 1): Postscript delegate failed `/tmp/magick-JV0tQv8S': No such file or directory @ error/pdf.c/ReadPDFImage/677 at /home/meumobi/PROJECTS/mobi.comunique-se.com.br/releases/20180403131600/sitebuilder/lib/meumobi/sitebuilder/services/PdfThumbnailer.php:32)","processing_time":0.38608694076538,"component":"media_thumbnailer"}
```

**Comment by elbidone** [comment]
I've checked if high processing times observed on comment above are related to high length of files, but not, I observe 16M, 5M and 3M.

```
> db.items.find({"medias": {$elemMatch: {url: "https://www.rd.com.br/Download.aspx?Arquivo=YgFGUcDl3w8R18SsCwGdLA=="}}}, {"medias.length": 1})
{ "_id" : ObjectId("5ac5728a70179678038b4ce0"), "medias" : [ { "length" : NumberLong(16384541) } ] }
db.items.find({"medias": {$elemMatch: {url: "https://cielo.riweb.com.br/Download.aspx?Arquivo=OE2DWSAZBZmdJ2E6qjuJpQ=="}}}, {"medias.length": 1})
{ "_id" : ObjectId("5ac3876570179649558b51e8"), "medias" : [ { "length" : NumberLong(5423800) } ] }
db.items.find({"medias": {$elemMatch: {url: "https://cielo.riweb.com.br/Download.aspx?Arquivo=DpYuECxnJIHpdmTdDULPHA=="}}}, {"medias.length": 1})
{ "_id" : ObjectId("5ac3876670179649558b51f0"), "medias" : [ { "length" : NumberLong(3444827) } ] }
```

**Comment by elbidone** [comment]
The ImageMagick version:
```
# convert --version
Version: ImageMagick 6.7.7-10 2013-09-01 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

// GPL Ghostscript 9.05 (2012-02-08)
# /usr/bin/gs --version
9.05

// Check available version of a package in Debian repositories from command line
# apt-cache madison imagemagick
imagemagick | 8:6.7.7.10-5+deb7u21 | http://security.debian.org/ wheezy/updates/main amd64 Packages
imagemagick | 8:6.7.7.10-5+deb7u4 | http://ftp.debian.org/debian/ wheezy/main amd64 Packages
imagemagick | 8:6.7.7.10-5+deb7u3 | http://ftp.debian.org/debian/ wheezy/main Sources
imagemagick | 8:6.7.7.10-5+deb7u4 | http://ftp.debian.org/debian/ wheezy/main Sources
imagemagick | 8:6.7.7.10-5+deb7u21 | http://security.debian.org/ wheezy/updates/main Sources

# apt-cache madison php5-imagick
php5-imagick | 3.1.0~rc1-1+b2 | http://ftp.debian.org/debian/ wheezy/main amd64 Packages
php-imagick | 3.1.0~rc1-1 | http://ftp.debian.org/debian/ wheezy/main Sources

# aptitude -V -s install imagemagick
The following packages will be upgraded: 
  imagemagick [8:6.7.7.10-5+deb7u2 -> 8:6.7.7.10-5+deb7u21]  
1 packages upgraded, 0 newly installed, 0 to remove and 188 not upgraded.
Need to get 293 kB of archives. After unpacking 139 kB will be used.
Do you want to continue? [Y/n/?] y
Would download/install/remove packages.
#
```

I've upgraded required packages

```
$ aptitude install imagemagick php5-imagick imagemagick-common
```

**Comment by elbidone** [comment]
I've upgraded packages to check if it fix the issue, without success:

```
aptitude install ghostscript php5-imagick imagemagick imagemagick-common
```

**Comment by elbidone** [comment]
> ImageMagick reverts to using the Ghostscript program if the Ghostscript delegate library and its headers are not installed. The only difference between using the program rather than the library is just a few tens of a second in start-up time (starting a command line program is generally slower than making direct API calls to the library)

Source: [Convert PDF to JPG: 64-Bit Postscript delegate. Please h](https://www.imagemagick.org/discourse-server/viewtopic.php?t=19545#p76928)

**Comment by elbidone** [comment]
feature implemented on #172 

About [generated temp files are not deleted](https://www.imagemagick.org/discourse-server/viewtopic.php?t=15960#p57850)
> ImageMagick requires temporary files when caching pixels to disk or when creating intermediate files for delegate programs. All the temporary filenames begin with magick-. ImageMagick includes signal handlers so that it can clean-up any temporary files before it exits. The actual temporary file clean up method is magick/resource.c/AsynchronousResourceComponentTerminus. In some cases, ImageMagick is not given the opportunity to call its clean-up code to properly delete temporary files. In this case **you need to remove them manually**. You could run a job each night to delete magick-* from the temporary directory. A better solution might be to create a temporary folder for each call to ImageMagick and point ImageMagick to it (e.g MAGICK_TMPDIR=/data/magick/abacadaba). That way when the process is complete, simply remove that folder to ensure temporary files are removed without interfering with other ImageMagick processes.

The command run by meumobi could be translated as below on cli:
```
# time convert -verbose -layers flatten -fill white -alpha off  "https://ri.magazineluiza.com.br/Download.aspx?Arquivo=IASD4HSphSp352Tr0ncIqg==&[0]" foo.png
foo.png PNG 794x1123 794x1123+0+0 8-bit PseudoClass 5c 12.3KB 1.210u 0:01.000
0m5.725s
```

Could investigate how much should benefit add following options
- `-density 96x96`
- `-layers optimize-frame`
- `-layers optimize-transparency`

**Comment by elbidone** [comment]
|file|length|num. pages|processing time (sec.)|
|---|---|---|---|
|[file](http://www.ri.santander.com.br/download.aspx?Arquivo=H6v2M1QMToBEspIE5Ab8zQ==)|1M|121|118|
|[file](http://www.ri.santander.com.br/download.aspx?Arquivo=Z0tZQpNjlv1CemPHRxk7tQ==)|9M|496|362|
|[file](https://www.rd.com.br/Download.aspx?Arquivo=kAGeho+ch5xRFo+1NrilEw==)|1M|93|182|
|[file](https://www.rd.com.br/Download.aspx?Arquivo=dntMElwUmB+Ut6n257rwrw==)|6M|326|133|
|[file](https://www.rd.com.br/Download.aspx?Arquivo=0FFyBVPB9UeclK/eOjt4Ig==)|1M|175|103|
|[file](https://www.rd.com.br/Download.aspx?Arquivo=g1va4C+5cfmJ7zPl9zlMTQ==)|15M|556|465|
|[file](https://ri.magazineluiza.com.br/Download.aspx?Arquivo=r2idayGw0SpEyMEpvvBHWw==)|365K|1|5|
|[file](https://www.rd.com.br/Download.aspx?Arquivo=piCUV7s/q/X+ColZJfeqdA==)|147K|2|2|
|[file](https://www.rd.com.br/Download.aspx?Arquivo=5tSfk566DINnYFUJk8pPEQ==)|214K|1|5|
|[file](https://cielo.riweb.com.br/Download.aspx?Arquivo=YIkW9uByl7XnUqg5iARnzg==)|218K|3|2.5|

90% of files are processed in less than 35 sec.

**Comment by elbidone** [comment]
If I convert through cli a file file with 556 pages, it spend 19 sec. instead of 465 sec. when processed by php  imagemagick.

```
 time convert -verbose -layers flatten -fill white -alpha off "https://www.rd.com.br/Download.aspx?Arquivo=g1va4C+5cfmJ7zPl9zlMTQ==&[0]" foo.png
"curl" -s -k -o "/tmp/magick-3cFzcBV5" "https://www.rd.com.br/Download.aspx?Arquivo=g1va4C+5cfmJ7zPl9zlMTQ==&"
"gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -dFirstPage=1 -dLastPage=1 "-sOutputFile=/tmp/magick-Wz4Eeqmt-%08d" "-f/tmp/magick-a6tk5H99" "-f/tmp/magick-1dkUb2WQ"
/tmp/magick-Wz4Eeqmt-00000001 PNG 612x792 612x792+0+0 8-bit DirectClass 125KB 0.050u 0:00.050
https://www.rd.com.br/Download.aspx?Arquivo=g1va4C+5cfmJ7zPl9zlMTQ==&[0]=>//www.rd.com.br/Download.aspx?Arquivo=g1va4C+5cfmJ7zPl9zlMTQ==& PNG 612x792 612x792+0+0 16-bit DirectClass 125KB 0.000u 0:00.009
https://www.rd.com.br/Download.aspx?Arquivo=g1va4C+5cfmJ7zPl9zlMTQ==&[0]=>foo.png PNG 612x792 612x792+0+0 8-bit DirectClass 102KB 0.320u 0:00.230

real	0m19.798s
user	0m7.940s
sys	0m0.308s
```

If I download the pdf and run php imagemagick through local file path, instead remote Uri it fix issue.
It means that using a remote pdf and setIteratorIndex seems to convert all pages of doc and return only the first while using a local file suffixed by `[0]` only convert the first page.

```
# time php image.php "foo.pdf[0]" png
foo.pdf[0]
real    0m5.308s
user    0m3.512s
sys     0m0.108s
```

**Comment by elbidone** [comment]
i recommend a PR to https://github.com/spatie/pdf-to-image to:

- if remote media pdf, download before convert
- FIX if necessary [set background white if layermethod_flatten image](https://github.com/spatie/pdf-to-image/commit/dca165ecdd76cdc9c2a726c3da8c575b3ca13eea)

**Comment by danconte72** [comment]
There is a problem with Pdf-To-Image
On constructor the file is read (in the slow way): ```$this->imagick = new Imagick($pdfFile);```

```php
/**
     * @param string $pdfFile The path or url to the pdffile.
     *
     * @throws \Spatie\PdfToImage\Exceptions\PdfDoesNotExist
     */
    public function __construct($pdfFile)
    {
        if (! filter_var($pdfFile, FILTER_VALIDATE_URL) && ! file_exists($pdfFile)) {
            throw new PdfDoesNotExist();
        }

        $this->imagick = new Imagick($pdfFile);

        $this->numberOfPages = $this->imagick->getNumberImages();

        $this->pdfFile = $pdfFile;
    }
```
This is just did to get number of pages;

On getImageData the imagick is reinitialized 

```php
 public function getImageData($pathToImage)
    {
        /*
         * Reinitialize imagick because the target resolution must be set
         * before reading the actual image.
         */
        $this->imagick = new Imagick();

        $this->imagick->setResolution($this->resolution, $this->resolution);

        if ($this->colorspace !== null) {
            $this->imagick->setColorspace($this->colorspace);
        }

        if ($this->compressionQuality !== null) {
            $this->imagick->setCompressionQuality($this->compressionQuality);
        }

        if (filter_var($this->pdfFile, FILTER_VALIDATE_URL)) {
            $this->pdfFile = $this->getRemoteFile($pathToImage);
            $this->tempFile = true;
        }

        $this->imagick->readImage(sprintf('%s[%s]', $this->pdfFile, $this->page - 1));

        if (is_int($this->layerMethod)) {
            $this->imagick = $this->imagick->mergeImageLayers($this->layerMethod);
        }

        $this->imagick->setFormat($this->determineOutputFormat($pathToImage));

        if ($this->tempFile) {
            $this->deleteTempFile();
        }

        return $this->imagick;
    }
```

The main problem is the file is read two times, solution.
Move this lines from getImageData to constructor:
```php
    public function __construct($pdfFile)
    {
        if (! filter_var($pdfFile, FILTER_VALIDATE_URL) && ! file_exists($pdfFile)) {
            throw new PdfDoesNotExist();
        }       
        $this->pdfFile = $pdfFile;
        if (filter_var($this->pdfFile, FILTER_VALIDATE_URL)) {
            $this->pdfFile = $this->getRemoteFile("/tmp/");
            $this->tempFile = true;
        } 
        $this->imagick = new Imagick($this->pdfFile);
        $this->numberOfPages = $this->imagick->getNumberImages();
    }
```
But to to this we need the pathToImage, or set default temp dir.
What to do?

**Comment by elbidone** [comment]
could fetchRemoteFile on construct and set a variable $isRemoteFile. then pdfFile will always be a local path. If $isRemotefile remove $pdfFile after downloaded on [$pdfFile->clear](http://php.net/manual/en/imagick.clear.php).
On construct check if $pdfFile already setted and $isRemoteFile, if true delete file and unset $isRemoteFile.

**Comment by elbidone** [comment]
Use [sys_get_temp_dir](http://php.net/manual/en/function.sys-get-temp-dir.php) to get directory path used for temporary files
```
// Create a temporary file in the temporary 
// files directory using sys_get_temp_dir()
$pdfFile = tempnam(sys_get_temp_dir(), 'pdf-to-image');

// Example of return /tmp/pdf-to-image64XD8J
```
