### ISSUE TITLE
allow to create new visitors with [auto or default] password 

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#32]
When a new visitor is created admin could choose if it site-builder should generate a password (auto) or set a default password (site.slug)

It allows "flash campaign" of subscription without mailing, visitor only need to flash qrcode and use default password (no need to check mail)

**Comment by t4deu** [comment]
In order to prevent code duplication and avoid to add an operation that isn't related to the Visitor entity.

I'm gonna create the service CreateVisitorService. It will be responsible the visitor creation, and to check when to use a default password or generate a new one.

The methods Visitor::setRandonPassword  will be removed, and the Visitors::setPassword will accept a new parameter to set the "should_renew_password"

...

**Comment by elbidone** [comment]
should_renew_password is a consequence not a param. It depends on type of password {custom=setted by user, random= generated by site-builder, default= site.slug}.

If password.type is custom then should_renew_password = false
else should_renew_password=false

**Comment by juliogreff** [comment]
I don't like having a "password type". A password is just a password, the knowledge about the consequence come from the service either way. I'd rather have the setPassword get a shouldRenewPassword param (and I could see it being used when an admin sets a password manually and wants the user to renew immediately, for example), or then having the service set it on the visitor from the outsite (via $visitor->setShouldRenewPassword or something like that).

**Comment by elbidone** [comment]
but where|how to call auto or manual password ? Please explain the
algorithm to allow to use auto or default password

2015-03-30 5:30 GMT-03:00 Julio Greff <notifications@github.com>:

> I don't like having a "password type". A password is just a password, the
> knowledge about the consequence come from the service either way. I'd
> rather have the setPassword get a shouldRenewPassword param (and I could
> see it being used when an admin sets a password manually and wants the user
> to renew immediately, for example), or then having the service set it on
> the visitor from the outsite (via $visitor->setShouldRenewPassword or
> something like that).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meumobi/sitebuilder/issues/32#issuecomment-87590555>.
>



-- 
Dias Victor

victor.dias@meumobi.com
skype : victor.dias.meumobi

Brésil : +55 21 98348 7230
France : +33 (0)970 406 968

FAX : +33 4 26 99 94 89

**Comment by juliogreff** [comment]
The service caller should do that. See code below. There's three options:

* User-supplied password. The visitor sets its own password, and should_renew_password = false
* Admin-supplied password. The site admin chooses a default password when creating new visitors. Just using the site slug instead is a very bad idea. In this case, should_renew_password = true
* Auto-generated password. We generate a random password, should_renew_password = true

```
$service = new CreateVisitorService();
$service->call([
    'email' => '...',
    // ... any other visitor information
    
    // if it's an user-supplied password:
    'password' => '123456',

    // if it's an admin-supplied password:
    'password' => 'meumobi',
    'default_password' => true,

    // if it's an auto-generated password:
    'default_password' => true,
]);
```

**Comment by elbidone** [comment]
we should use a predefined auto-password. It should not be setted by admin
or user.
The default password should be used to allow admin to communicate App
download without need of personalized mail. For example a generic folder
with download link and mention "use your own mail and password=meumobi".
We should not provide this task (choose a default password when creating
new visitors) to admin to prevent mispelling and redundant actions.
Slug is an option because it's specific to each site.


2015-03-30 11:43 GMT-03:00 Julio Greff <notifications@github.com>:

> The service caller should do that. See code below. There's three options:
>
>    - User-supplied password. The visitor sets its own password, and
>    should_renew_password = false
>    - Admin-supplied password. The site admin chooses a default password
>    when creating new visitors. Just using the site slug instead is a very bad
>    idea. In this case, should_renew_password = true
>    - Auto-generated password. We generate a random password,
>    should_renew_password = true
>
> $service = new CreateVisitorService();
> $service->call([
>     'email' => '...',
>     // ... any other visitor information
>
>     // if it's an user-supplied password:
>     'password' => '123456',
>
>     // if it's an admin-supplied password:
>     'password' => 'meumobi',
>     'default_password' => true,
>
>     // if it's an auto-generated password:
>     'default_password' => true,
> ]);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meumobi/sitebuilder/issues/32#issuecomment-87706315>.
>



-- 
Dias Victor

victor.dias@meumobi.com
skype : victor.dias.meumobi

Brésil : +55 21 98348 7230
France : +33 (0)970 406 968

FAX : +33 4 26 99 94 89

**Comment by juliogreff** [comment]
In this case, we can use a strategy pattern:

```
$service->call([
    // ... visitor information

    // if it's an user-supplied password:
    'password' => '123456',

    // otherwise:
    'password_strategy' => 'random',
    // or:
    'password_strategy' => 'default',
]);
```

Then, inside the the service, we can do a simple switch (to avoid the overhead of actually creating entire classes)

**Comment by t4deu** [comment]
The service will be named like, this:
```php
class VisitorCreationService {
   public function create()
}
```
Because most of services samples that I found are named like this, on a indicative, not inperative way, and had specific methods:
```
HashingService->hash()
CargoInspectionService->inspectCargo()
BookingService->bookNewCargo()
```
Even in the Eric Evans book, we can find the:
```
RoutingService->find()
```
Sources:
sample DDD aplication: http://sourceforge.net/projects/dddsample/
http://culttt.com/2014/09/29/creating-domain-services/
http://www.infoq.com/articles/ddd-in-practice

**Comment by t4deu** [comment]
A doubt, the default password applies only when creating a visitor. What about when updating or renewing a visitor password?

**Comment by elbidone** [comment]
Please can you provide more details about the strategy, I can't understand
what the issues behind this update.
The framework could provide all options, and we decide which one to use and
easily change it. Or could not because of architecture constraint and then
recommend one, for any reason.

2015-04-02 10:42 GMT-03:00 t4deu <notifications@github.com>:

> A doubt, the default password applies only when creating a visitor. What
> about when updating or renewing a visitor password?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meumobi/sitebuilder/issues/32#issuecomment-88905174>.
>



-- 
Dias Victor

victor.dias@meumobi.com
skype : victor.dias.meumobi

Brésil : +55 21 98348 7230
France : +33 (0)970 406 968

FAX : +33 4 26 99 94 89

**Comment by t4deu** [comment]
The Service will generate the visitor password, this simplifies the use of default password on every cases(create, update, renew password).

The service name is VisitorPasswordGenerationService.

About the strategy pattern, it is used only to choose the correct password type(manual, default, random) inside the service. And is not related with the previous doubt
