### ISSUE TITLE
FIX congrats mail to user after accept invitation

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#323]
Related to #204 

# User Invite Confirm
![invite_confirmed_-_tadeu_valentt_meumobi_com_-_e-mail_de_meumobi_png_-_google_drive](https://cloud.githubusercontent.com/assets/9011612/13494771/217170a0-e125-11e5-876e-cb95951ba648.png)

- Token: users/mail/invite_confirm:subject
- File Path: app/models/users.php
- View: users/invite_confirmed_mail.htm
- Subject: s('[SEGMENT_NAME] %s has joined %s Content Managers', $user->fullname(), $site->title)	
- Example: [infomobi] Victor Dias has joined Light Content Managers

**Comment by juliogreff** [comment]
The fix for this email is too expensive for the value it brings (which, in my opinion, is zero), so instead of fixing I'm removing the email.
