### ISSUE TITLE
Bad site domain used on PROD

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#329]
I've created a site "newcomm" and meumobi raised `http://newcomm.comunique-se.meumobilesite.com` url instead of `http://newcomm.meumobi.com`

**Comment by juliogreff** [comment]
Should it be .meubmobi.com even for the comunique-se environment?

**Comment by elbidone** [comment]
no, on comunique-se ENV it's `*.mobi.comunique-se.com.br` It's like vhost is configured
