### ISSUE TITLE
The size of logs/sitebuilder.log is 2.1Go on PROD

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#334]
It's impossible to correctly use a such bug file, why it's not rotate log ?

**Comment by elbidone** [comment]
when I try to use a grep, it raises "grep: log/sitebuilder.log: Input/output error"

**Comment by juliogreff** [comment]
logrotate is running, but there seems to be something wrong with the config, it does not thing the file needs rotation.

```
root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com/shared/log# logrotate -d /etc/logrotate.d/sitebuilder
reading config file /etc/logrotate.d/sitebuilder

Handling 1 logs

rotating pattern: /home/meumobi/PROJECTS/meumobi.com/shared/log/*.log  weekly (12 rotations)
empty log files are not rotated, old logs are removed
switching euid to 1004 and egid to 1000
considering log /home/meumobi/PROJECTS/meumobi.com/shared/log/php.log
  log does not need rotating
considering log /home/meumobi/PROJECTS/meumobi.com/shared/log/sitebuilder.log
  log does not need rotating
considering log /home/meumobi/PROJECTS/meumobi.com/shared/log/whenever.log
  log does not need rotating
not running prerotate script, since no logs will be rotated
not running postrotate script, since no logs were rotated
not running prerotate script, since no logs will be rotated
not running postrotate script, since no logs were rotated
not running prerotate script, since no logs will be rotated
not running postrotate script, since no logs were rotated
switching euid to 0 and egid to 0
```

**Comment by elbidone** [comment]
on C-SE env it reaches 3.5 Go
/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current# ls -ahl log/sitebuilder.log
-rwxrwxrwx 1 meumobi meumobi 3.5G Apr  1 12:19 log/sitebuilder.log

**Comment by juliogreff** [comment]
I had to delete all logs on C-SE because the logs were too big for gzip to process. Also, the logrotate config there was wrong. I fixed it.

Same happened to production. Also fixed.

I'm letting this run for another week to make sure everything keeps working. Then I'll close the ticket.

**Comment by juliogreff** [comment]
I just checked, and the logs seem to be working fine. I'll also fix this on INT.
