### ISSUE TITLE
bad spelling on confirm pt message when delete a category

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#35]
"Você realmente quer remover todos a categoria cat to test Push?"

https://www.evernote.com/shard/s245/sh/2ba8a624-76d5-4d6a-aee8-d28bbac7abca/987ca9ca3086fe8dc461a846ef468622/deep/0/Index---MeuMobi-and-New-Issue---meumobi-sitebuilder-and-Skype.png

**Comment by t4deu** [comment]
The fixed quote will be:
Você realmente quer remover a categoria {CATEGORY NAME}?
