### ISSUE TITLE
Inconsistency on polls result values format

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#351]
meumobi API returns voted.values with two different format `"values": [1],` and  `"values": {"1": 1},`

You can check following request
`$ curl -X GET http://meumobi.com/api/visa.meumobi.com/items/search?type=polls -H "X-Visitor-Token: 1d960c6a231beed6c0c3cdfe20d21593e14d6613"`

where exists `"values": [1],`

```json
"voted": {
    "user_id": "5672e3349a645d456df2ac3b",
    "values": [
        1
    ],
    "timestamp": 1459951537
},
```

and  `"values": {"1": 1},`

```json
"voted": {
    "user_id": "5672e3349a645d456df2ac3b",
    "values": {
        "1": 1
    },
    "timestamp": 1459960303
},
```

**Comment by elbidone** [comment]
@juliogreff remember to fix api documentation replacing `-d "values[2]=1"` on curl command with `-d "value[2]=1"` and providing an example of response

**Comment by juliogreff** [comment]
PHP simply refuses to serialize [ 0 => 1 ] as { "0": "1" }, no matter what I try. It works with [ 1 => 1 ], but it never does with the first option in the poll.

To solve this, I added a dummy value to the vote. It will now show up as { "_": 0, "0": 1 }. That dummy value should be ignored.
