### ISSUE TITLE
Use secure https for meumobi api and dashboard

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#354]
tell me If backward compatibility has a cost, to plan a migration of front-end.

**Comment by elbidone** [comment]
https://letsencrypt.org/

**Comment by elbidone** [comment]
CloudFare https

Segment Home: mobi.comunique-se.com.br
Segment Home: residence.meumobi.com
Segment Home: employee.meumobi.com
Segment Home: meumobi.com

We should do a full non Regression Tests Campaign

**Comment by elbidone** [comment]
# Going further
- [Keep-Alive and HTTPS
](http://brianflove.com/2014/12/04/keep-alive-and-https/)

**Comment by danielindiano** [comment]
I've created a cloudfare account and setup a configuration for meumobi.com domain. The next step is change the CNAME's for the one's listed below:

- brett.ns.cloudflare.com
- dora.ns.cloudflare.com

![screenshot from 2017-02-24 17-40-53](https://cloud.githubusercontent.com/assets/553232/23320609/3e67dca8-faba-11e6-853b-5b7196b8581a.png)

**Comment by danconte72** [comment]
[Open SSL](https://www.youtube.com/watch?v=zwnEmLx2LRs)

**Comment by elbidone** [comment]
missing on c-se and int (setup vhost with domain ns325644.ip-37-187-106.eu)

**Comment by elbidone** [comment]
Need to update
- ns325644.ip-37-187-106.eu
Already up
- mobi.comunique-se.com.br
- meumobi.com
- https:employee.meumobilesite.com
- https:comunique-se.meumobilesite.com
