### ISSUE TITLE
Images from feed are not imported as expected

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#388]
On elefante I've applied the fix of #381  on `sitebuilder/lib/meumobi/sitebuilder/services/UpdateNewsFeed.php`, and ran an importation with following feed: [onboard Feed](http://mobi.comunique-se.com.br/static/meu-feeds/siemens/blog.xml)
The image of the latest article is not processed, only file size is computed.
`<enclosure url="http://mobi.comunique-se.com.br/static/meu-feeds/onboard/6932685.jpg" length="51141" type="image/jpeg"/>`
All images of others articles are almost correctly processed: items.thumbnails and items.images are created, but medias.thumbnails NOT.

**Comment by elbidone** [comment]
If you change the image on feed from 
`<enclosure url="http://mobi.comunique-se.com.br/static/meu-feeds/onboard/6932685.jpg" length="51141" type="image/jpeg" />`
to
`<enclosure url="https://blogs.siemens.com/static/sibs/sites/conexaosiemens/media/geracao-distribuida-energia-sustentavel.fullscreen.jpg" length="51141" type="image/jpeg" />`
the img is processed.
It works.

I've tested the same feed on C-SE environment and the image from mobi.comunique-se.com.br is correctly processed.

the main issue is that there's no logs to understand what went wrong ,I've opened an issue about that #387

**Comment by juliogreff** [comment]
I tested this on INT, and it all seems to work, the image gets downloaded correctly (see curl request below for a category with this feed). I'll close this, and if we see the issue persists in PROD we can reopen.

```
curl http://int.meumobi.com/api/greff.int-meumobi.com/categories/84/items | python -m json.tool
```

Regarding the missing thumbnails for media, a commit with a fix is incoming. They're not supposed to be media items, and that's why we get no thumbnails. They're supposed to be only images.

**Comment by elbidone** [comment]
This issue remains on PROD. I've checked the logs and see following msg:

```bash
"message":"destination file already exists","exception":"[object] (Exception(code: 0): destination file already exists at /home/meumobi/PROJECTS/meumobi.com/releases/20160726195931/sitebuilder/lib/utils/FileDownload.php:22)"
```

you can reproduce it with following feed:
http://meumobi.com/static/meu-feeds/siemens/blog.xml
That includes the enclosure:
```xml
<enclosure url="http://mobi.comunique-se.com.br/static/meu-feeds/onboard/6932685.jpg" length="51141" type="image/jpeg" />
```
