### ISSUE TITLE
Some bbcode tags isn't being parsed and are returned by the API

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#39]
The item.description is parserd by Decoda on the Items::toJSON method but nothing changes.
It may be caused by a Decoda misconfiguration.
I coud not see the or revert to commits before date 17/12/2014 to verify this

**Comment by t4deu** [comment]
Here a example:
http://int-meumobi.com/api/santander.int-meumobi.com/items/551ace62b5a508685a8b4567
```json
{
   "description": "<p>test <strong>bb</strong> [small]code[/small]</p>"
}
```

**Comment by elbidone** [comment]
decoda doesn't filter small tag, check here list of decoded tags:
https://github.com/milesj/decoda
You can remove it from white-list and test that remains tags works fine
