### ISSUE TITLE
I've renew a password but should_renew_password remains false

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#4]
I've renew from action 
http://int-meumobi.com/visitors/reset/5488cba7b5a508fd5e8b4569

> db.visitors.find({email:'fabio.g.cardoso@gmail.com'})
{ "_id" : ObjectId("5488cba7b5a508fd5e8b4569"), "email" : "fabio.g.cardoso@gmail.com", "first_name" : "Fabio", "last_name" : "Cardoso", "site_id" : NumberLong(6), "hashed_password" : "5add5769fdd812d465535508c44ce978f44dffcb", "auth_token" : "864e066043c3e39a9dcbab3e93071443ffcb9988", "last_login" : null, "should_renew_password" : false, "devices" : [ ], "groups" : [ "meumobi" ] }

**Comment by t4deu** [comment]
Hi everyone,

This is probably because the "shouldRenewPassword" flag isn't being updated when the visitor random password is generated, in the Visitors::setRandomPassword() method.

Adding

    $this->shouldRenewPassword = true;

to the method shoud fix.

**Comment by juliogreff** [comment]
I'd call setPassword($password) instead. You can go ahead with that one.

**Comment by t4deu** [comment]
Both methods already exists.

But the setPassword($password) is the one that set shouldRenewPassword to false. Its called when the visitor provides the password

**Comment by juliogreff** [comment]
Oh yes, I'm sorry. Go ahead then :)
