### ISSUE TITLE
If I set a legend on item.image the corresponding item is removed from API response

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#40]
I've tested following request:
http://int-meumobi.com/api/infobox.int-meumobi.com/categories/31/items
with X-Visitor-Token: b43954d10f7e80e39fc6978e02ecf1155a668df1, see below:

```sh
curl http://int-meumobi.com/api/infobox.int-meumobi.com/categories/31/items -H "X-Visitor-Token: b43954d10f7e80e39fc6978e02ecf1155a668df1"
```

It returns 6 items. But if I add a legend on image of item._id:"551191d4b5a5089e078b4567" corresponding item is not returned by API

**Comment by t4deu** [comment]
Couldn't reproduce, tested locally and in the specified item, both are returned by the api after add a image label.

Tested add, edit and removing an image and legend

**Comment by elbidone** [comment]
I couldn't reproduce this morning. Let this issue under observation

**Comment by juliogreff** [comment]
It's been a month since this happened last, so I'm closing. Reopen if it still happens.
