### ISSUE TITLE
Add new preview engine

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#412]

**Comment by elbidone** [comment]
# Requirements
The purpose of this issue is to serve requests on *.meumobi.com or custom domains. 

- All sites have a list of available domains and a unique theme. 
- Each theme corresponds to a SPA (single Page Application).
- SPA could be reached on root or directly to an internal page (deep-linking)

Because of Deep-link I reocmmend using PROXY to the SPA, passing params on url.

# vhost apps.meumobi.com
catch *.meumobi.com and redirect to /home/meumobi/PROJECTS/apps/current/public

# public/index.php
```php
<?php
$domain = $_SERVER['HTTP_HOST'];
$url = "http://meumobi.com/api/" . $domain;
$remote = curl_init($url);
curl_setopt($remote, CURLOPT_HEADER, 0);
curl_setopt($remote, CURLOPT_RETURNTRANSFER, true);
$data = curl_exec($remote);
curl_close($remote);

$obj = json_decode($data);
//echo $obj->theme;
// PROXY http://0.0.0.0:8001/$params where 0.0.0.0:8001 is the address of theme, could be replaced by a vhost, ie infomobi.meumobi.com
?>
```
For performance improvements we should consider the use of a local cache used by index.php to save api requests. This cache could be erased/updated by Http call of meumobi if a site change its theme.

# Static Assets
Assets should be served by Apache
Each App (THEME) should have a directory on public/ and should prefix all assets by `themes/<THEME>/` then configure Apache to serve any request as *.meumobi.com/themes

**Comment by juliogreff** [comment]
I'd recommend against the proxy idea, for several reasons. We'd need to do too much set up for dubious gain.

Since it's a JS app, it's very easy to do deep linking. You can read the URL params via JS (with document.location). That might take some parsing, but via proxying you would probably need it anyway (since it's a SPA).

It's as easy as having something like [mod_xsendfile](https://tn123.org/mod_xsendfile/) enabled in Apache, and sending the right headers. Apache will read and return the file without the need to bother with it via PHP. This way, there's no need to bind themes to anything, it's all in the filesystem.

**Comment by elbidone** [comment]
To simplify, we'll discard cache on 1st version

**Comment by elbidone** [comment]
# Install Debian package [libapache2-mod-xsendfile](https://packages.debian.org/wheezy/libapache2-mod-xsendfile)

```
$ apt-get update
$ aptitude install libapache2-mod-xsendfile
$ a2enmod xsendfile
```

Then you can send an X-SendFile header, which is processed by Apache.
Also note that when doing this, you should also send a Content-Type header at the very least.

# Update Directory Directive

Update VHost `/etc/apache2/sites-available/meumobi.com`, all domains *.meumobi.com.

```
...
  DocumentRoot /home/meumobi/PROJECTS/apps
  <Directory /home/meumobi/PROJECTS/apps/>
    XSendFile on
    XSendFilePath /home/meumobi/PROJECTS/apps
    Options -Indexes FollowSymLinks MultiViews
    AllowOverride All
  </Directory>
...
```

# Add .htaccess
Use [Rewrite Rules](http://httpd.apache.org/docs/current/mod/mod_rewrite.html) to redirect all requests to `/apps/index.php` which check theme of domain to send correct file

```
RewriteEngine On

RewriteRule ^.*$ index.php [NC,L]
```

# Check theme from domain and sendFile

```php
<?php

$domain = $_SERVER['HTTP_HOST'];
$url = "http://meumobi.com/api/" . $domain;
$remote = curl_init($url);
curl_setopt($remote, CURLOPT_HEADER, 0);
curl_setopt($remote, CURLOPT_RETURNTRANSFER, true);
$data = curl_exec($remote);
curl_close($remote);

$obj = json_decode($data);
$theme = $obj->theme; #"employee";
$path = $_SERVER['REDIRECT_URL'];
$ext = pathinfo($path, PATHINFO_EXTENSION);

switch ($ext) {
  case 'css':
    $type = 'text/css';
    break;
  case "js":
    $type = 'application/javascript';
    break;
  case 'ico':
    $type = 'image/vnd.microsoft.icon';
    break;
  case 'jpeg':
  case 'jpg':
    $type = 'image/jpeg';
    break;
  default:
    $type = 'text/html';
}
header("Content-type: $type");
header("X-Sendfile: /home/meumobi/PROJECTS/apps/$theme$path");
```

# TODO
## Live update skin 
meumobi/infomobi#251

`<iframe id="theme-frame" src="http://meumobi.meumobi.com?skin=57d8d93f9a645d9e354a7b7d&amp;1484161589374" data-url="http://meumobi.meumobi.com" data-autoload="1"></iframe>`

## Serve static files with Apache
Static files are served through sendFile, it increase the load time because for each request index.php call the api to retrieve theme of domain and check extension to set correct content-type.
We should find a way to serve static files w/ Apache.
