### ISSUE TITLE
ImportVisitorsCsv Service load wrong segment

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#427]
I've tested to import visitors from csv, using site id 6 from segment "meumobi".
But visitors received a mail with translations from  segment "infobox".

And the logo displayed on email is broken `http://infobox.meumobilesite.com/uploads/site_logos/200x200_4507.png` instead of `http://int.meumobi.com/uploads/site_logos/200x200_4507.png`

**If I create visitor from dashboard everything works fine** (transaltion and logo)

**Comment by elbidone** [comment]
Mail layout uses `<img src="<?= MeuMobi::url($logo, true) ?>` for logo
and `ImportVisitorsService.php` uses `$segment = MeuMobi::currentSegment();` on `function sendVisitorEmail`.
So I suppose this class MeuMobi (sitebuilder/app/models/meu_mobi.php) doesn't retrieve correct segment when called from cli.

**Comment by elbidone** [comment]
find in attach the csv I've used with following cli:
`php sitebuilder/script/import_visitors.php --exclusive --site 6 --import-file katrium-visitors-test.csv --password-strategy random`

**Comment by juliogreff** [comment]
I spent a good while looking at this, and from the code there's no way this is wrong. I decided to check the database:

```
mysql> select segment from sites where id = 6;
+---------+
| segment |
+---------+
| infobox |
+---------+
1 row in set (0.00 sec)
```

I think all is alright with the script. Are you sure you created the site on the right segment?

**Comment by elbidone** [comment]
Should not reproduce, seems to occured on INT due to a bad configuration or wrong datas
