### ISSUE TITLE
Remove push_id of subscribers on notification, send to all subscribers

### ISSUE THREAD

**Issue by danielindiano** [meumobi/sitebuilder#459]
When the service SendPushNotification calls getDevicesTokens method, it is bringing the pushId's, but for call the OneSignal api, it needs the playerId's instead.

**Comment by elbidone** [comment]
Regarding #298 we'll not need to use push_id or player_id. meumobi could on this release send push to all subscribers of App. On Next version we'll implement #298 to segment audience.
Then I'll rewrite ticket title to "remove push_id of subscribers on notification, send to all subscribers"

**Comment by danielindiano** [comment]
Ok. I'll keep that in mind when developing the related issues.
