### ISSUE TITLE
Allow to Sites uses both providers for Push Notification

### ISSUE THREAD

**Issue by danielindiano** [meumobi/sitebuilder#461]
- Save appId for pushwoosh;
 - Save appId/authToken for OneSignal;
 - Alter the SendPushNotification service to use both other Services;
 - Alter the controller and views for sites settings;

**Comment by danielindiano** [comment]
The appId for pushwoosh may be saved in a temporary structure considering that we will migrate to use only OneSignal service. (Keep this in mind).

In the Service, it must check if has the OneSignal configuration from site and call the Api, then check if Pushwoosh is set in the chosen structure and call the pushwoosh service as well;

The views and controller for sites must be modified to allow the sites keep both configurations set. Also keeping in mind that in the future we'll have only onesignal config;

**Comment by elbidone** [comment]
No need to update views and controller for sites, only admin use sites/settings, and you can advice them.

**Comment by danielindiano** [comment]
Ok
