### ISSUE TITLE
Dump database schema

### ISSUE THREAD

**Issue by juliogreff** [meumobi/sitebuilder#49]
I'm trying to set up a new instance, but I'm having trouble running all migrations from the start. We need a schema dump to set this up more easily.

Dump the database schema to sitebuilder/db/schema.sql

**Comment by t4deu** [comment]
Create a schema.sql was already tried before and din't work well.
The database dump already exists on the migration db/20130101000000_create_db.sql.

The trouble that happened to you was probably related to the issue #12 but not been fixed yet

**Comment by juliogreff** [comment]
The issue that happened to me is way way earlier than that.

About the thing being tried before, what were the problems? A db dump from 2013 doesn't really help, it has to be current.

**Comment by t4deu** [comment]
Din't worked because it need to manually migrate the database, and we often forget that, and we had to look for where the problem came when migrating, costing an unnecessary time.

But I added now the current schema to sitebuilder/db/schema.sql

**Comment by t4deu** [comment]
You also may need some sample skins to be able to create a site through the dashboard

**Comment by juliogreff** [comment]
I'd also dump the contents of the schema_migrations table, so we don't try to run all the migrations again.
