### ISSUE TITLE
I've setted a category as not visible but on its items continue to appears on items/latest response 

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#51]
I've tested on INT, site infobox and category 40.

The request to retrieve items is:

```sh
$ curl http://int-meumobi.com/api/infobox.int-meumobi.com/items/latest -H "X-Visitor-Token: d337e966361bcfdad40e48b9d645640d993e7835"
```

**Comment by juliogreff** [comment]
I'll push a commit with the fix later today (it's still in progress), but fixing it would make the news items not appear on this endpoint anymore, since they're a hidden category. Is that a problem that we need to fix later on or is it okay?

**Comment by elbidone** [comment]
No pb, it could make sense to not share news of business with content

**Comment by elbidone** [comment]
@juliogreff  did you push the commit ? Close this issue if done
