### ISSUE TITLE
Allow to Upload Media in a external storage like S3 on CreateItem 

### ISSUE THREAD

**Issue by danconte72** [meumobi/sitebuilder#536]

**Comment by elbidone** [comment]
- Migrate images/media to AWS S3 (5Go free + US$4/100Go)
  - Should allow to upload media and free up space on server to upgrade our server to SSD architecture to increase performances
  - [FlySystem](https://github.com/thephpleague/flysystem): Abstraction for local and remote filesystems
- [FileStack](https://www.filestack.com/): Files uploading API
