### ISSUE TITLE
Remove unnecessary images from uploads folder

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#565]
Remove unnecessary images that have no more items

Steps
- Loop through images and make a copy of each one image file in a backup shared/uploads.new
  - images of items on images table in the mysql database
  - (images of items on items entries in mongo)
- Archive uploads folder, rename it (be careful it's symlink)
  - uploads -> /home/meumobi/PROJECTS/meumobi.com/shared/uploads
  - mv shared/uploads  shared/uploads.old
- recover the backup images in a new uploads folder
  - mv shared/uploads.new shared/uploads
- regenerate the thumbnails
  - for images items
  - for media

**Comment by elbidone** [comment]
update `/sitebuilder/script/images/clean.php`
`isValidItem` should check if item exists on db (mongo) if not remove it.
Check also `/sitebuilder/script/remove_sites.php` to get more recent/efficient methods to achieve it

**Comment by elbidone** [comment]
images include items, pdf_thumbnails, site_apple_touch_icon, site_logos, site_photos

- site_photos: ex. `/uploads/site_photos/139x139_934635.jpg`
- site_logos: ex. `/uploads/site_logos/200x200_1216078.png`
- android_custom_icon: ex. `/uploads/skins/5ab156562ce3c3ddafc578d6/android_custom_icon.png`
- site_apple_touch_icon: ex. `/uploads/site_apple_touch_icon/6947572.png`
- pdf_thumbnails: ex.
- items: ex.

**Comment by danconte72** [comment]
Origin | DB | Model | Dir | Thumbnails
-- | -- | -- | -- | --
SitePhotos | MySql | Sites | site_photos | regenerate
SiteLogos | MySql | Sites | site_logos | regenerate
SiteAppleTouchIcon | MySql | Sites | site_apple_touch_icon | regenerate
SiteSplashScreens | MySql | Sites | site_splash_screens | n/a
Items - UI | Mongo | Items | items | regenerate
Items - Remote | - | - | - | process remote media
Skins | Mongo | Skins | skins | n/a

**Comment by danconte72** [comment]
- Copy All content from uploads folder  to a backup folder; (backupContent --type=)
- Copy Necessary content to a temp folder; (copyNecessary --type=[])
      Necessary are images vinculated with a model;
- Delete uploads content; (deleteContent --type=)
- Move temp content to uploads folder; (recoverContent --type=) 
- Regenerate Thumbnails from updated uploads folder; (regenerateThumbnails --type=)

**Comment by danconte72** [comment]
### How to use:
```bash
$ php script/images/cleanContent.php --action=[] --type=[]
```
**Action** [copy, thumbnail, backup, clean, recover , process]
**Type**: [sites_images, items_images, items_medias]

### How it works:
- **copy** - copy all valid images from upload/[dir] to a new folder;
- **backup** - move uploads/[dir] folder all content to a backup folder;
- **clean** - remove uploads/[dir] content;
- **recover** - move from valid folder to uploads/[dir];
- **thumbnail** - call specific methods to regenerate thumbnails;
- **process** - execute all methods in this order: copy, backup, clean, recover, thumbnail;
  - during the process some thumbnails can be unavailable (originals are reachable) , the alternative is rewrite the following methods because them need to point to another folder:
    - Images->regenerate
    - Item->processRemoteMedia

**Comment by danconte72** [comment]
In order to work updating symlinks 
The following changes need to be make

Item->processRemoteMedia must to update medium-url to temp folder
```php
public function createThumbnail($medium)
	{
		if ($medium['type'] == 'application/pdf') {
			$thumbnail = PdfThumbnailer::perform([
				'url' => $medium['url'],
				'extension' => 'png'
			]);

			return $thumbnail;
		} else {
			throw new Exception(sprintf('file type "%s" not supported', $medium['type']));
		}
	}
```

Images->regenerate must to add a param
```php
public function regenerate($model)
	{
		$fileInfo = pathinfo($this->path);
		$path = $fileInfo['dirname'];
		$filename = $fileInfo['basename'];
		$this->resizeImage($model, $path, $filename);
	}

```

**Comment by danconte72** [comment]
The script regenerate items_images on prod got killed after ~10 minutes;
Probably because a overload of server resources
```bash
$ php script/images/cleanContent.php --action=thumbnail --type=items_images
```

**Comment by danconte72** [comment]
Process remote media failing on int 
```bash
[2018-03-28 19:32:07] sitebuilder.NOTICE: "thumbnail generation failed" {"item_id":"5abbce57b5a508cb01fb498f","medium_url":"https://firebasestorage.googleapis.com/v0/b/meumobi-sitebuilder.appspot.com/o/files%2F493efafb-6acd-d72d-392a-6fab172cecbf.pdf?alt=media&token=dbcebeba-6bbf-41d5-a2fa-36017ce1255b","type":"application/pdf","message":"WriteBlob Failed `/home/meumobi/PROJECTS/int-meumobi.com/releases/20180322180031/uploads/pdf_thumbnail/db413e06ac3c43892e9c06605ab642e8.png' @ error/png.c/MagickPNGErrorHandler/1728","exception":"[object] (ImagickException(code: 1): WriteBlob Failed `/home/meumobi/PROJECTS/int-meumobi.com/releases/20180322180031/uploads/pdf_thumbnail/db413e06ac3c43892e9c06605ab642e8.png' @ error/png.c/MagickPNGErrorHandler/1728 at /home/meumobi/PROJECTS/int-meumobi.com/releases/20180322180031/sitebuilder/lib/meumobi/sitebuilder/services/PdfThumbnailer.php:57)","processing_time":4.237645149231,"component":"media_thumbnailer"}
```
