### ISSUE TITLE
email reader ignore item, no trace on logs

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#571]
I've sent twice an email "É na Globo hj - 3" to `post+V28VZ4iPn2FClmCfTAEMHA==@meumobi.com` (ELEFANTE account, site 543 category 7390) but none item was created and its fetch never appears on logs

```
[2018-03-20 22:32:03] sitebuilder.DEBUG: "server connected" {"server":"{imap.gmail.com:993/imap
/ssl}INBOX","user":"post@meumobi.com","password":"MeuMobi123!","component":"email_reader"}
[2018-03-20 22:32:03] sitebuilder.INFO: "fetching email" {"emails_count":0,"component":"import_
content_email"}
[2018-03-20 22:32:03] sitebuilder.DEBUG: "server disconnected" {"component":"email_reader"}
[2018-03-20 22:32:03] sitebuilder.INFO: "job event created" {"worker":"ImportEmailWorker","star
t":"2018-03-20 22:32:02","end":"2018-03-20 22:32:03","params":[],"success":true,"updatedExistin
g":true,"n":1,"connectionId":23982,"err":null,"ok":1,"component":"job_event"}
[2018-03-20 22:32:03] sitebuilder.INFO: "script finished" {"script_id":"ImportEmail-5ab17dd2a5b
9c","component":"cli"}
```

*what is the 'job event created' if none email is fetched ?*

**Comment by elbidone** [comment]
I've re-tested after stopping cron of it and it works. If it was the pb of previous try should be considered as an issue at least of config.

**Comment by danconte72** [comment]
**what is the 'job event created' if none email is fetched ?**
I was looking in the code, probably this is unnecessary

**Comment by danconte72** [comment]
To keep same email account on different environments there are some steps:
- Only set email as read when email options are compatible with the environment;
- If options are wrong set as read;
- If are not options set as read;

The main problem is, each server will be read the same e-mail. 
We can fetch emails by criteria param on [imap_search](http://php.net/manual/pt_BR/function.imap-search.php), today we fetch UNSEEN

**Comment by elbidone** [comment]
The main problem is, each server will read the same e-mail.
It's not important to solve it, we can manage like that.

BUT **how to set config to test when required** ?

**Comment by danconte72** [comment]
Ways to test config:
1. Set different email account for the server you are testing. Just updating the following env vars
```
EMAIL_USERNAME=post@meumobi.com
EMAIL_HOSTNAME={imap.gmail.com:993/imap/ssl}INBOX
EMAIL_SERVER=meumobi.com
EMAIL_PASSWORD=***********
EMAIL_ACCOUNT=post
```  

2. Disable cron (not recommended).

There is no switch option to able/disable get emails.
