### ISSUE TITLE
I've created a new visitor through dashbord but should_renew_password is unexpectedly false

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#6]
I've created the following visitor and before login its field "should_renew_password" value is set to false instead of true

> db.visitors.find({email:'elbidone@gmail.com'})
{ "_id" : ObjectId("55107f4eb5a50854788b4569"), "email" : "elbidone@gmail.com", "first_name" : "Victor", "last_name" : "Dias", "site_id" : NumberLong(6), "hashed_password" : "a96c602d287c5ac006942ea5314d61988822d06a", "auth_token" : "689766d3406e669b4a1de7d7d605a3b0d563bc62", "last_login" : null, "should_renew_password" : false, "devices" : [ ], "groups" : [ ] }

**Comment by juliogreff** [comment]
This seems to have been fixed by something else, so I'm closing the issue.
