### ISSUE TITLE
Update log parser agent

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#602]
What you'll need to do is set your new API key, and change the URL for the scalyr server to https://eu.scalyr.com 

Here's what you need to do on each server.

Write Logs API Key: "0dGpONJdgOxNQ8mhzmRMheuTwcfuznx3FscLK8bOaJdo-"

`/usr/sbin/scalyr-agent-2-config  --set-api-key "your_write_logs_api_key" --set-scalyr-server "upload.eu.scalyr.com"`

No need to restart the agent.

And of course, you'll need to apply these changes to however you deploy/provision servers/instances.

**Comment by danconte72** [comment]
```bash
/usr/sbin/scalyr-agent-2-config --set-key "0dGpONJdgOxNQ8mhzmRMheuTwcfuznx3FscLK8bOaJdo-" --set-scalyr-server "https://eu.scalyr.com"
```

**Comment by danconte72** [comment]
- migrate parsers from eua to europe account;

**Comment by danconte72** [comment]
Log parser was updated on august
