### ISSUE TITLE
Create databases backups in the deploy

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#61]

**Comment by t4deu** [comment]
Create a backup database script at sitebuilder/scripts/backup_database.php, it will be executed by the capistrano deploy.

Because the database connections settings are available only for php(config/connections.php) and it will follow the convention of the scripts "clean_db", "create_db", "check_database" that already exists.

The backup files generated by the script will saved at sitebuilder/db/backups/

This can also be applied to the issue #50 or make it unnecessary.

OBS. Rename the existing scripts to follow a convention, eg. clean_db => clean_database

**Comment by juliogreff** [comment]
Be sure to symlink db/backups into shared, the same manner with do with the logs. Otherwise we'll be eating disk spaces without even seeing it.

**Comment by t4deu** [comment]
I'm thinking of leaving a backup per release, eg:

releases/31321312/db/backups/mysql_backup.sql
releases/31321312/db/backups/mongodb_backup/

So when an old release is automatically removed by a deploy, the backup files for that release are removed too. the current limit for releases is 5
