### ISSUE TITLE
logrotate not working on ELEFANTE

### ISSUE THREAD

**Issue by vdias38** [meumobi/sitebuilder#611]
### Expected behaviour
Tell us what should happen

### Actual behaviour
see [commit](https://github.com/meumobi/sitebuilder/commit/d582a5e7dd5bce2560989ea583145759d4e93ac8) for details

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
sitebuilder.log stop to rotate
last instance was sitebuilder.log-20180107

**Comment by vdias38** [comment]
@danconte72 check on vps-2 if logrotate works, if true we can discard this issue because we'll migrate

**Comment by danconte72** [comment]
there were not a logrotate file set for sitebuilder on vps2
`$ cat /etc/logrotate.d/sitebuilder`

Should check hot logrotate [works](https://www.networkworld.com/article/3218728/how-log-rotation-works-with-logrotate.html)

**Comment by danconte72** [comment]
- cat /etc/logrotate.conf  is equal on vps2 elefante and cse
- cat /etc/cron.daily/logrotate  is equal too

**Comment by danconte72** [comment]
how to test logrotate 
as root
`$ logrotate --force /etc/logrotate.d/sitebuilder`

/etc/logrotate.d/sitebuilder mod must to be 644 or 444

`$ chmod 644 /etc/logrotate.d/sitebuilder`


it worked on vps2
```bash
meumobi@vps673381:~$ ls -al PROJECTS/meumobi.com/current/log/
total 100348
drwxrwsrwx 2 meumobi meumobi     4096 Apr 22 19:31 .
drwxrwsr-x 7 meumobi meumobi     4096 Apr 12 18:02 ..
-rw-rw-rw- 1 meumobi meumobi    14409 Apr 22 19:34 sitebuilder.log
-rw-rw-rw- 1 meumobi meumobi 78090892 Apr 22 19:31 sitebuilder.log-20190422
-rw-rw-rw- 1 meumobi meumobi     5088 Apr 22 19:34 whenever.log
-rw-rw-r-- 1 meumobi meumobi 24522666 Apr 22 19:31 whenever.log-20190422
```

**Comment by danconte72** [comment]
it's working on vps
