### ISSUE TITLE
protocol is missing on thumb urls when source of thumb is an image

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#617]
### Expected behaviour
Tell us what should happen

### Actual behaviour
On [cat 617](https://mobi.comunique-se.com.br/api/biosevpt.mobi.comunique-se.com.br/categories/617/items?limit=15&order=published,DESC&page=1) protocol is missing on thumb urls

```
"thumbnails": [
{
"width": "80",
"height": "60",
"url": "//mobi.comunique-se.com.br/uploads/items/80x60_1266030.jpg"
},
```

But on [cat 503](https://mobi.comunique-se.com.br/api/biosevpt.mobi.comunique-se.com.br/categories/503/items?limit=15&order=published,DESC&page=1) for example, it's ok. The difference is on cat 617 all thumbs are extracted from images, but on cat 503, all are extracted from pdf.

```
thumbnails": [
{
"url": "http://mobi.comunique-se.com.br/uploads/pdf_thumbnail/078a56816c029e3f914c5732a6f8dc42.png",
"type": "image/png",
"width": 1920,
"height": 1080
},
```

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by elbidone** [comment]
Not happens on ELEFANTE

```
thumbnails": [
{
"width": "80",
"height": "60",
"url": "https://meumobi.com/uploads/items/80x60_6981762.jpg"
},
```

Seems to occur a bad deploy/update on c-se env, check https://github.com/meumobi/IRmobi/issues/308

**Comment by elbidone** [comment]
Seems to be a deploy issue, check https://github.com/meumobi/IRmobi/issues/308

**Comment by danconte72** [comment]
There ir a lot of items with items.thumbnails using http protocol:
```js
$ db.items.find({"medias.thumbnails.url":{$regex : "http://.*"}}).count()
``` 

- it.c-se  - 1897;
- c-se - 10936;
- elefante - 10; 

Should update to https in order to avoid duplicated calls to server on each redirect

**Comment by elbidone** [comment]
this issue re-appear, see meumobi/ion-employee/issues/235 for more details

**Comment by danconte72** [comment]
To check if there is item.thumbnails without protocol 
`$ db.items.find({"thumbnails.url":{$regex : "//.*"}}).count()`

**Comment by danconte72** [comment]
check how item.thumbnail works

**Comment by danconte72** [comment]
both items created by ui or feed has no protocol on thumb.url

**Comment by danconte72** [comment]
Even when item.images.url has protocol, thumbs hasn't 
![image](https://user-images.githubusercontent.com/32454870/51834701-3e055180-22e2-11e9-9da9-bd40fe05b61a.png)

**Comment by danconte72** [comment]
on mongo thumbnails has no protocol 
```
	{
		"_id" : ObjectId("5c4ef69cb5a508f646a7efb7"),
		"author" : "",
		"created" : ISODate("2019-01-28T12:33:31.972Z"),
		"description" : "",
		"groups" : [ ],
		"guid" : "",
		"is_published" : true,
		"link" : "",
		"medias" : [ ],
		"modified" : ISODate("2019-01-28T12:33:32.181Z"),
		"notification_id" : "",
		"order" : NumberLong(2),
		"parent_id" : NumberLong(121),
		"published" : ISODate("2019-01-28T12:33:00Z"),
		"site_id" : NumberLong(23),
		"thumbnails" : [
			{
				"width" : "80",
				"height" : "60",
				"url" : "//int.meumobi.com/uploads/items/80x60_192036.jpg"
			},
			{
				"width" : "80",
				"height" : "80",
				"url" : "//int.meumobi.com/uploads/items/80x80_192036.jpg"
			},
			{
				"width" : "139",
				"height" : "139",
				"url" : "//int.meumobi.com/uploads/items/139x139_192036.jpg"
			},
			{
				"width" : "314",
				"height" : "220",
				"url" : "//int.meumobi.com/uploads/items/314x220_192036.jpg"
			},
			{
				"width" : "1200",
				"height" : "800",
				"url" : "//int.meumobi.com/uploads/items/1200x800_192036.jpg"
			}
		],
		"title" : "teste",
		"type" : "articles"
	}
```

**Comment by danconte72** [comment]
the origin 
https://github.com/meumobi/sitebuilder/commit/e4f0b80bb245913bd7782139b2ad0c191beb4476#diff-61a8de917ded29951064fce96090a6eb 

It was done do handle http and https requests

**Comment by danconte72** [comment]
- [ ] should modify to add https on url
- [ ] perform a mongo script to add https protocol on urls 
- [ ] update on prod and int env

**Comment by danconte72** [comment]
I've updated and tested on int
![image](https://user-images.githubusercontent.com/32454870/51838816-96425080-22ee-11e9-9d66-c8e51e1c1265.png)

**Comment by danconte72** [comment]
SCRIPT 
```
db.items.find({"thumbnails.url":{$regex : "//.*"}}).forEach(function(e,i) {
    e.thumbnails = e.thumbnails.map(function(thumb,i) {
      thumb.url = thumb.url.replace("//","https://");
      return thumb;
    });
    db.items.save(e);
});
```

**Comment by danconte72** [comment]
script performed on prod
