### ISSUE TITLE
Add apache2 access.log on scalyr => handle log rotation

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#621]
How could we handle logs import on scalyr when the log file name is dynamic, as access.log of apache

**Comment by danconte72** [comment]
I sent an email to scalyr support.

**Comment by danconte72** [comment]
Please use the following document link and find the section "rename logfile as json object"

https://www.scalyr.com/help/scalyr-agent#rename_logfile-as-json-object

What you need to do is to define something similar to the following in your agent.json
```js
{
    rename_logfile: {
        match: "/var/log/access.(\d{4}-\d{2}-\d{2})",
        replacement: "/scalyr/access.log"
    }
}
```
This uploads all of the access logs with the matched pattern to Scalyr as "/scalyr/access.log"
Let us know if you have more questions on this.

**Comment by danconte72** [comment]
the rename can work, but it will rename all log files and not just de current date log

**Comment by danconte72** [comment]
```js
{
    rename_logfile: {
        match: "/var/log/access.(\d{4}-\d{2}-\d{2})",
        replacement: "/scalyr/access\\0.log"
    }
}
```

**Comment by danconte72** [comment]
file to edit
```/etc/scalyr-agent-2/agent.json```

**Comment by danconte72** [comment]
I've add on [ELEFANTE] agent.json 
```js
{
  path: "/home/meumobi/teste/access.log",
  rename_logfile: {
    match: "/var/log/apache2/meumobi.com/access.([0-9]{4}-[0-9]{2}-[0-9]{2})",
    replacement: "/home/meumobi/teste/access.log"
  }
}
```
Restarted the server and I couldn't get any scalyr data on scalyr console

**Comment by danconte72** [comment]
I sent a new email explaining our situation, because rename logs didn't work if we follow de docs.

> Joel Mora (Scalyr)
> Jan 8, 17:59 PST
> 
> Hey Daniel,
> 
> Thanks for reaching out. I am looking into your question now regarding the agent now. I'll update you here as I have more information. 
> 
> Regards, 
> 
> Joel Christopher Mora 
> Technical Support Engineer 
> Scalyr, Inc.

**Comment by danconte72** [comment]
Todo 
- [ ] enable log apache log rotation on c-se
- [ ] enable log apache log rotation on it.cs-se
- [ ] update agent.json on c-se
- [ ] update agent.json on it.c-se

**Comment by danconte72** [comment]
The it.c-se setup will be realized on #628
