### ISSUE TITLE
There was a problem delivering your message to ...

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#623]
### Expected behaviour
Tell us what should happen

### Actual behaviour
The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 [mail.estacio.br. 200.216.152.82: timed out]

### Steps to reproduce
observed on email inbox

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
I've double checked email address and IR contact from estacio is ri[at]estacio[dot]br and not ri[at]estacio[dot]com[dot]br 

I'v update docs, and dashboard contact to the correct.
Also I sent a contact through the app and the error it not happens
