### ISSUE TITLE
missing scalyr monitoring of sitebuilder logs on itau

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#624]
### Expected behaviour
Should monitor log/sitebuilder.log

### Actual behaviour
None sitebuilder log for itau server.

![overview___scalyr](https://user-images.githubusercontent.com/9011612/50255235-01902d00-03e9-11e9-8dd0-b3b8dc805fba.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
add log on scalyr config

**Comment by danconte72** [comment]
- check if scalyr is misconfigured;
- config log correctly;
- probably on latest release deploy broke previous config, because config was set for ```/home/meumobi/PROJECTS/mobi.comunique-se.com.br/current/log/sitebuilder.log``` and now log file where on ```/home/meumobi/PROJECTS/itau.mobi.comunique-se.com.br/current/log/sitebuilder.log```

**Comment by danconte72** [comment]
```bash
$ nano /etc/scalyr-agent-2/agent.json
$ sudo scalyr-agent-2 restart
```
I've updated agent.json and log started to be tracked
