### ISSUE TITLE
remote media info download failed on itau env

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#626]
### Expected behaviour
Contact support for fix with details of error (feed url and XML extract of error)

### Actual behaviour
```
Wed Dec 19, 2018 10:03:07 PM CSE-MOBI-CL [36m[2018-12-19 20:03:03] sitebuilder.NOTICE: "remote media info download failed" {"item_id":"5b991a4670179651078b4587","url":"https://www.itau.com.br/Download.aspx?Arquivo=RaPTgbe3ejriLA5eXr4cTA==","error":"http status 404","processing_time":0.50131893157959,"component":"remote_media"} [0m
Wed Dec 19, 2018 10:03:07 PM CSE-MOBI-CL [36m[2018-12-19 20:03:03] sitebuilder.NOTICE: "remote media info download failed" {"item_id":"5b991a4670179651078b4587","url":"https://www.itau.com.br/Download.aspx?Arquivo=6VElZ2JSOU7leVyi/XNs8A==","error":"http status 404","processing_time":0.33385014533997,"component":"remote_media"} [0m
Wed Dec 19, 2018 10:03:07 PM CSE-MOBI-CL [36m[2018-12-19 20:03:03] sitebuilder.NOTICE: "remote media info download failed" {"item_id":"5b991a4670179651078b4587","url":"https://www.itau.com.br/Download.aspx?Arquivo=SffNQpS0e3vYek/LpGpayw==","error":"http status 404","processing_time":0.34925603866577,"component":"remote_media"}
```
### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by elbidone** [comment]
log is from c-se env and not itau, but should be the same.

Check if the url of feed is correct: from prod and not int url. You can get the url looking for category of item_id mentioned on logs

**Comment by danconte72** [comment]
I couldn't find any item with the "item_id":"5b991a4670179651078b4587";
I will try get by medias.url

**Comment by danconte72** [comment]
Mongo Query to get item by the medias.url 
```
db.items.find({"medias.url":"https://www.itau.com.br/Download.aspx?Arquivo=RaPTgbe3ejriLA5eXr4cTA=="}).toArray()
```

**Comment by danconte72** [comment]
ParentId: 643;
Feed with this files: https://www.itau.com.br/relacoes-com-investidores/FeedMeuMobi.aspx?idCanal=lyyjtVJ4BExsF2fi1Kfy0Q==&linguagem=en

- All files set on this feed point to a 404
Url on feeds are missing `[relacoes-com-investidores]`
Wrong:  https://www.itau.com.br/Download.aspx?Arquivo=RaPTgbe3ejriLA5eXr4cTA==
Correct: https://www.itau.com.br/relacoes-com-investidores/Download.aspx?Arquivo=RaPTgbe3ejriLA5eXr4cTA==

**Comment by danconte72** [comment]
Must do send emails, for who?

**Comment by danconte72** [comment]
Last email sent on 2019/01/07

**Comment by danconte72** [comment]
I've checked using the following scripts 
#### Correct media url = Total 4866
```js
$ db.items.find({"medias.url":{$regex : "https://www.itau.com.br/relacoes-com-investidores/Download.*"}}).count()
4866
```
#### Wrong media url = Total 0
```js
$ db.items.find({"medias.url":{$regex : "https://www.itau.com.br/Download.*"}}).count()
0
```
There is no more `'remote media info download failed' $detailsError == "http status 404"` on [scalyr logs](https://eu.scalyr.com/events?filter=%27remote%20media%20info%20download%20failed%27%20$detailsError%20%3D%3D%20%22http%20status%20404%22&mode=log&teamToken=LxiLJcjvN4TQeugi6eciKw--&logSource=CSE-ITAU-MOBI-LX-CL&startTime=24%20hours)

Feed looks like ok too
![image](https://user-images.githubusercontent.com/32454870/52058255-34802180-254e-11e9-9b00-a21539b95fcd.png)

**Comment by danconte72** [comment]
Response sent on 2019-01-19 11:56
