### ISSUE TITLE
can't upload pdf media

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#627]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Carol from Katrium tried to upload `DIVULGAÇÃO DA PLR - 2018.pdf` as media but it raised following log error

```
[2019-01-09 20:06:13] sitebuilder.NOTICE: "remote media info download failed" {"item_id":"5c3645c79a645d1a339bee01","url":"https://firebasestorage.googleapis.com/v0/b/meumobi-sitebuilder.appspot.com/o/files%2F89e620a8-cdfb-1153-569a-e4736690fa73.pdf?alt=media&token=13876317-9cce-4e95-9cd2-5d00875be625","error":"http status 404","processing_time":0.63530206680298,"component":"remote_media"}
```

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
I've re-upload on s3 and update on meumobi to make sure the file is available

**Comment by elbidone** [comment]
the original pdf, using original name is saved on gdrive @shared/PRODUCTS/employee/Apps/infomobi/tmp/DIVULGAÇÃO DA PLR - 2018.pdf

**Comment by elbidone** [comment]
If we request from browser the file it returns following error

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>
No such object: meumobi-sitebuilder.appspot.com/files/89e620a8-cdfb-1153-569a-e4736690fa73.pdf
</Details>
</Error>
```

I've checked on firestorage and for the same date, 09/01, there are 3 pdf uploaded by katrium, none of them corresponding to the [file of error](https://firebasestorage.googleapis.com/v0/b/meumobi-sitebuilder.appspot.com/o/files%2F89e620a8-cdfb-1153-569a-e4736690fa73.pdf?alt=media&token=13876317-9cce-4e95-9cd2-5d00875be625). BUT means the upload feature worked for them.

Published the 9/Jan: PLR 2018 (51,271 bytes)
https://firebasestorage.googleapis.com/v0/b/meumobi-sitebuilder.appspot.com/o/files%2Ff6633a96-4653-bb78-7985-b7022408e2f4.pdf?alt=media&token=7d9ad10d-3685-45ed-87cb-938461614b73

Published the 9/Jan: PLR 2018 (51,271 bytes)
https://firebasestorage.googleapis.com/v0/b/meumobi-sitebuilder.appspot.com/o/files%2Fdaf9b8a8-ff2c-0313-6ebd-5779ccc8d221.pdf?alt=media&token=ffae4835-6ab5-4954-b5ca-6657e7e967c0

Published the 9/Jan: PLR Abril/2018 (48K)
https://firebasestorage.googleapis.com/v0/b/meumobi-sitebuilder.appspot.com/o/files%2Fac2cfaa5-704b-6edb-ff29-26abef3dc3f6.pdf?alt=media&token=2786889e-302d-4c6a-b7a5-a72719dc9377

**Comment by danconte72** [comment]
I've tested and actually the sitebuilder perform media correctly but firebase files can't be downloaded on infomobi app as explained here https://github.com/meumobi/infomobi/issues/296
