### ISSUE TITLE
Enable apache log rotation on it.c-se

### ISSUE THREAD

**Issue by danconte72** [meumobi/sitebuilder#628]
### Expected behaviour
On it.c-se env
#### Enable apache log rotation;
on */etc/apache2/sites-available/{site}*
```
CustomLog "/var/log/apache2/{site}/access.%Y-%m-%d" combined
```
```$ a2ensite {site}```
#### Track log on scalyr
on */etc/scalyr-agent-2/agent.json*
```
{
  path: "/var/log/apache2/{site}/access.*",
  attributes: {parser: "accessLog"},
  rename_logfile: {
    match: "/var/log/apache2/{site}/access.([0-9]{4}-[0-9]{2}-[0-9]{2})",
    replacement: "/scalyr/access.log"
  }
}
```
```$ sudo scalyr-agent-2 restart``` 

### Actual behaviour
- There is one single log file

### How to test
- open it app
- perform some requests
- certify if the requests were sent to scalyr

**Comment by elbidone** [comment]
`a2ensite` is useless, site is already enabled. Only need to restart apache to load config update (new apache log path)

**Comment by danconte72** [comment]
I did this.  on it. after update log rotation on files ```CustomLog "/var/log/apache2/{site}/access.%Y-%m-%d" combined```
```bash
$ a2ensite 000-mobi.comunique-se.com.br-itau 
$ a2dissite 000-mobi.comunique-se.com.br
$a2dissite 000-mobi.comunique-se.com.br-le-ssl.conf
$ a2ensite 000-mobi.comunique-se.com.br-le-ssl.conf-itau 
$ service apache2 reload
```

I`ve checked and the mobi and it.mobi files where equals

**Comment by danconte72** [comment]
Log rotation is working
```bash
root@CSE-ITAU-MOBI-LX-CL:~# ls /var/log/apache2/itau.mobi.comunique-se.com.br/access.2019-04-10 -al
-rw-r--r-- 1 root root 726882 Apr 10 09:02 /var/log/apache2/itau.mobi.comunique-se.com.br/access.2019-04-10
```
