### ISSUE TITLE
Enable siteubilder log rotation on it.c-se

### ISSUE THREAD

**Issue by danconte72** [meumobi/sitebuilder#629]
https://github.com/meumobi/sitebuilder/commit/d582a5e7dd5bce2560989ea583145759d4e93ac8

### Expected behaviour

Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
based on commit and this [post](https://www.networkworld.com/article/3218728/how-log-rotation-works-with-logrotate.html)
based on  `config/logrotate/comunique-se`
create `config/logrotate/itau-comunique-se` and commit to sitebuilder
create `config/logrotate/itau-comunique-se` into server 

updated on server `/etc/logrotate.d/sitebuilder` 
from `/home/meumobi/PROJECTS/mobi.comunique-se.com.br/shared/log/*.log`
to `/home/meumobi/PROJECTS/itau.mobi.comunique-se.com.br/shared/log/*.log`


wait 24h to check if logrotate performed correctly

**Comment by vdias38** [comment]
# Why it happens ?

we know how logrotate works because we use it on all our servers, but seems to have a mis-configuration on it.c-ser server, it the purpose of this issue.

**Comment by danconte72** [comment]
## why it happens
- There were not logrotate config for it.cse env on sitebuilder
- on server it was set for mobi.cse and not for it.mobi.cse (caused by server clone) - I've correctly updated configs. 

## how to fix
- [create](https://github.com/meumobi/sitebuilder/commit/c9d8fe2c4d81a7c6806cd753ae8d30d0dd602a49) a it.cse env logrotate config 
- manually update `/etc/logrotate.d/sitebuilder`

## how to test
- wait until tomorrow and check if log rotated
```bash
$ ls /home/meumobi/PROJECTS/itau.mobi.comunique-se.com.br/shared/log/ -al -t
```
