### ISSUE TITLE
Scalyr agent update required

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#634]
We ask that you update the Scalyr agent on your affected systems immediately. Instructions for updating the agent are available [here](https://eu.scalyr.com/help/scalyr-agent#upgrades). For additional protection, we recommend generating a new Write Log [API key](https://eu.scalyr.com/keys), installing that on your systems, and then deleting the old key.

You may check to see which systems are affected by running scalyr-agent-2 status -v and looking for this line:

View data from this agent at: https://upload.eu.scalyr.com/events...

If “https://” is not present, the agent is sending data over http and should be updated.

**Comment by danconte72** [comment]
```
$ sudo apt-get update
$ sudo apt-get install scalyr-agent-2
$ scalyr-agent-2 status -v | grep View
View data from this agent at: https://upload.eu.scalyr.com/events?filter=$serverHost%3D%27CSE-MOBI-CL%27
```
- elefante is ok 
- cse is ok
- is.cse is ok

in all 3 servers we have been sending logs correctly

**Comment by elbidone** [comment]
The email of scalyr support mention 2 IPs the traffic is coming from:
- 179.107.33.254 is a c-se server, we use 
  - mobi.comunique-se.com.br | 179.107.33.80
  - itau.mobi | 179.107.33.14
- **176.31.249.79 is elefante**

Please check the IPs of c-se servers, maybe it has changed since the deploy, when I get IPs. Also check with scalyr support why we don't see on elefante traffic using http.

**Comment by danconte72** [comment]
Accord with email on 2018-02-06

> I can confirm that insecure traffic has not started, and your log volume seems to be back to normal- so I think we are in good shape.
