### ISSUE TITLE
upgrade to latest version

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#638]

**Comment by elbidone** [comment]
- current version : v1.0.0-rc13 released on Nov 28, 2017
- latest version: v1.1.0-rc18 released on Nov 2, 2018

**Comment by danconte72** [comment]
Upgraded to master after some bugs on  v1.1.0-rc18
Updated [docs](https://github.com/meumobi/ion-employee/wiki/Image-flow-server:-Operating-hand-book) on how to update/manage/build imageflow server
