### ISSUE TITLE
upload file (logo) not available

### ISSUE THREAD

**Issue by vdias38** [meumobi/sitebuilder#639]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Can't save a new error on site, raise an error on logs (see details below)

### Steps to reproduce
1. login as admin
2. click on content>business_info
3. upload a file as logo and save

Should observe an error on logs as shown below

```
[2019-02-13 13:12:20] sitebuilder.ERROR: "uploadFile failed" {"model":"[object] (SiteLogos: {\"id\":\"545\"})","path":"uploads/site_logos","message":"upload folder is not writeable","exception":"[object] (Exception(code: 0): upload folder is not writeable at /home/meumobi/PROJECTS/meumobi.com/releases/20181119114456/sitebuilder/lib/utils/FileUpload.php:87)","component":"images"}
```

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by elbidone** [comment]
I've updated permissions to fix it
`root@ks387594[ELEFANTE]:/home/meumobi/PROJECTS/meumobi.com# chmod -R 777 shared/uploads/site_logos/`

This should be running when deployed with capistrano [task :permission](https://github.com/meumobi/sitebuilder/blob/9a53be412f34126d41c376605414fea00be1fe4e/sitebuilder/Capfile.rb#L31). **Need to investigate why permissions was not well setted**

**Comment by elbidone** [comment]
Also update `uploads/site_photos` face the same issue but with a different error msg `download folder is not writeable`

`# chmod -R 777 shared/uploads/site_photos/`

**Comment by danconte72** [comment]
capistrano permissions worked properly, but backup images script recreated folder with wrong mod.
