### ISSUE TITLE
meumobi dot com is out error 500

### ISSUE THREAD

**Issue by danconte72** [meumobi/sitebuilder#642]
![image](https://user-images.githubusercontent.com/32454870/53333327-4c8c5c00-38d4-11e9-9cd0-a782f122db74.png)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
I can't connect through ssh 
![image](https://user-images.githubusercontent.com/32454870/53333452-b0af2000-38d4-11e9-9f08-d0b0982c08d7.png)

**Comment by vdias38** [comment]
due to error of payment, resolved after payment and reboot
