### ISSUE TITLE
add new script to re-process pdf thumbnails

### ISSUE THREAD

**Issue by vdias38** [meumobi/sitebuilder#651]

**Comment by danconte72** [comment]
- based on cleanContent scrip
- should check if can filter by siteid/categoryid
- should get all items with pdf media and add a ProcessRemoteMedia task for each on stack;
- should check if previous thumbs are deleted after reprocess

**Comment by vdias38** [comment]
Why don't use #586 ?

**Comment by danconte72** [comment]
> Why don't use #586 ?

We should and also add a siteid param, also check if process delete previous files.
Is it necessary a categoryId filter?

**Comment by vdias38** [comment]
> Is it necessary a categoryId filter?
What is your suggestion ? it depends on your analysis, if it's one line more and no risk make sense, if it's complex could be avoid

**Comment by danconte72** [comment]
> What is your suggestion ? 

It's useful but just as an optional param. If not passed it will do for all site categories
Site_id should be mandatory  
It's quite simple, just add one line more.

```php
    $conditions = array(
        'medias' => [
            '$elemMatch' => [
                "type" => $type,
                "thumbnails" => [ '$size' => 0 ]
            ]            
        ],
        'site_id' => $site_id,
    );
    if ($parent_id) {
        $conditions['parent_id'] = $parent_id;
    }
    $items = Items::find('all', array('conditions' => $conditions));
```

**Comment by vdias38** [comment]
If think site_id and category_id could be optional, don't see any reason to set site_id as mandatory. If site_id not provided process all media from db

**Comment by danconte72** [comment]
- script add correctly medias to reprocess;
- but it not delete previous thumbnails linked with item;
### investigating which delete method is the best
- alter ProcessRemoteMedia to delete previous thumbnail file;
- delete thumbnail when script (regenerate thumb) is ran;
- delete all pdf_thumbnail files from server and run for all sites/categories

**Comment by danconte72** [comment]
### alter ProcessRemoteMedia to delete previous thumbnail file;
### delete thumbnail when script (regenerate thumb) is ran;
- file on item.medias.thumbnails.url is a absolute path as `https://meumobi.lvh.me/uploads/pdf_thumbnail/cddf4de4d42189dee4617a866e04d269.png`
### delete all pdf_thumbnail files from server and run for all sites/categories
- easiest solution;


# I'm still writing this comment...

**Comment by danconte72** [comment]
- On delete items through UI, thumbnails are deleted
