### ISSUE TITLE
Prevent multiple push sent in a short period

### ISSUE THREAD

**Issue by vdias38** [meumobi/sitebuilder#654]
### Expected behaviour
Tell us what should happen

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
update the following function  https://github.com/meumobi/sitebuilder/blob/ceb5699fcce7ac271424441a46edf16b55570959/sitebuilder/lib/meumobi/sitebuilder/services/CreateItem.php#L107

to 
```php
protected function sendPushNotification($item)
{
	$category = $item->parent();
	$limitDate = gmdate('Y-m-d H:i:s', strtotime("-2 days"));
	if ($item->published < $limitDate) {
		Logger::warning('push notification', 'out to date push', [
			'site_id' =>$item->site_id,
			'parent_id' =>$item->parent_id,
			'title' =>$item->title,
			'published' =>$item->published
		]);
		return;
	}

	if ($item->is_published && $category->notification) {
		$job = WorkerManager::enqueue('push_notification', [
			'item_id' => $item->id(),
			'category_id' => $item->parent_id
		]);
	}
}
```

**Comment by danconte72** [comment]
do not use hardcoded limitdays config

**Comment by danconte72** [comment]
add a scalyr alert to monitor when it happens

**Comment by vdias38** [comment]
check could not be done on `sendPushNotification` function should do only one thing.
Avoid providing implementation, prefer design, in this case how to insert the check on push sending flow. The implementation should be obvious if correctly designed.

**Comment by vdias38** [comment]
`published` is a field of articles but not of items, how it works if sending push of item that is not an article ?

**Comment by danconte72** [comment]
should create a function
**shouldSendPush**
it will check 
- if $item->is_published
- if $category->notification
- if type in (Articles, Polls, Results)
  -  if published date > limitDate
- if type in (Contacts, Events) do not check limitDate

and will returns true if should 
and false if not - must to log why push will be not sent

### limitDate
based on current date - Config.limitDays

### types on servers
On cse [ "articles", "events", "files", "results", "promotions" ]
On it.cse [ "articles", "events" ]
On elefante [ "business", "articles", "products", "promotions", "polls", "contacts", "events"]
but products, business, promotions has no items after 2014
