### ISSUE TITLE
add application/mp3 check on generic media handler

### ISSUE THREAD

**Issue by danconte72** [meumobi/sitebuilder#656]
based on https://github.com/meumobi/IRmobi/issues/327
update on [generic media handler](https://github.com/meumobi/sitebuilder/blame/master/sitebuilder/lib/meumobi/sitebuilder/services/ProcessRemoteMedia/GenericMediaHandler.php#L69)   
```php
//FROM
if ($type == 'application/octet-stream' && $response->headers('Content-Disposition')) {
//TO
if (($type == 'application/octet-stream' || $type == 'application/mp3' )  && $response->headers('Content-Disposition')) {
```

**Comment by vdias38** [comment]
Should re-process all media.type="application/mp3", how could we achieve it ?

**Comment by danconte72** [comment]
To regenerate
```
$ php sitebuilder/script/images/regenerate_media_thumbnail.php --type=application/mp3 
```
It will reprocess all items with a type=application/mp3

**Comment by danconte72** [comment]
rename regenerate_media_thumbnail to reprocess_remote_media to be more semantic
