### ISSUE TITLE
Emails not sent

### ISSUE THREAD

**Issue by vdias38** [meumobi/sitebuilder#665]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tested when invite user or visitor none email is received

### Steps to reproduce
1. login
2. invite a user

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
[We've moved mailer from local to smtp last year](https://github.com/meumobi/sitebuilder/issues/550#issuecomment-372735974).  
[Instructions](https://linuxconfig.org/configuring-gmail-as-sendmail-email-relay) should be copied on [HOWTO Setup Debian 9 for meumobi](https://docs.google.com/document/d/1kw_UAQmkuvSuidaMmjgKF6Xl2fembEWolFtONAoiWug/edit?usp=sharing)

**Comment by vdias38** [comment]
1. check which emails have been lost since migration
2. remove email enqueued

**Comment by danconte72** [comment]
### Error
Try to send email (verbose) on GUEPARDO
```bash
root@vps673381:/home/meumobi# sendmail -i -v -Am -- daniel.conte@meumobi.com
teste
...
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
>>> QUIT
221 2.0.0 closing connection j66sm18019510wmb.24 - gsmtp
daniel.conte@meumobi.com... Deferred: Temporary AUTH failure
Closing connection to gmail-smtp-msa.l.google.com.
```
I've tried from mobi.cse and It worked
```
root@CSE-MOBI-CL:~# sendmail -i -v -Am -- daniel.conte@meumobi.com
sent from mobi cse
...
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
>>> AUTH LOGIN
334 VXNlcm5hbWU6
>>> Y29udGFjdEBtZXVtb2JpLmNvbQ==
334 UGFzc3dvcmQ6
...
```
- The main difference that On Guepardo AUTH LOGIN does not work
- Error: "Deferred: Temporary AUTH failure"
### Searchs for Error
- [[SOLVED] Sendmail Temporary auth failure](http://www.linuxforums.org/forum/servers/199055-sendmail-temporary-auth-failure.html)
- [How to Fix "Sendmail: Temporary Auth Failure"](https://www.golinuxhub.com/2013/06/sendmail-temporary-auth-failure.html)
I've tried and this fixes not worked

A lot of fixes and [tutorials]((https://access.redhat.com/solutions/6876) talk about sasl
I've installed
```
sudo apt-get install libsasl2-bin
sudo apt-get install libsasl2-modules
```

Then restarted 
````
sudo /etc/init.d/saslauthd restart
sudo  /etc/init.d/sendmail restart
```
And retested 
```
root@vps673381:/etc/mail# sendmail -i -v -Am -- daniel.conte@meumobi.com
teste novo
daniel.conte@meumobi.com... Connecting to gmail-smtp-msa.l.google.com. port 587 via relay...
220 smtp.gmail.com ESMTP w10sm20030683wrr.67 - gsmtp
>>> EHLO vps673381.ovh.net
250-smtp.gmail.com at your service, [217.182.171.27]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
>>> STARTTLS
220 2.0.0 Ready to start TLS
>>> EHLO vps673381.ovh.net
250-smtp.gmail.com at your service, [217.182.171.27]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
>>> AUTH LOGIN
334 VXNlcm5hbWU6
>>> Y29udGFjdEBtZXVtb2JpLmNvbQ==
334 UGFzc3dvcmQ6
>>> bWV1bW9iaTEyMw==
235 2.7.0 Accepted
>>> MAIL From:<meumobi@vps673381.ovh.net> SIZE=11 AUTH=meumobi@vps673381.ovh.net
250 2.1.0 OK w10sm20030683wrr.67 - gsmtp
>>> RCPT To:<daniel.conte@meumobi.com>
>>> DATA
250 2.1.5 OK w10sm20030683wrr.67 - gsmtp
354  Go ahead w10sm20030683wrr.67 - gsmtp
>>> .
250 2.0.0 OK  1559583423 w10sm20030683wrr.67 - gsmtp
daniel.conte@meumobi.com... Sent (OK  1559583423 w10sm20030683wrr.67 - gsmtp)
Closing connection to gmail-smtp-msa.l.google.com.
>>> QUIT
221 2.0.0 closing connection w10sm20030683wrr.67 - gsmtp
```
Email got
![image](https://user-images.githubusercontent.com/32454870/58822327-9d1b0000-860d-11e9-8b03-9a97025b4015.png)

**Comment by danconte72** [comment]
I've tested from ui to reset a visitor password and it worked
![image](https://user-images.githubusercontent.com/32454870/58822519-1b77a200-860e-11e9-8d37-86dd62a35baf.png)

**Comment by danconte72** [comment]
- Updated [Documentation](https://docs.google.com/document/d/1kw_UAQmkuvSuidaMmjgKF6Xl2fembEWolFtONAoiWug/edit#)
- Added [Scalyr alert](https://eu.scalyr.com/alert?id=%2FWJ5IewzFrING6Z0&teamToken=LxiLJcjvN4TQeugi6eciKw--) when email send failure
- Updated [Testbook](https://github.com/meumobi/sitebuilder/blob/master/TESTBOOK.md#4-sending) 
- We lost one single email
```
Jun  3 18:42:52 vps673381 sm-mta[4762]: x53GgqvX004760: to=<jscanzi@katrium.com.br>, delay=00:00:00, xdelay=00:00:00, mailer=relay, pri=121827, relay=gmail-smtp-msa.l.google.com. [108.177.15.108], dsn=4.0.0, stat=Deferred: Temporary AUTH failure
//But it was sent one hour later when service was fixed
Jun  3 19:36:39 vps673381 sm-mta[23334]: x53GgqvX004760: to=<jscanzi@katrium.com.br>, delay=00:53:47, xdelay=00:00:01, mailer=relay, pri=841827, relay=gmail-smtp-msa.l.google.com. [173.194.76.108], dsn=2.0.0, stat=Sent (OK  1559583399 w3sm9852895wmc.8 - gsmtp)
```
