### ISSUE TITLE
lock already acquired on c-se

### ISSUE THREAD

**Issue by vdias38** [meumobi/sitebuilder#669]
### Expected behaviour
lock already acquired should be an exception, if too long should hide a none expected behaviour.

### Actual behaviour
Yesterday c-se worker was locked for long time (more than 2h), should investigate the reason.

![Resolved_Scalyr_alert__lock_already_acquired__Thu_Jun_6__2019_8_22_44_PM_-_UTC__-_victor_dias_meumobi_com_-_MeuMobi_Mail](https://user-images.githubusercontent.com/9011612/59093641-53336200-890c-11e9-8963-ae5eddf30fc7.png)

A similar behavior was observed last year https://github.com/meumobi/sitebuilder/issues/596

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
A similar issue https://github.com/meumobi/sitebuilder/issues/596

**Comment by danconte72** [comment]
So many process remote media 
```
//ON CSE
> db.jobs.distinct("type")
[ "process_remote_media" ]
> db.jobs.count()
712
> db.jobs.distinct("type")
[ "process_remote_media" ]
> db.jobs.count()
709
//ON IT.CSE
> db.jobs.count()
1082
> db.jobs.distinct("type")
[ "process_remote_media" ]
> db.jobs.count()
1033
> db.jobs.count()
1030
```
Checksum updated 
![image](https://user-images.githubusercontent.com/32454870/59127971-4da33f80-893f-11e9-9360-b40ef98b7978.png)

Just few items created on that period
![image](https://user-images.githubusercontent.com/32454870/59127865-0026d280-893f-11e9-8d03-7d9ecb135bd2.png)

Items updated on that period by site
![image](https://user-images.githubusercontent.com/32454870/59127066-01570000-893d-11e9-8dec-623e077de616.png)

ITEMS UPDATE BY CATEGORY
![image](https://user-images.githubusercontent.com/32454870/59127808-dcfc2300-893e-11e9-94b0-6e7e29b10095.png)

Categories (!= events) with >=100 items updated 
```
// on cse
mysql> select id, title,site_id,type from categories where id in (641,659,349,173,644,632,587,92,573,69,512,481) and type <> 'events';
+-----+---------------------+---------+----------+
| id  | title               | site_id | type     |
+-----+---------------------+---------+----------+
| 641 | Outros Comunicados  |      68 | articles |
| 659 | Other Announcements |      69 | articles |
+-----+---------------------+---------+----------+
2 rows in set (0.00 sec)
// on it.cse
mysql> select id, title,site_id,type from categories where id in (641,659,349,173,644,632,587,92,573,69,512,481) and type <> 'events';
+-----+---------------------+---------+----------+
| id  | title               | site_id | type     |
+-----+---------------------+---------+----------+
| 641 | Outros Comunicados  |      68 | articles |
| 659 | Other Announcements |      69 | articles |
+-----+---------------------+---------+----------+
2 rows in set (0.00 sec)
```

### Categories to check with uncommon behavior
- Itau IR - Other Announcements - 69-659 [feed](https://www.itau.com.br/relacoes-com-investidores/FeedMeuMobi.aspx?idCanal=bTGUGfB1lWzfGrlGkyuiOw==&linguagem=en)
![image](https://user-images.githubusercontent.com/32454870/59130143-fb651d00-8944-11e9-92b4-7dca4b0d31f9.png)
- Itau RI - Outros Comunicados - 68-641 [feed](https://www.itau.com.br/relacoes-com-investidores/FeedMeuMobi.aspx?idCanal=bTGUGfB1lWzfGrlGkyuiOw==)
![image](https://user-images.githubusercontent.com/32454870/59130067-cc4eab80-8944-11e9-9b80-c1710a832f96.png)
### Attention
Each category has 1152 items!!!
```
> db.items.find({parent_id:641}).count()
1152
> db.items.find({parent_id:659}).count()
1152
```
Feed contains 1152 items.
![image](https://user-images.githubusercontent.com/32454870/59130789-cce84180-8946-11e9-91ff-ae34c04977f9.png)

**Comment by danconte72** [comment]
### Why it happens
- 2 categories of itau (659, 641) where updated. All items where updated, the categories are had 1152 items each, feed is on Exclusive mode (import all items of feed).
- All items with files, we launch a process remote media every time an item is updated

**Comment by vdias38** [comment]
## Why it happens

urls of media were wrong, leading to dev/homolog env.
