### ISSUE TITLE
Use workers instead of services for async tasks

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#67]
Most of the workers are being treated as Services, like the Import Rss, Publish items etc.
They are implemented at lib/meumobi/sitebuilder/services. Mixed with the DDD domain services like the VisitorPasswordGenerationService.

They are recurring jobs, and because of that they should be on lib/meumobi/sitebuilder/workers
A recurring job is a common job, that at the end of it's "perform" method, it self enqueue again.

Here are some examples and libs for reference:

- https://github.com/tobiassvn/sidetiq/wiki/Basic-Usage
- http://stackoverflow.com/questions/25798013/how-do-i-schedule-recurring-jobs-in-active-job-rails-4-2
- http://stackoverflow.com/questions/14964567/how-to-correctly-implement-recurring-tasks-with-time-frequency-set-by-user

**Comment by juliogreff** [comment]
Since we're doing a bigger refactoring and moving all the code to ruby, shouldn't we just spec this out on the new architecture already, instead of trying to put lipstick on the pig?

It seems to me that doing this refactoring in PHP now is a bit wasteful. @elbidone thoughts?

**Comment by elbidone** [comment]
The pb is that specs are on stby, I'm the unique editor till now,.... And it concerns a bug resolution in a major feature of our platform, RSS import. If to do it right, to guarantee no more bugs and service broken, we need to refactor my thought is that we MUST refactor in php. Big Companies use our platform and any bug is forbidden, our **quality of service is not negotiable**.
