### ISSUE TITLE
Update RSS items (identified by guid)

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#68]
Current version only create items, but when users update feeds it's not considered. We'll add this feature to improve consistency between content hosted by user and meumobi records.

**Comment by t4deu** [comment]
This happens because the Articles::addFeed() is creating and filling the properties of the created item, there is no update.

To fix we need to split this on two methods, one to load or create a new item, and the other to update the item properties

**Comment by juliogreff** [comment]
This one now depends on #120 

After that is done, we'll only have to change the **UpdateNewsFeed** service. The *createItem* method will be renamed to *createOrUpdateItem*, and it will delegate to the corresponding service. The decision of which service we should delegate to will be done by the following method:

```php
protected function selectService($category, $article) {
    $categoryHasArticle = Items::find('count', ['conditions' => [
        'parent_id' => $category->id,
        'guid' => $article->guid
    ]]);

    return $categoryHasArticle
        ? new UpdateItem
        : new CreateItem;
}
```

We'll need to rename **ItemCreation** to **CreateItem** to comply with our guidelines, but that will be done in a later ticket.

**UpdateItem** does not exist yet, and will be created. Updating the rest of the platform to use the UpdateItem service will be done in a later ticket, not on this one. For the moment, it can be only a placeholder, still pointing to the old logic, unless that would create problems.

We'll also update the *isNewContent* method. It'll look like the following:

```php
protected function isNewContent($category, $article) {
    return !Items::find('count', ['conditions' => [
        'parent_id' => $category->id,
        'guid' => $article->guid,
        'checksum' => $article->checksum,
    ]]);
}
```

Note that there's a "checksum" property in the $article. That is new, and should be generated by the *extractArticles* method, with the algorithm below. We'll also need to apply that to all existing items with a migration.

```php
// both the title and the description should be the ones after any sanitizing or purifying
$checksum = md5($article->title . $article->description);
```

**Comment by t4deu** [comment]
According to the implementation of the "isNewContent" described above, even if an item with the same "guid" already exists a new item will be created  every time the checksum is different.

In this case, if an item had some simple changes or a misspelling fix in the title or description, it will not be updated, but a duplicated one will be created?
