### ISSUE TITLE
wrong created_date on items from RSS feed, it's always equals to pubdate and not the date of creation on db as expected

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#72]

**Comment by t4deu** [comment]
Well, you must have a reason for this in the past. Because a before save observer has created to make this change:
https://github.com/meumobi/sitebuilder/blob/master/sitebuilder/app/models/items/Articles.php#L333

Removing the observer you solve this

**Comment by t4deu** [comment]
Could not find the repository history the commit that added the observer.
But I think the observer has added when the items order was determined by creation date.
Now the observer is no longer needed since the order is determined by the item.order field.
I'm gonna remove the observer

**Comment by juliogreff** [comment]
You might also need to update the API for the ItemsController::latest(), since it currently uses the creation date for ordering. We need to change that to use the date the item was published on.

**Comment by juliogreff** [comment]
@t4deu did you address my last comment?

**Comment by t4deu** [comment]
No @juliogreff , I'm only seeing it now.
I also check for the "item.is_published"?

**Comment by juliogreff** [comment]
I thought that was there already. But if it's not, yes.

**Comment by elbidone** [comment]
I've create #87, it could concern this one also. When I import feed without pubdate it raises date in 1969. I think it should use created date for published date
