### ISSUE TITLE
one media missing on edit item page

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#77]
Editing on INT item below, I only see one media on site-builder interface instead of 2 on mongodb

https://www.evernote.com/l/APWykkiRBbhI-om-zVIfKT09NmsDbPeNMxoB/image.png

```
{ "_id" : ObjectId("5526e98db5a508962e8b4567"),
...
"medias" : [ 	{ 	"type" : "application/pdf", 	"length" : "", 	"title" : "Microsoft Board Member Mason Morfit", 	"url" : "http://video.ch9.ms/ch9/37ec/49f91064-a1d6-499b-a76b-054d2b9f37ec/MasonMorfit.mp3" }, 	{ 	"type" : "video/mp4", 	"length" : "", 	"title" : "Microsoft Board Member Mason Morfit", 	"url" : "http://video.ch9.ms/ch9/37ec/49f91064-a1d6-499b-a76b-054d2b9f37ec/MasonMorfit.mp3" } ]
...
```

**Comment by elbidone** [comment]
And check also this mis-implementation:
https://www.evernote.com/l/APX8ofp-5w5Gw5fZhuOiEh-jVy6p3MSbYGIB/image.png

**Comment by elbidone** [comment]
I understand why only one appears, it's because the second has a type != application/pdf.

So please check the mis-implementation described on previous comment and unconsider this issue

**Comment by t4deu** [comment]
The mis-implementation is because the element is hidden by default and dynamically made visible with javascript.

To fix instead of making the element visible, i'm gonna remove the "hidden" class with javascript

**Comment by elbidone** [comment]
Guarantee that this solution is consistant. On INT I continue to see this morning same mis-implementation on /sites/custom_domain.
If exist hide/show functions you should use them instead of removeClass. The issue is that you mix behaviors / techniques and raise inconsistency that lead to raise bugs in future. 
Check how themes do, ie. first
