### ISSUE TITLE
items should not be removed when the extension is disabled

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#82]
Disabled extension remains on db, at any moment user could re-enabled it. We should use status to pause import not to remove items. Another action, independent of extension, is responsible for removing items.
On current release there's no way to pause import.

**Comment by elbidone** [comment]
it's maybe related to #85. Removing extension should remove content, but disabling should pause the importation.
I remove this issue of rel-2.6.2, it's not urgent

**Comment by t4deu** [comment]
Remove the line 141, from the Extension::disable method:
```php
public static function disable($extension) {
...
  $category->removeItems();
...
}
```
