### ISSUE TITLE
Create initial spec for new version

### ISSUE THREAD

**Issue by juliogreff** [meumobi/sitebuilder#83]
The bare minimum we need is:

* Items
* Categories
* Sites
* Users

**Comment by elbidone** [comment]
I've initiate a spec "what neumobi do" check wiki. Before writing a spec of
new product it could be better to write the spec of current. And later
describe how to manage current behavior on new architecture.
Em 14/05/2015 15:10, "Julio Greff" <notifications@github.com> escreveu:
