### ISSUE TITLE
when RSS feed items have no pubdate should use the created date

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#87]
here an example
http://respostassustentaveis.com.br/feed/rss/

**Comment by t4deu** [comment]
To confirm:
when RSS feed items have no pubdate should use the created date **as the value of pubdate**, right?

**Comment by elbidone** [comment]
yes

**Comment by t4deu** [comment]
Another thing
The Item also have the "published" field that is used to order the items on the GET /latest request, and currently has nothing to do with the "puddate" field

**Comment by juliogreff** [comment]
For RSS feeds, published should be the same as pubdate.

**Comment by t4deu** [comment]
Ok, so there is a reason for have two properties, pubdate and published, why not use only only "published"?

**Comment by juliogreff** [comment]
Good point :)

We'll need to update all the API clients to get rid of pubdate though.

**Comment by t4deu** [comment]
ok, so I'm gonna remove the puddate and set the "published" value on the" UpdateFeedsWorker".

And for the issue #83, may be good to add an API versioning, to allow make API changes with a more safer way for the API clients

**Comment by elbidone** [comment]
ok, I agree, check what's the better solution, keep pubdate or published

**Comment by t4deu** [comment]
I think that is better keep "published", it's simpler to implement and to me has more meaning than "pubdate"
