### ISSUE TITLE
remove_sites script not work

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#88]
I've removed site 16 on PROD, # php remove_sites.php 16, categories with site_id=16 remains

**Comment by t4deu** [comment]
Yes, it's a confirmed bug.
It's happening because instead of what the action SitesController::remove does, the script don't load the site before remove it, and the "before delete" observers don't work properly because of this.

To fix this update the script to load the site before remove:
```
$site = Model::load('Sites')->firstById($site_id)->delete();
```
