### ISSUE TITLE
remove_categories script raises error if site_id not exist

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#89]
If you try to remove a category whose site not exist it raises an error. 

- Why the script need the site to remove a category ?  
-How to remove a category whose site not exist ?

**Comment by t4deu** [comment]
The error is happening on the "Categories::updateParentTimestampsWhenDeleted" observer.

The script don't need a site to remove a category, but every time a category is created/updated/removed it's parent site and category "modified" field is updated, for Etag purposes.

The only way that I found to prevent the error is adding a try/catch block in the "Categories::updateParentTimestampsWhenDeleted" observer.

But I think there may exist a better way to do this, I just don't know what
