### ISSUE TITLE
Remove remaining notification jobs if a site has no push configured or the push for the category is disabled

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#96]

**Comment by juliogreff** [comment]
This seems like a lot of bug-prone code. Wouldn't it be easier to check that information on the job itself, and just move on if the preconditions changed?

**Comment by t4deu** [comment]
Yes, I'm agree that less code is always better. And the verification that you mentioned is already being made.
But @elbidone argued that processing the remaining jobs already knowing that the site or category had disabled push is dumb and generates a lot of unnecessary log messages

**Comment by elbidone** [comment]
I agree @juliogreff, we've seen huge number of ERROR notifications due to issue #98.
@tadeu, comment on this issue please the verifications and logs you've mentioned on previous comment.

I see inconsistencies on logs, I'd like your report and if necessary you should open a new issue about.
```
[2015-05-27 03:18:02] sitebuilder.ERROR: error executing worker {"job_id":"55651b3fb5a508f
72f8b459a","job type":"push_notification","job params":{"item_id":"55651b3fb5a508f72f8b459
9","category_id":"3"},"exception":"app\\models\\RecordNotFoundException","message":"item n
ot found"} 
[2015-05-27 03:18:02] sitebuilder.ERROR: Push notification error: no push app configured f
or site {"item id":"55651b48b5a508f72f8b459b","category id":"32","site id":7}

```

**Comment by juliogreff** [comment]
I believe we should not fix this one this way, so I'm closing this one.
