### ISSUE TITLE
Only send push notification when a item is created

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#97]

**Comment by juliogreff** [comment]
If this is a bug, you should include the current behavior (so we can check if the bug was really fixed), and also the rationale on why you need the behavior to be different.

**Comment by t4deu** [comment]
According to the logs the notifications are being sent when the item is created and updated.
Ideally, the user should be notified only for new content

**Comment by elbidone** [comment]
ok, but you should provide more informations. 
# What occurs
You can show the log of items updated and the log of push  for these same items. By this way we'll be able to test that it not occurs anymore after the fix. 
# How to reproduce
Update existing item (**no need to be feed, alright ?**) of category with push enabled. And grep on log/sitebuilder.log "push" and category_id
# How to fix
Which code is responsible to push item to jobs queue ? how to fix it ? 

How to test is not necessary because redundant with how to test

**Comment by elbidone** [comment]
ok, but you should provide more informations. 
# What occurs
You can show the log of items updated and the log of push  for these same items. By this way we'll be able to test that it not occurs anymore after the fix. 
# How to reproduce
Update existing item (**no need to be feed, alright ?**) of category with push enabled. And grep on log/sitebuilder.log "push" and category_id
# How to fix
Which code is responsible to push item to jobs queue ? how to fix it ? 

How to test is not necessary because redundant with how to test

**Comment by elbidone** [comment]
The rule is: only create Push job when item is created and the update_feed priority != 1

**Comment by t4deu** [comment]
# How to reproduce
Currently, the push notification is sent only when creating items, both imported and manually created.
Here a feed import log present in the issue #99, where only 2 items are created :
```
[2015-05-28 08:45:46] sitebuilder.INFO: updating feeds {"priority":0} 
[2015-05-28 08:46:42] sitebuilder.DEBUG: updated feeds {"5552171b297e6b9c048b4567":{"extension_id":"5552171b297e6b9c048b4567","total_articles":10,"updated_articles":8,"created_articles":2,"removed_articles":0,"total_images":21,"failed_images":0,"category_id":"6"}} 
[2015-05-28 08:46:42] sitebuilder.INFO: finished updating feeds {"total_updated_feeds":1,"total_failed_feeds":0,"failed_feeds":[],"priority":0,"elapsed_time":55.282558917999} 
```
And only 2 push jobs had been registered
```
> db.jobs.find();
{ "_id" : ObjectId("55670013297e6b170f8b4568"), "params" : { "item_id" : "55670013297e6b170f8b4567", "category_id" : "6" }, "created" : ISODate("2015-05-28T11:46:27.367Z"), "modified" : ISODate("2015-05-28T11:46:27.367Z"), "type" : "push_notification", "priority" : NumberLong(0) }
{ "_id" : ObjectId("55670016297e6b170f8b456a"), "params" : { "item_id" : "55670016297e6b170f8b4569", "category_id" : "6" }, "created" : ISODate("2015-05-28T11:46:30.363Z"), "modified" : ISODate("2015-05-28T11:46:30.363Z"), "type" : "push_notification", "priority" : NumberLong(0) }
```
And since the issue #68 has reverted, there is no way to update an item thought feed import.

# How to fix
The code responsible to queue push jobs is the observer Items::sendPushNotification:
```php
  public static function sendPushNotification($self, $params, $chain)            
  {                                                                              
   ...                                               
    // only if new and category send notifications                               
    if (!$item->id() && $item->is_published && $category->notification) {   
      if ($id = $item->id()) {                                                   
        WorkerManager::enqueue('push_notification',  ['item_id' => $id, 'category_id' => $category->id]);
      }
      ...                                                             
    }                        
  }
```
To prevent send push if update_feed priority != 1, need to remove the observer and manually call the $item->sendPushNotification(); after the item be created in the UpdateFeedsWorker::updateArticle method. But I don't think that this is the best solution

**Comment by elbidone** [comment]
Update: only create Push job when item is created and the update_feed priority is HIGH

**Comment by juliogreff** [comment]
#68 has been reverted, but we'll reimplement that, so make sure to only generate push notifications for items that are created. Remember that we can still update articles from the web interface.

**Comment by t4deu** [comment]
To prevent the code duplication use a service to create the items and enqueue the push messages, this will also ensure that the push message are sent only for item creation.

1, Create the service at lib/meumobi/sitebuilder/services/ItemCreation.php
```
class ItemCreation
{
  public function create($item, $sendPush = false)
  {
    //TODO create item
  }
  protected function sendPushNotification()
  {
   //TODO enqueue push notification
  }
}
```
2, Remove the Items::sendPushNotification() observer

3, update UpdateFeedsWorker::updateArticle() and ItemsController::create() to use the ItemCreation service to create the items

**Comment by t4deu** [comment]
Add a build method in the service to generate an new Item instance, and replace the duplicated code in the controllers:
```php
class ItemCreation
{
  public function build($siteId, $categoryId);
}
```
