### ISSUE TITLE
Only update items on feed import if the feed item is updated

### ISSUE THREAD

**Issue by t4deu** [meumobi/sitebuilder#98]

**Comment by juliogreff** [comment]
Why, and how do you plan to check that the item was updated?

**Comment by t4deu** [comment]
Because there is no need to reimport an item when nothing was updated in the article.
@elbidone indicated that the pubdate of the article may be used to verify if the item is updated or not, but I'm not sure if it can be used for this

**Comment by elbidone** [comment]
what's your recommendation @t4deu ?

**Comment by juliogreff** [comment]
This was fixed when we reverted #68.
